// @ts-check
/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites.

Warmth checklist:
	Base: 0
	Covers feet: +1
	Covers legs: +1

	Materials:
	Thin: -1
	Normal: 0
	Thick: +1
	Very thick: +2

	Max warmth: 4
*/
function initLegs() {
	/** @type {ClothesItem[]} */
	const clothing = [
		new ClothesItem({
			index: 0,
			slot: "legs",
			name: "naked",
			name_cap: "Naked",
			variable: "naked",
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			state: 0,
			state_base: 0,
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "naked",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		}),
		new ClothesItem({
			index: 1,
			slot: "legs",
			name: "tights",
			name_cap: "Tights",
			variable: "tights",
			combat: {
				renderType: "waisthighs",
			},
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 1000,
			description: "They don't conceal much.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "tights.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 2,
			slot: "legs",
			name: "boy's gym socks",
			name_cap: "Boy's gym socks",
			variable: "boysgymsocks",
			combat: {
				renderType: "thighhighs",
				accessory: true,
				accColour: "#00f",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs", // Thighs?
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["school", "athletic"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 500,
			description: "Cushioned and breathable. Suitable for school, but not required.",
			shop: ["clothing", "school", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "boys_gym_socks.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 3,
			slot: "legs",
			name: "girl's gym socks",
			name_cap: "Girl's gym socks",
			variable: "girlsgymsocks",
			combat: {
				reference: "boysgymsocks",
				accessory: true,
				accColour: "#a354ce",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs", // Thighs?
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["school", "athletic"],
			gender: "f",
			femininity: 100,
			warmth: 2,
			cost: 500,
			description: "Cushioned and breathable. Suitable for school, but not required.",
			shop: ["clothing", "school", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "girls_gym_socks.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 4,
			slot: "legs",
			name: "stockings",
			name_cap: "Stockings",
			variable: "stockings",
			combat: {
				renderType: "thighhighs",
			},
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 1500,
			description: "Attractive and alluring.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "stockings.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 5,
			slot: "legs",
			name: "fishnet stockings",
			name_cap: "Fishnet stockings",
			variable: "fishnetstockings",
			combat: {
				renderType: "thighhighs",
			},
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_combat: 0,
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 0,
			cost: 1500,
			description: "Attractive and alluring.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "fishnet_stockings.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 6,
			slot: "legs",
			name: "fishnet tights",
			name_cap: "Fishnet tights",
			variable: "fishnettights",
			combat: {
				renderType: "waisthighs",
			},
			integrity: 25,
			integrity_max: 25,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_combat: 0,
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 1,
			cost: 1700,
			description: "Attractive and alluring.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "fishnet_tights.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 7,
			slot: "legs",
			name: "garter stockings",
			name_cap: "Garter stockings",
			variable: "garterstockings",
			combat: {
				renderType: "thighhighs",
			},
			integrity: 15,
			integrity_max: 15,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [
				"black",
				"navy blue",
				"brown",
				"wine",
				"grey",
				"light pink",
				"lilac",
				"soft brown",
				"blue",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"pale white",
				"pale yellow",
				"custom",
			],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 2,
			cost: 4000,
			description: "Sexy.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "garter_stockings.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 8,
			slot: "legs",
			name: "legwarmers",
			name_cap: "Legwarmers",
			variable: "legwarmers",
			combat: {
				renderType: "thighhighs",
			},
			integrity: 25,
			integrity_max: 25,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "neon blue", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 4,
			cost: 1500,
			description: "Cosy.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "legwarmers.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 9,
			slot: "legs",
			name: "christmas leg warmers",
			name_cap: "Christmas leg warmers",
			variable: "christmas",
			combat: {
				renderType: "thighhighs",
			},
			integrity: 25,
			integrity_max: 25,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "f",
			femininity: 200,
			warmth: 3,
			cost: 2500,
			description: "Festive.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "christmas_leg_warmers.png",
		}),
		new ClothesItem({
			index: 10,
			slot: "legs",
			name: "gold anklets",
			name_cap: "Gold anklets",
			variable: "goldanklets",
			combat: {
				renderType: "ankled",
				mainColour: "#e8b826",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "serving"],
			gender: "n",
			warmth: 0,
			cost: 25000,
			description: "Exotic and eye-catching.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "gold_anklets.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 11,
			/* TODO: Not sure why we have 2 naked? */
			slot: "legs",
			name: "naked",
			name_cap: "Naked",
			variable: "naked",
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			state: 0,
			state_base: 0,
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "naked",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		}),
		new ClothesItem({
			index: 12,
			slot: "legs",
			name: "striped thighhighs",
			name_cap: "Striped thighhighs",
			variable: "stripedthighhighs",
			combat: {
				reference: "plainthighhighs",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 300,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 3,
			cost: 3000,
			description: "Brimming with personality.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			accessory_colour_combat: 0,
			cursed: 0,
			location: 0,
			iconFile: "striped_thighhighs.png",
			accIcon: "striped_thighhighs_acc.png",
		}),
		new ClothesItem({
			index: 13,
			slot: "legs",
			name: "ankle socks",
			name_cap: "Ankle socks",
			variable: "anklesocks",
			combat: {
				renderType: "ankled",
				accColour: "#f5f0ee",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["school", "athletic"],
			gender: "n",
			femininity: 0,
			warmth: 1,
			cost: 500,
			description: "Perfect for sport.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "ankle_socks.png",
			accIcon: "ankle_socks_acc.png",
		}),
		new ClothesItem({
			index: 14,
			slot: "legs",
			name: "plain thighhighs",
			name_cap: "Plain thighhighs",
			variable: "plainthighhighs",
			combat: {
				renderType: "thighhighs",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 300,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 3,
			cost: 2500,
			description: "Simple and cute.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "striped_thighhighs.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 15,
			slot: "legs",
			name: "cow socks",
			name_cap: "Cow socks",
			variable: "cow",
			combat: {
				renderType: "kneehighs",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 400,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			femininity: 0,
			warmth: 2,
			cost: 1000,
			description: "Cute cow print.",
			shop: ["forest", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "brown", "light pink", "light blue", "light green", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "cow_socks.png",
			accIcon: "cow_socks_acc.png",
		}),
		new ClothesItem({
			index: 16,
			slot: "legs",
			name: "nurse socks",
			name_cap: "Nurse socks",
			variable: "nursesocks",
			combat: {
				reference: "stockings",
				mainColour: "#f00",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["white", "hospital pink", "light blue", "light green", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "f",
			femininity: 100,
			warmth: 2,
			cost: 900,
			description: "Worn by nurses at the local hospital.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_sidebar: 1,
			accessory_colour_options: ["red", "hospital pink", "light blue", "light green", "white", "black", "custom"],
			cursed: 0,
			location: 0,
			iconFile: "nurse_socks.png",
			accIcon: "nurse_socks_acc.png",
		}),
		new ClothesItem({
			index: 17,
			slot: "legs",
			name: "ribbon stockings",
			name_cap: "Ribbon stockings",
			variable: "ribbonstockings",
			combat: {
				renderType: "thighhighs",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 3,
			cost: 4000,
			description: "Cute.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "ribbon_stockings.png",
			accIcon: "ribbon_stockings_acc.png",
		}),
		new ClothesItem({
			index: 18,
			slot: "legs",
			name: "patterned dress socks",
			name_cap: "Patterned dress socks",
			variable: "twirly socks",
			combat: {
				reference: "striped socks long",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 1,
			cost: 1200,
			description: "Men's dress socks. Masculine, yet playful.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "twirly_socks.png",
			accIcon: "twirly_socks_acc.png",
		}),
		new ClothesItem({
			index: 19,
			slot: "legs",
			name: "polka dot socks",
			name_cap: "Polka dot socks",
			variable: "polka socks",
			combat: {
				reference: "striped socks long",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "neon blue", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 1,
			cost: 1200,
			description: "Patterned dress socks. Masculine, yet playful.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [
				"black",
				"blue",
				"brown",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"neon blue",
				"custom",
			],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "polka_socks.png",
			accIcon: "polka_socks_acc.png",
		}),
		new ClothesItem({
			index: 20,
			slot: "legs",
			name: "sports socks",
			name_cap: "Sports socks",
			variable: "sports socks short",
			combat: {
				reference: "striped socks short",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "athletic"],
			gender: "m",
			femininity: -100,
			warmth: 1,
			cost: 500,
			description: "Cushioned and breathable.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "short_sport.png",
			accIcon: "short_sport_acc.png",
		}),
		new ClothesItem({
			index: 21,
			slot: "legs",
			name: "knee-high sports socks",
			name_cap: "Knee-high sports socks",
			variable: "sports socks long",
			combat: {
				reference: "striped socks long",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "athletic"],
			gender: "m",
			femininity: -300,
			warmth: 2,
			cost: 800,
			description: "Cushioned and breathable.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "long_sport.png",
			accIcon: "long_sport_acc.png",
		}),
		new ClothesItem({
			index: 22,
			slot: "legs",
			name: "rib-knit socks",
			name_cap: "Rib-knit socks",
			variable: "striped socks long",
			combat: {
				renderType: "kneehighs",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 3,
			cost: 1200,
			description: "Men's ribbed socks, for his pleasure.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "long_stripe.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 23,
			slot: "legs",
			name: "rib-knit ankle socks",
			name_cap: "Rib-knit ankle socks",
			variable: "striped socks short",
			combat: {
				renderType: "ankled",
				accessory: true,
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 2,
			cost: 1000,
			description: "Men's ribbed socks, for his pleasure.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "short_stripe.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 24,
			slot: "legs",
			name: "striped kneehighs",
			name_cap: "Striped kneehighs",
			variable: "striped kneehighs",
			combat: {
				reference: "striped socks short",
				accessory: true,
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 2,
			cost: 2000,
			description: "Brimming with personality.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "striped_kneehighs.png",
			accIcon: "striped_kneehighs_acc.png",
		}),
		new ClothesItem({
			index: 25,
			slot: "legs",
			name: "sheer leggings",
			name_cap: "Sheer leggings",
			variable: "sheerleggings",
			combat: {
				reference: "tights",
			},
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: [
				"black",
				"navy blue",
				"fleshy",
				"light brown",
				"soft brown",
				"brown",
				"wine",
				"grey",
				"light pink",
				"lilac",
				"blue",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"pale white",
				"pale yellow",
				"custom",
			],
			colour_sidebar: 1,
			type: ["normal", "dance", "athletic"],
			gender: "f",
			femininity: 200,
			warmth: 3,
			cost: 1000,
			description: "Too translucent to wear alone.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "leggings.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 26,
			slot: "legs",
			name: "mismatched socks",
			name_cap: "Mismatched socks",
			variable: "mismatched socks",
			combat: {
				reference: "striped socks short",
				accessory: true,
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "neon blue", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 1,
			cost: 2000,
			description: "Brimming with personality.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "mismatched.png",
			accIcon: "mismatched_acc.png",
		}),
		new ClothesItem({
			index: 27,
			slot: "legs",
			name: "loose socks",
			name_cap: "Loose socks",
			variable: "loosesocks",
			combat: {
				renderType: "ankled",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["white", "black", "grey", "lilac", "light pink", "light blue", "custom"],
			colour_sidebar: 1,
			type: ["school"],
			gender: "f",
			femininity: 100,
			warmth: 2,
			cost: 500,
			description: "Popular with schoolgirls in a foreign land.",
			shop: ["clothing", "school", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "loose_socks.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 28,
			slot: "legs",
			name: "sexy nun's stockings",
			name_cap: "Sexy nun's stockings",
			variable: "nunlewd",
			combat: {
				reference: "striped socks long",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["white", "black", "bronze"],
			colour_sidebar: 1,
			type: ["holy", "costume", "fetish"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 2000,
			description: "For looking your Sunday best while on your knees.",
			shop: ["forest", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["white", "black", "bronze"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "sexy_nuns_stockings.png",
			accIcon: "sexy_nuns_stockings_acc.png",
		}),
		new ClothesItem({
			index: 29,
			slot: "legs",
			name: "fishnet garter stockings",
			name_cap: "Fishnet garter stockings",
			variable: "fishnet garter stockings",
			description: "Featuring bold design.",
			cost: 6500,
			shop: ["clothing", "adult"],
			type: ["fetish"],
			state: "knees",
			state_base: "knees",
			combat: {
				reference: "stockings",
			},
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 800,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			gender: "f",
			femininity: 200,
			warmth: 1,
			set: "legs",
			cursed: 0,
			location: 0,
			shopGroup: "harness garter stockings",
			iconFile: "fishnet-garter-stockings.png",
			accIcon: "fishnet-garter-stockings-acc.png",
		}),
		new ClothesItem({
			index: 30,
			slot: "legs",
			name: "men's garter socks",
			name_cap: "Men's garter socks",
			variable: "mensgarters",
			combat: {
				reference: "striped socks long",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["black", "brown", "tan", "white", "navy blue", "grey", "olive", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 1,
			cost: 4000,
			description: "Sexy and functional.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["steel", "blue steel", "bronze", "gold", "rose gold", "silver", "black", "white"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "mens_garters.png",
			accIcon: "mens_garters_acc.png",
		}),
		new ClothesItem({
			index: 31,
			slot: "legs",
			name: "ruffled socks",
			name_cap: "Ruffled socks",
			variable: "ruffled socks",
			combat: {
				reference: "anklesocks",
				accColour: "primary",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "wine", "brown", "tan", "white", "light pink", "light blue", "lilac", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 800,
			description: "Frilly.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "ruffled_socks.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 32,
			slot: "legs",
			name: "ruffled kneehighs",
			name_cap: "Ruffled kneehighs",
			variable: "ruffled kneehighs",
			combat: {
				reference: "striped socks long",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["black", "wine", "brown", "tan", "white", "light pink", "light blue", "lilac", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 1200,
			description: "Frilly.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "ruffled_kneehighs.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 33,
			slot: "legs",
			name: "ruffled thighhighs",
			name_cap: "Ruffled thighhighs",
			variable: "ruffled thighhighs",
			combat: {
				reference: "plainthighhighs",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "wine", "brown", "tan", "white", "light pink", "light blue", "lilac", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 2000,
			description: "Frilly.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "ruffled_thighhighs.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 34,
			slot: "legs",
			name: "tabi",
			name_cap: "Tabi",
			variable: "tabi",
			combat: {
				reference: "anklesocks",
				accColour: "primary",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["white", "black", "grey", "lilac", "light pink", "light blue", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 2,
			cost: 2000,
			description: "Exotic.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "tabi.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 35,
			slot: "legs",
			name: "gold shackles",
			name_cap: "Gold shackles",
			variable: "goldshackles",
			combat: {
				reference: "goldanklets",
				mainColour: "#e8b826",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["holy", "fetish"],
			gender: "n",
			warmth: 0,
			cost: 25000,
			description: "Bound by the weight of the world.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "gold_anklets.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 36,
			slot: "legs",
			name: "mismatched thighhighs",
			name_cap: "Mismatched thighhighs",
			variable: "mismatched thighhighs",
			combat: {
				reference: "plainthighhighs",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 300,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 3000,
			description: "As if you got dressed in the dark.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			accessory_colour_combat: 0,
			cursed: 0,
			location: 0,
			iconFile: "mismatched_thighhighs.png",
			accIcon: "mismatched_thighhighs_acc.png",
		}),
		new ClothesItem({
			index: 37,
			slot: "legs",
			name: "sheer stockings",
			name_cap: "Sheer stockings",
			variable: "sheer stockings",
			combat: {
				reference: "stockings",
			},
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: [
				"black",
				"navy blue",
				"fleshy",
				"light brown",
				"soft brown",
				"brown",
				"wine",
				"grey",
				"light pink",
				"lilac",
				"blue",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"pale white",
				"pale yellow",
				"custom",
			],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 1000,
			description: "Translucent.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "sheer_thighhighs.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 38,
			slot: "legs",
			name: "belted thighhighs",
			name_cap: "Belted thighhighs",
			variable: "belted",
			combat: {
				reference: "plainthighhighs",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 500,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [
				"black",
				"brown",
				"silver",
				"gold",
				"rose gold",
				"blue",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"neon blue",
				"custom",
			],
			colour_sidebar: 1,
			colour_combat: 0,
			pattern: 0,
			pattern_options: ["long", "short"],
			pattern_layer: "primary",
			type: ["cool"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 3500,
			description: "Buckles for days.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "pattern",
			accIcon: "belted_thighhighs_acc.png",
		}),
		new ClothesItem({
			index: 39,
			slot: "legs",
			name: "leather thighhighs",
			name_cap: "Leather thighhighs",
			variable: "leather",
			combat: {
				reference: "plainthighhighs",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 300,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [
				"black",
				"brown",
				"silver",
				"gold",
				"rose gold",
				"blue",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"neon blue",
				"custom",
			],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 2,
			cost: 3000,
			description: "Accentuates your calves.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "belted_thighhighs_long.png",
		}),
		new ClothesItem({
			index: 40,
			slot: "legs",
			name: "chain leggings",
			name_cap: "Chain leggings",
			variable: "chain leggings",
			combat: {
				reference: "plainthighhighs",
			},
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "unstealthy"],
			gender: "n",
			warmth: 1,
			high_img: 1,
			cost: 5000,
			description: "Protects the most vulnerable arteries in your body. No, the jugular is a vein.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "chainmail_leggings.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 41,
			slot: "legs",
			name: "knee plaster",
			name_cap: "Knee plaster",
			variable: "kneeplaster",
			combat: {
				reference: "anklesocks",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 0,
			cost: 500,
			description: "Great for scrapes.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			altposition: "none",
			altdisabled: [],
			iconFile: "kneeplaster.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 42,
			slot: "legs",
			name: "ripped tights",
			name_cap: "Ripped tights",
			variable: "rippedtights",
			combat: {
				reference: "tights",
			},
			state: "waist",
			state_base: "waist",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 1,
			reveal: 600,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 500,
			description: "Great for alternative styles.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "rippedtights.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 43,
			slot: "legs",
			name: "floral socks",
			name_cap: "Floral socks",
			variable: "floralsocks",
			combat: {
				reference: "anklesocks",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 2,
			cost: 500,
			description: "Cute and soft.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "floralsocks.png",
			accIcon: "floralsocks_acc.png",
		}),
		new ClothesItem({
			index: 44,
			slot: "legs",
			name: "lace over-the-knee socks",
			name_cap: "Lace over-the-knee socks",
			variable: "laceovertheknee",
			combat: {
				reference: "plainthighhighs",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 4,
			cost: 500,
			description: "Light and elegant.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "laceovertheknee.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 45,
			slot: "legs",
			name: "lace socks with ribbons",
			name_cap: "Lace socks with ribbons",
			variable: "lacesockswithribbons",
			combat: {
				reference: "anklesocks",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 3,
			cost: 500,
			description: "Light, elegant, and cute.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "lacesockswithribbons.png",
			accIcon: "lacesockswithribbons_acc.png",
		}),
		new ClothesItem({
			index: 46,
			slot: "legs",
			name: "lace socks",
			name_cap: "Lace socks",
			variable: "lacesocks",
			combat: {
				reference: "anklesocks",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 3,
			cost: 500,
			description: "Pretty.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "lacesocks.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 47,
			slot: "legs",
			name: "lace socks with bows",
			name_cap: "Lace socks with bows",
			variable: "lacesockswithbows",
			combat: {
				reference: "anklesocks",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 3,
			cost: 500,
			description: "Frilly.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "lacesockswithbows.png",
			accIcon: "lacesockswithbows_acc.png",
		}),
		new ClothesItem({
			index: 48,
			slot: "legs",
			name: "elegant knee-high socks",
			name_cap: "Elegant knee-high socks",
			variable: "elegantkneehigh",
			combat: {
				reference: "plainthighhighs",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 300,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 4,
			cost: 500,
			description: "Prim and proper.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "elegantkneehigh.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 49,
			slot: "legs",
			name: "elegant socks",
			name_cap: "Elegant socks",
			variable: "elegantsocks",
			combat: {
				reference: "anklesocks",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 3,
			cost: 500,
			description: "Short and sweet.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "elegantkneehigh.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 50,
			slot: "legs",
			name: "striped leg warmers",
			name_cap: "Striped leg warmers",
			variable: "stripedlegwarmers",
			combat: {
				reference: "striped socks long",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 4,
			cost: 500,
			description: "Keeps your legs warm.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "stripedlegwarmers.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 51,
			slot: "legs",
			name: "mischievous socks",
			name_cap: "Mischievous socks",
			variable: "mischievous",
			combat: {
				reference: "anklesocks",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 2,
			cost: 500,
			description: "Get down from the tree.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "mischievous.png",
			accIcon: "mischievous_acc.png",
		}),
		new ClothesItem({
			index: 52,
			slot: "legs",
			name: "fishnet ankle socks",
			name_cap: "Fishnet ankle socks",
			variable: "fishnetankle",
			combat: {
				reference: "anklesocks",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 1,
			reveal: 300,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 0,
			cost: 500,
			description: "Also available in longer lengths.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "fishnetankle.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 53,
			slot: "legs",
			name: "plain over-the-knee socks",
			name_cap: "Plain over-the-knee socks",
			variable: "plainovertheknee",
			combat: {
				reference: "plainthighhighs",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 4,
			cost: 500,
			description: "Simple daily wear.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "plainovertheknee.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 54,
			slot: "legs",
			name: "lace tights",
			name_cap: "Lace tights",
			variable: "lacetights",
			combat: {
				reference: "tights",
			},
			state: "waist",
			state_base: "waist",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 500,
			description: "Laced with character.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "lacetights.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 55,
			slot: "legs",
			name: "asymmetrical garter stockings",
			name_cap: "Asymmetrical garter stockings",
			variable: "asymmetricalgarter",
			combat: {
				reference: "stockings",
			},
			state: "knees",
			state_base: "knees",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 300,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 500,
			description: "Formal on one side.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["steel", "blue steel", "bronze", "gold", "rose gold", "silver", "black", "white"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "asymmetricalgarter.png",
			accIcon: "asymmetricalgarter_acc.png",
		}),
		new ClothesItem({
			index: 56,
			slot: "legs",
			name: "asymmetrical loose socks",
			name_cap: "Asymmetrical loose socks",
			variable: "asymmetricalloose",
			combat: {
				reference: "anklesocks",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 300,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 3,
			cost: 500,
			description: "Couldn't find the other half.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "asymmetricalloose.png",
			accIcon: "asymmetricalloose_acc.png",
		}),
		new ClothesItem({
			index: 57,
			slot: "legs",
			name: "asymmetrical striped garters",
			name_cap: "Asymmetrical striped garters",
			variable: "asymmetricalstriped",
			combat: {
				reference: "stockings",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 400,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 3,
			cost: 500,
			description: "Without belt.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "asymmetricalstriped.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 58,
			slot: "legs",
			name: "fuzzy knee socks",
			name_cap: "Fuzzy knee socks",
			variable: "fuzzykneesocks",
			combat: {
				reference: "plainthighhighs",
			},
			state: "ankles",
			state_base: "ankles",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 4,
			cost: 500,
			description: "Keeps your feet warm.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "white", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "fuzzykneesocks.png",
			accIcon: "fuzzykneesocks_acc.png",
		}),
		new ClothesItem({
			index: 59,
			slot: "legs",
			name: "fishnet kneehighs",
			name_cap: "Fishnet kneehighs",
			variable: "fishnetkneehighs",
			combat: {
				reference: "fishnetstockings",
			},
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_combat: 0,
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 0,
			cost: 1500,
			description: "Attractive and alluring.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "fishnet_stockings.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 60,
			slot: "legs",
			name: "harness garter stockings",
			name_cap: "Harness garter stockings",
			variable: "harness garter stockings",
			description: "Featuring bold design.",
			cost: 6500,
			shop: ["clothing", "adult"],
			type: ["fetish"],
			state: "knees",
			state_base: "knees",
			combat: {
				reference: "stockings",
			},
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 800,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			pattern: 0,
			pattern_options: ["detail"],
			pattern_layer: "tertiary",
			gender: "f",
			femininity: 200,
			warmth: 1,
			set: "legs",
			cursed: 0,
			location: 0,
			shopGroup: "harness garter stockings",
			iconFile: "harness-garter-stockings.png",
			accIcon: "harness-garter-stockings-acc.png",
			detailIcon: "harness-garter-stockings-detail.png",
		}),
		new ClothesItem({
			index: 61,
			slot: "legs",
			name: "striped garter stockings",
			name_cap: "Striped garter stockings",
			variable: "striped garter stockings",
			description: "Featuring bold design.",
			cost: 6500,
			shop: ["clothing", "adult"],
			type: ["fetish"],
			state: "knees",
			state_base: "knees",
			combat: {
				reference: "stockings",
			},
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 800,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			pattern: 0,
			pattern_options: ["detail"],
			pattern_layer: "tertiary",
			gender: "f",
			femininity: 200,
			warmth: 1,
			set: "legs",
			cursed: 0,
			location: 0,
			shopGroup: "harness garter stockings",
			iconFile: "striped-garter-stockings.png",
			accIcon: "striped-garter-stockings-acc.png",
			detailIcon: "harness-garter-stockings-detail.png",
		}),
		new ClothesItem({
			index: 62,
			slot: "legs",
			name: "patterned leggings",
			name_cap: "Patterned leggings",
			variable: "patterned leggings",
			description: "Adds some details.",
			cost: 2500,
			shop: ["clothing"],
			type: ["normal"],
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "n",
			plural: 1,
			colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			accessory: 1,
			accessory_colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			warmth: 4,
			iconFile: "patterned-leggings.png",
			accIcon: "patterned-leggings-acc.png",
		}),
	];
	setup.clothes.legs = clothing;

	/*
		Clothes that modders add go into this array. This should be empty in the base game at all times.
		These items should have a `modder` variable with the modder's name in a short string.
	*/
	setup.moddedClothes.legs = [];

	setup.moddedClothes.legs.forEach((x, i) => (x.index = setup.clothes.legs.length + i));
	setup.clothes.legs.push(...setup.moddedClothes.legs);
}
window.initLegs = initLegs;
