// @ts-check
/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites.

Warmth checklist:
	Base: 0
	Covers hands: +1
	Covers arms: +1

	Materials
	Thin: -1
	Normal: 0
	Thick: +1

	Max warmth: 3
*/
function initHands() {
	/** @type {ClothesItem[]} */
	const clothing = [
		new ClothesItem({
			index: 0,
			slot: "hands",
			name: "naked",
			name_cap: "Naked",
			variable: "naked",
			state: 0,
			state_base: 0,
			warmth: 0,
			integrity: 0,
			integrity_max: 0,
			fabric_strength: 0,
			reveal: 1,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			cost: 0,
			description: "naked",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		}),
		new ClothesItem({
			index: 1,
			slot: "hands",
			name: "fingerless gloves",
			name_cap: "Fingerless gloves",
			variable: "fingerlessgloves",
			state: 0,
			state_base: 0,
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 1000,
			description: "Fingerless gloves to keep your hands warm.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "fingerless_gloves.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 2,
			slot: "hands",
			name: "mittens",
			name_cap: "Mittens",
			variable: "mittens",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 2,
			cost: 400,
			description: "Isn't shaped for individual fingers, but that shouldn't be a problem.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "mittens.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 3,
			slot: "hands",
			name: "arm warmers",
			name_cap: "Arm warmers",
			variable: "armwarmers",
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 2,
			cost: 1000,
			description: "Keep your arms warm.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "arm_warmers.png",
			accIcon: "arm_warmers_acc.png",
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 4,
			slot: "hands",
			name: "lace arm warmers",
			name_cap: "Lace arm warmers",
			variable: "lacewarmers",
			combat: {
				boundable: true,
			},
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 15,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 2500,
			description: "Fashionable.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "lace_arm_warmers.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 5,
			slot: "hands",
			name: "long leather gloves",
			name_cap: "Long leather gloves",
			variable: "longleathergloves",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [
				"black",
				"wine",
				"navy blue",
				"silver",
				"gold",
				"blue",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"brown",
				"custom",
			],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal", "sticky_fingers", "stealthy"],
			gender: "n",
			warmth: 3,
			cost: 8000,
			description: "Fashionable and ready to slip into pockets.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "long_leather_gloves.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 6,
			slot: "hands",
			name: "cheerleader gloves",
			name_cap: "Cheerleader gloves",
			variable: "pompoms",
			combat: {
				reference: "fingerlessgloves",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 1500,
			description: "For cheering your team to victory.",
			shop: ["clothing", "school", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [
				"black",
				"blue",
				"brown",
				"green",
				"pink",
				"purple",
				"red",
				"pale tangerine",
				"teal",
				"pale white",
				"pale yellow",
				"custom",
			],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "fingerless_gloves.png",
			accIcon: "fingerless_gloves_acc.png",
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 7,
			slot: "hands",
			name: "gold bracelets",
			name_cap: "Gold bracelets",
			variable: "gold",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			type: ["costume", "serving"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 25000,
			description: "Eye-catching and exotic.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "gold_bracelets.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 8,
			slot: "hands",
			name: "cow sleeves",
			name_cap: "Cow sleeves",
			variable: "cow",
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			type: ["costume"],
			gender: "n",
			warmth: 1,
			cost: 1000,
			description: "Cute cow print.",
			shop: ["forest", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "brown", "light pink", "light blue", "light green", "custom"],
			accessory_colour_sidebar: "secondary",
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "cow_sleeves.png",
			accIcon: "cow_sleeves_acc.png",
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 9,
			slot: "hands",
			name: "work gloves",
			name_cap: "Work gloves",
			variable: "workgloves",
			combat: {
				reference: "longleathergloves",
				mainColour: "#8c4c00",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal"],
			gender: "n",
			warmth: 2,
			cost: 1500,
			description: "For getting your hands dirty.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "work_gloves.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 10,
			slot: "hands",
			name: "sexy nun's gloves",
			name_cap: "Sexy nun's gloves",
			variable: "nunlewd",
			combat: {
				reference: "armwarmers",
				mainColour: "#2f2534",
				accColour: "#2f2534",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["holy", "costume", "fetish"],
			gender: "f",
			warmth: 1,
			cost: 3000,
			description: "Great for rubbing out sin.",
			shop: ["forest", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "sexy_nuns_gloves.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 11,
			slot: "hands",
			name: "wrist cuffs",
			name_cap: "Wrist cuffs",
			variable: "wristcuffs",
			combat: {
				reference: "gold",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			type: ["costume", "serving"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 800,
			description: "Sexy enough for a playboy bunny, classy enough for a butler.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "wrist_cuffs.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 12,
			slot: "hands",
			name: "gold shackles",
			name_cap: "Gold shackles",
			variable: "goldshackles",
			combat: {
				reference: "gold",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			type: ["holy", "fetish"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 25000,
			description: "Bound by obsession. Bound by vanity.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 1,
			location: 0,
			iconFile: "gold_bracelets.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 13,
			slot: "hands",
			name: "belted gloves",
			name_cap: "Belted gloves",
			variable: "belted",
			combat: {
				reference: "longleathergloves",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [
				"black",
				"brown",
				"silver",
				"gold",
				"rose gold",
				"blue",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"neon blue",
				"custom",
			],
			colour_sidebar: 1,
			colour_combat: 0,
			pattern: 0,
			pattern_options: ["gloves", "belts"],
			pattern_layer: "primary",
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 8000,
			description: "Buckles for days.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "pattern",
			accIcon: "belted_gloves_acc.png",
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
		new ClothesItem({
			index: 14,
			slot: "hands",
			name: "succubus gloves",
			name_cap: "Succubus gloves",
			variable: "succubus",
			combat: {
				reference: "armwarmers",
				mainColour: "#2f2534",
				accColour: "#2f2534",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["costume", "fetish", "dark"],
			gender: "f",
			warmth: 1,
			cost: 12000,
			description: "Ready to extract every last drop.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "succubus_gloves.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		}),
	];
	setup.clothes.hands = clothing;

	/*
		Clothes that modders add go into this array. This should be empty in the base game at all times.
		These items should have a `modder` variable with the modder's name in a short string.
	*/
	setup.moddedClothes.hands = [];

	setup.moddedClothes.hands.forEach((x, i) => (x.index = setup.clothes.hands.length + i));
	setup.clothes.hands.push(...setup.moddedClothes.hands);
}
window.initHands = initHands;
