// @ts-check
/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites.

Warmth checklist:
	Base: 0
	Covers ½ feet: 1 || Covers whole feet: 2
	Covers ankles: +1

	Materials:
	Thin: 0
	Normal: +1
	Thick: +2

	Max warmth: 5
*/
function initFeet() {
	/** @type {ClothesItem[]} */
	const clothing = [
		new ClothesItem({
			index: 0,
			slot: "feet",
			name: "naked",
			name_cap: "Naked",
			variable: "naked",
			state: 0,
			state_base: 0,
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "벗었습니다.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		}),
		new ClothesItem({
			index: 1,
			slot: "feet",
			name: "school shoes",
			name_cap: "School shoes",
			variable: "schoolshoes",
			combat: {
				reference: "lightuptrainers",
				accColour: "#0c0c0c",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["school"],
			gender: "n",
			warmth: 2,
			cost: 2500,
			description: "세련되고 학교에 입기에도 적합하지만, 꼭 입어야 하는 것은 아닙니다.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "school_shoes.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 2,
			slot: "feet",
			name: "tuxedo shoes",
			name_cap: "Tuxedo shoes",
			variable: "tuxedoshoes",
			combat: {
				reference: "lightuptrainers",
				accColour: "#1d191e",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["formal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 10000,
			description: "단정하고 세련되었습니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "tuxedo_shoes.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 3,
			slot: "feet",
			name: "ankle cuffs",
			name_cap: "Ankle cuffs",
			variable: "anklecuffs",
			combat: {
				accessory: true,
				hasJoinedLimbsAcc: true,
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["fetish", "shackle"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "잠금을 해제하려면 특수 도구가 필요합니다.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			notuck: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		}),
		new ClothesItem({
			index: 4,
			slot: "feet",
			name: "sandals",
			name_cap: "Sandals",
			variable: "sandals",
			combat: {
				reference: "wedgesandals",
				accColour: "#cdb493",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 2000,
			description: "여름에 시원합니다.",
			shop: ["clothing", "baitShop"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_combat: "brown",
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "sandals.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 5,
			slot: "feet",
			name: "dress sandals",
			name_cap: "Dress sandals",
			variable: "dresssandals",
			combat: {
				reference: "wedgesandals",
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 10000,
			description: "패셔너블하고 세련되었습니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "dress_sandals.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 6,
			slot: "feet",
			name: "trainers",
			name_cap: "Trainers",
			variable: "trainers",
			combat: {
				reference: "lightuptrainers",
				hasMainImg: false,
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 250,
			integrity_max: 250,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "athletic"],
			gender: "n",
			warmth: 2,
			cost: 3000,
			description: "캐주얼하고 실용적입니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "trainers.png",
			accIcon: "trainers_acc.png",
		}),
		new ClothesItem({
			index: 7,
			slot: "feet",
			name: "witch shoes",
			name_cap: "Witch shoes",
			variable: "witch",
			combat: {
				reference: "courtheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 4000,
			description: "귀엽고 으스스합니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "witch_shoes.png",
			accIcon: "witch_shoes_acc.png",
		}),
		new ClothesItem({
			index: 8,
			slot: "feet",
			name: "wellies",
			name_cap: "Wellies",
			variable: "wellies",
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "rugged"],
			gender: "n",
			warmth: 3,
			cost: 5000,
			description: "방수 처리되었습니다.",
			shop: ["clothing", "baitShop"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "wellies.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 9,
			slot: "feet",
			name: "platform heels",
			name_cap: "Platform heels",
			variable: "platformheels",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 800,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "custom"],
			colour_sidebar: 1,
			type: ["formal", "serving", "bimbo", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 5000,
			description: "꽤 여성스러운 기분이 들게 합니다.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "platform_heels.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 10,
			slot: "feet",
			name: "kitten heels",
			name_cap: "Kitten heels",
			variable: "kittenheels",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 50,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 10000,
			description: "굽이 3센티미터밖에 되지 않아 키튼 힐이라고 불립니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "kitten_heels.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 11,
			slot: "feet",
			name: "wedge sandals",
			name_cap: "Wedge sandals",
			variable: "wedgesandals",
			combat: {
				accColour: "#a18262",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 400,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 3500,
			description: "해변에 아주 좋습니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_combat: 0,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "wedge_sandals.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 12,
			slot: "feet",
			name: "court heels",
			name_cap: "Court heels",
			variable: "courtheels",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal", "serving", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 12500,
			description: "꽤 높고 아주 어른스럽습니다.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "court_heels.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 13,
			slot: "feet",
			name: "heeled boots",
			name_cap: "Heeled boots",
			variable: "bootheels",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 600,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["fetish", "serving", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 3,
			cost: 16000,
			description: "강렬한 선택입니다.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "heeled_boots.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 14,
			slot: "feet",
			name: "stripper heels",
			name_cap: "Stripper heels",
			variable: "stripperheels",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 800,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["dance", "fetish", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 25000,
			description: "미친 듯이 높고 아주 음탕합니다.",
			shop: ["adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "stripper_heels.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 15,
			slot: "feet",
			name: "horsebit loafers",
			name_cap: "Horsebit loafers",
			variable: "horsebitloafers",
			combat: {
				reference: "lightuptrainers",
				accColour: "#171717",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 20000,
			description: "검은색 홀스빗 로퍼 한 켤레.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "horsebit_loafers.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 16,
			slot: "feet",
			name: "cordovan loafers",
			name_cap: "Cordovan loafers",
			variable: "cordovanloafers",
			combat: {
				reference: "lightuptrainers",
				accColour: "#40181f",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 40000,
			description: "셸 코도반 로퍼 한 켤레. 비싸지만 품질이 매우 좋습니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "cordovan_loafers.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 17,
			slot: "feet",
			name: "animal slippers",
			name_cap: "Animal slippers",
			variable: "bunny",
			combat: {
				reference: "lightuptrainers",
				accColour: "#ffffff",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "white",
			type: ["sleep"],
			gender: "n",
			femininity: 0,
			warmth: 2,
			cost: 2000,
			description: "발가락을 따뜻하게 유지해 줍니다.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			pattern: 0,
			pattern_options: ["bunny", "ducky", "foxy", "kitty", "moomoo", "puppy", "teddy bear"],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "pattern",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 18,
			slot: "feet",
			name: "combat boots",
			name_cap: "Combat boots",
			variable: "combat",
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 500,
			integrity_max: 500,
			fabric_strength: 50,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "soft brown", "light brown", "khaki", "sand", "tan", "white", "custom"],
			colour_sidebar: 1,
			type: ["normal", "rugged"],
			gender: "m",
			femininity: -100,
			warmth: 4,
			cost: 20000,
			description: "튼튼하고 고품질의 소재로 만들어졌습니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "combat_boots.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 19,
			slot: "feet",
			name: "field boots",
			name_cap: "Field boots",
			variable: "field",
			combat: {
				reference: "bootheels",
				mainColour: "#333333",
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 40,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal", "riding"],
			gender: "n",
			femininity: 0,
			warmth: 4,
			cost: 14500,
			description: "유연합니다. 전문적인 승마용입니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "field_boots.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 20,
			slot: "feet",
			name: "paddock boots",
			name_cap: "Paddock boots",
			variable: "paddock",
			combat: {
				reference: "bootheels",
				mainColour: "#333333",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 40,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal", "riding"],
			gender: "n",
			femininity: 0,
			warmth: 3,
			cost: 8000,
			description: "가벼운 승마용입니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "paddock_boots.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 21,
			slot: "feet",
			name: "work boots",
			name_cap: "Work boots",
			variable: "work",
			combat: {
				reference: "bootheels",
				mainColour: "#b27531",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 40,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "brown",
			type: ["normal", "rugged"],
			gender: "n",
			femininity: 0,
			warmth: 4,
			cost: 6000,
			description: "발가락을 보호합니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "work_boots.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 22,
			slot: "feet",
			name: "flippers",
			name_cap: "Flippers",
			variable: "flippers",
			combat: {
				reference: "lightuptrainers",
				hasMainImg: false,
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 60,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["swim", "diving", "unstealthy"],
			gender: "n",
			femininity: 0,
			warmth: 2,
			cost: 2000,
			description: "더 빨리 잠수할 수 있게 해줍니다.",
			shop: ["clothing", "baitShop"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "flippers.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 23,
			slot: "feet",
			name: "ice skates",
			name_cap: "Ice skates",
			variable: "iceskates",
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 4,
			cost: 10000,
			description: "튼튼하면서도 우아합니다. 마치 그것을 신고 공연하는 사람들처럼요.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "ice_skates.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 24,
			slot: "feet",
			name: "long boots",
			name_cap: "Long boots",
			variable: "long",
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 60,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 5,
			cost: 4500,
			description: "무릎을 덮습니다.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "long_boots.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 25,
			slot: "feet",
			name: "light-up trainers",
			name_cap: "Light-up trainers",
			variable: "lightuptrainers",
			combat: {
				accColour: "#121212",
			},
			state: 0,
			state_base: 0,
			integrity: 250,
			integrity_max: 250,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "athletic", "unstealthy"],
			gender: "n",
			warmth: 2,
			cost: 4500,
			description: "시야 확보에 좋습니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "light-up_trainers.png",
			accIcon: "light-up_trainers_acc.png",
		}),
		new ClothesItem({
			index: 26,
			slot: "feet",
			name: "ball and chain",
			name_cap: "Ball and chain",
			variable: "ballchain",
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["fetish", "shackle"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "잠금을 해제하려면 특수 도구가 필요합니다.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			notuck: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		}),
		new ClothesItem({
			index: 27,
			slot: "feet",
			name: "cowboy boots",
			name_cap: "Cowboy boots",
			variable: "cowboy",
			combat: {
				reference: "bootheels",
				mainColour: "#9a643b",
			},
			state: 0,
			state_base: 0,
			integrity: 350,
			integrity_max: 350,
			fabric_strength: 40,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "brown",
			type: ["normal", "riding"],
			gender: "m",
			femininity: -200,
			warmth: 3,
			cost: 8500,
			description: "박차가 포함되어 있습니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "cowboy_boots.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 28,
			slot: "feet",
			name: "high top trainers",
			name_cap: "High top trainers",
			variable: "hightops",
			combat: {
				reference: "lightuptrainers",
				accColour: "primary",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "athletic"],
			gender: "n",
			warmth: 2,
			cost: 6000,
			description: "패셔너블하고 실용적입니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "trainers.png",
			accIcon: "trainers_acc.png",
		}),
		new ClothesItem({
			index: 29,
			slot: "feet",
			name: "belly dancer's shoes",
			name_cap: "Belly dancer's shoes",
			variable: "belly",
			combat: {
				reference: "courtheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 4000,
			description: "걸을 때마다 딸랑거리는 소리가 납니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "belly_dancers_shoes.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 30,
			slot: "feet",
			name: "canvas loafers",
			name_cap: "Canvas loafers",
			variable: "canvas loafers",
			combat: {
				reference: "wedgesandals",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 3500,
			description: "캐주얼하고 실용적입니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "canvas_loafers.png",
			accIcon: "canvas_loafers_acc.png",
		}),
		new ClothesItem({
			index: 31,
			slot: "feet",
			name: "thigh-high heeled boots",
			name_cap: "Thigh-high heeled boots",
			variable: "thighhigh_heels",
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "tan", "grey", "brown", "blue", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["heels"],
			gender: "f",
			femininity: 200,
			warmth: 5,
			cost: 10000,
			description: "무릎을 덮습니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "thighhigh_heels.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 32,
			slot: "feet",
			name: "fur boots",
			name_cap: "Fur boots",
			variable: "fur_boots",
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 250,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "tan", "grey", "brown", "blue", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["heels"],
			gender: "f",
			femininity: 200,
			warmth: 4,
			cost: 7500,
			description: "클럽에서 주목받기 좋습니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["white", "brown", "black", "tan", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "fur_boots.png",
			accIcon: "fur_boots_acc.png",
		}),
		new ClothesItem({
			index: 33,
			slot: "feet",
			name: "mary janes",
			name_cap: "Mary janes",
			variable: "maryjanes",
			combat: {
				reference: "kittenheels",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "brown", "tan", "white", "light pink", "light blue", "lilac", "custom"],
			colour_sidebar: 1,
			type: ["school"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 2500,
			description: "단정하고 학교에 적합하지만, 필수는 아닙니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["steel", "blue steel", "bronze", "gold", "rose gold", "silver", "black", "white"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "mary_janes.png",
			accIcon: "mary_janes_acc.png",
		}),
		new ClothesItem({
			index: 34,
			slot: "feet",
			name: "platform mary janes",
			name_cap: "Platform mary janes",
			variable: "platformmaryjanes",
			combat: {
				reference: "wedgesandals",
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "brown", "tan", "white", "light pink", "light blue", "lilac", "custom"],
			colour_sidebar: 1,
			type: ["school"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 4500,
			description: "학교에 적합하지만, 필수는 아닙니다.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["steel", "blue steel", "bronze", "gold", "rose gold", "silver", "black", "white"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "platform_mary_janes.png",
			accIcon: "platform_mary_janes_acc.png",
		}),
		new ClothesItem({
			index: 35,
			slot: "feet",
			name: "geta",
			name_cap: "Geta",
			variable: "geta",
			combat: {
				reference: "wedgesandals",
				accColour: "#e49a7d",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "tan", "grey", "brown", "blue", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 4500,
			description: "이국적입니다.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "geta.png",
			accIcon: "geta_acc.png",
		}),
		new ClothesItem({
			index: 36,
			slot: "feet",
			name: "zori",
			name_cap: "Zori",
			variable: "zori",
			combat: {
				reference: "wedgesandals",
				accColour: "#e49a7d",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "tan", "grey", "brown", "blue", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 3500,
			description: "이국적입니다.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "zori.png",
			accIcon: "zori_acc.png",
		}),
		new ClothesItem({
			index: 37,
			slot: "feet",
			name: "ribbon platform heels",
			name_cap: "Ribbon platform heels",
			variable: "ribbonplatformheels",
			combat: {
				reference: "wedgesandals",
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 600,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "custom"],
			colour_sidebar: 1,
			type: ["formal", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 5000,
			description: "종아리를 돋보이게 합니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "ribbon_platform_heels.png",
			accIcon: "ribbon_platform_heels_acc.png",
		}),
		new ClothesItem({
			index: 38,
			slot: "feet",
			name: "penny loafers",
			name_cap: "Penny loafers",
			variable: "loafers",
			combat: {
				reference: "lightuptrainers",
				accColour: "primary",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["brown", "black", "russet", "wine", "soft brown", "light brown", "navy", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["formal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 5000,
			description: "클래식한 가죽 로퍼.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "loafers.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 39,
			slot: "feet",
			name: "wingtips",
			name_cap: "Wingtips",
			variable: "wingtips",
			combat: {
				reference: "lightuptrainers",
				accColour: "primary",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 300,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["brown", "black", "russet", "wine", "soft brown", "light brown", "navy", "white", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["formal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 12000,
			description: "구식입니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["brown", "black", "russet", "wine", "soft brown", "light brown", "navy", "white", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "wingtips.png",
			accIcon: "wingtips_acc.png",
		}),
		new ClothesItem({
			index: 40,
			slot: "feet",
			name: "laced-up heeled boots",
			name_cap: "Laced-up heeled boots",
			variable: "lacedupheels",
			combat: {
				reference: "bootheels",
				accessory: false,
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 600,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["heels"],
			gender: "f",
			femininity: 200,
			warmth: 3,
			cost: 16000,
			description: "강력한 선택.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "laced-up_heeled_boots.png",
			accIcon: "laced-up_heeled_boots_acc.png",
		}),
		new ClothesItem({
			index: 41,
			slot: "feet",
			name: "belted boots",
			name_cap: "Belted boots",
			variable: "belted",
			combat: {
				reference: "bootheels",
				accessory: false,
			},
			state: 0,
			state_base: 0,
			integrity: 500,
			integrity_max: 500,
			fabric_strength: 50,
			reveal: 500,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [
				"black",
				"brown",
				"silver",
				"gold",
				"rose gold",
				"blue",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"neon blue",
				"custom",
			],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["normal", "rugged"],
			gender: "m",
			femininity: -100,
			warmth: 4,
			cost: 20000,
			description: "고급 가죽으로 제작되었습니다.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "belted_boots.png",
			accIcon: "belted_boots_acc.png",
		}),
		new ClothesItem({
			index: 42,
			slot: "feet",
			name: "basketball sneakers",
			name_cap: "Basketball sneakers",
			variable: "basketball",
			combat: {
				reference: "lightuptrainers",
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 250,
			integrity_max: 250,
			fabric_strength: 20,
			reveal: 300,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "neon blue", "custom"],
			colour_sidebar: 1,
			pattern: 0,
			pattern_options: ["soles"],
			type: ["athletic", "cool"],
			pattern_layer: "tertiary",
			gender: "m",
			femininity: -200,
			warmth: 2,
			cost: 30000,
			description: "비싼 신분의 상징입니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [
				"black",
				"blue",
				"brown",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"neon blue",
				"custom",
			],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "basketball_sneakers.png",
			accIcon: "basketball_sneakers_acc.png",
			detailIcon: "basketball_sneakers_detail.png",
		}),
		new ClothesItem({
			index: 43,
			slot: "feet",
			name: "chain boots",
			name_cap: "Chain boots",
			variable: "chain boots",
			combat: {
				reference: "bootheels",
				mainColour: "#333333",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			type: ["costume", "unstealthy", "rugged"],
			gender: "n",
			warmth: 1,
			cost: 5000,
			description: "보기보다 편안하지만, 매우 시끄럽습니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "chainmail_boots.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 44,
			slot: "feet",
			name: "ropes",
			name_cap: "Ropes",
			variable: "ropes",
			combat: {
				reference: "anklecuffs",
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["fetish"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "임시 결박입니다.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		}),
		new ClothesItem({
			index: 45,
			slot: "feet",
			name: "reindeer slippers",
			name_cap: "Reindeer slippers",
			variable: "reindeerslippers",
			combat: {
				reference: "lightuptrainers",
				accColour: "#ffffff",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "brown",
			type: ["costume", "sleep"],
			gender: "n",
			warmth: 2,
			cost: 1500,
			description: "아침의 졸음 안개 속에서 길을 안내해 줄 것입니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "animal_slippers_reindeer.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 46,
			slot: "feet",
			name: "gift wrap footwrap",
			name_cap: "Gift wrap footwrap",
			variable: "giftwrap",
			combat: {
				reference: "naked",
			},
			state: 0,
			state_base: 0,
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 10,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "fetish"],
			gender: "n",
			warmth: 0,
			cost: 1000,
			description: "이것을 발에 감는 것은 악마 같은 짓입니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "giftwrap_feet.png",
		}),
		new ClothesItem({
			index: 47,
			slot: "feet",
			name: "ballet shoes",
			name_cap: "Ballet shoes",
			variable: "balletshoes",
			combat: {
				reference: "stripperheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 800,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["dance"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 8000,
			description: "춤추기에 가장 좋습니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "ballet_shoes.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 48,
			slot: "feet",
			name: "succubus heels",
			name_cap: "Succubus heels",
			variable: "succubus",
			combat: {
				reference: "stripperheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 600,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "dance", "fetish", "heels", "dark"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 12000,
			description: "위험할 정도로 위압적입니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "succubus_heels.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 49,
			slot: "feet",
			name: "christmas boots",
			name_cap: "Christmas boots",
			variable: "christmasboots",
			combat: {
				reference: "bootheels",
				mainColour: "#333333",
			},
			state: 0,
			state_base: 0,
			integrity: 500,
			integrity_max: 500,
			fabric_strength: 50,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal", "rugged"],
			gender: "n",
			warmth: 4,
			cost: 8000,
			description: "굴뚝을 타고 내려갈 때 좋습니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "christmas_boots.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 50,
			slot: "feet",
			name: "vines",
			name_cap: "Vines",
			variable: "vines",
			combat: {
				reference: "anklecuffs",
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["shackle"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "자연이 반격할 때.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			notuck: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		}),
		new ClothesItem({
			index: 51,
			slot: "feet",
			name: "ankle strap sandals",
			name_cap: "Ankle strap sandals",
			variable: "anklestrapsandals",
			combat: {
				reference: "wedgesandals",
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 600,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 1000,
			description: "산들바람.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "custom"],
			accessory_colour_sidebar: 1,
			notuck: 1,
			location: 0,
			iconFile: "anklestrapsandals.png",
			accIcon: "anklestrapsandals-acc.png",
		}),
		new ClothesItem({
			index: 52,
			slot: "feet",
			name: "ankle strap sneakers",
			name_cap: "Ankle strap sneakers",
			variable: "anklestrapsneakers",
			combat: {
				reference: "lightuptrainers",
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 250,
			integrity_max: 250,
			fabric_strength: 20,
			reveal: 300,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "neon blue", "custom"],
			colour_sidebar: 1,
			pattern: 0,
			pattern_options: ["detail"],
			type: ["athletic", "cool"],
			pattern_layer: "tertiary",
			gender: "n",
			warmth: 2,
			cost: 7500,
			description: "편해 보입니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			notuck: 0,
			location: 0,
			iconFile: "anklestrapsneakers.png",
			accIcon: "anklestrapsneakers-acc.png",
			detailIcon: "anklestrapsneakers-detail.png",
		}),
		new ClothesItem({
			index: 53,
			slot: "feet",
			name: "ankle trainers",
			name_cap: "Ankle trainers",
			variable: "ankletrainers",
			combat: {
				reference: "lightuptrainers",
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 300,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 2,
			cost: 1000,
			description: "산뜻합니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "custom"],
			accessory_colour_sidebar: 1,
			notuck: 0,
			location: 0,
			iconFile: "ankletrainers.png",
			accIcon: "ankletrainers-acc.png",
		}),
		new ClothesItem({
			index: 54,
			slot: "feet",
			name: "ballet pumps",
			name_cap: "Ballet pumps",
			variable: "balletpumps",
			combat: {
			reference: "stripperheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 250,
			word: "",
			plural: 1,
			colour: 0,
			colour_sidebar: 1,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_combat: 0,
			type: ["dance"],
			gender: "n",
			warmth: 1,
			cost: 8000,
			description: "춤을 추고싶은 기분이 듭니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			notuck: 1,
			location: 0,
			iconFile: "balletpumps.png",
			accIcon: "balletpumps-acc.png",
		}),
		new ClothesItem({
			index: 55,
			slot: "feet",
			name: "butterfly heels",
			name_cap: "Butterfly heels",
			variable: "butterflyheels",
			combat: {
			reference: "stripperheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 250,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["formal", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 8000,
			description: "걸음마다 날지 못하는 기분이 듭니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			notuck: 1,
			location: 0,
			iconFile: "butterflyheels.png",
			accIcon: "butterflyheels-acc.png",
		}),
		new ClothesItem({
			index: 56,
			slot: "feet",
			name: "clogs",
			name_cap: "Clogs",
			variable: "clogs",
			combat: {
				reference: "wedgesandals",
				accColour: "#cdb493",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 50,
			word: "",
			plural: 1,
			type: ["normal"],
			gender: "n",
			warmth: 2,
			cost: 4500,
			description: "매력이 가득합니다.",
			shop: ["clothing"],
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			pattern: 0,
			pattern_options: ["plain", "dot", "strawberries"],
			pattern_caption: true,
			pattern_layer: "tertiary",
			notuck: 1,
			location: 0,
			iconFile: "clogs.png",
			accIcon: "clogs-acc.png",
		}),
		new ClothesItem({
			index: 57,
			slot: "feet",
			name: "double strap sandals",
			name_cap: "Double strap sandals",
			variable: "doublestrapsandals",
			combat: {
			reference: "wedgesandals",
			accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 50,
			word: "",
			plural: 1,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 2000,
			description: "두 배로 안전합니다.",
			shop: ["clothing"],
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			notuck: 1,
			location: 0,
			iconFile: "doublestrapsandals.png",
			accIcon: "doublestrapsandals-acc.png",
		}),
		new ClothesItem({
			index: 58,
			slot: "feet",
			name: "flat sandals",
			name_cap: "Flat sandals",
			variable: "flatsandals",
			combat: {
			reference: "wedgesandals",
			accColour: "#cdb493",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 1,
			word: "",
			plural: 1,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 500,
			description: "해변에 어울립니다.",
			shop: ["clothing"],
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			notuck: 1,
			location: 0,
			iconFile: "flatsandals.png",
			accIcon: "flatsandals-acc.png",
		}),
		new ClothesItem({
			index: 59,
			slot: "feet",
			name: "floral rain boots",
			name_cap: "Floral rain boots",
			variable: "floralrainboots",
			combat: {
			reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 150,
			word: "",
			plural: 1,
			type: ["normal", "waterproof"],
			gender: "n",
			warmth: 3,
			cost: 4500,
			description: "비 오는 날을 밝게 해줍니다.",
			shop: ["clothing"],
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			notuck: 0,
			location: 0,
			iconFile: "floralrainboots.png",
			accIcon: "floralrainboots-acc.png",
		}),
		new ClothesItem({
			index: 60,
			slot: "feet",
			name: "floral ribbon trainers",
			name_cap: "Floral ribbon trainers",
			variable: "floralribbontrainers",
			combat: {
			reference: "lightuptrainers",
			accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 250,
			word: "",
			plural: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 4500,
			description: "끈으로 묶여 있습니다.",
			shop: ["clothing"],
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			pattern: 0,
			pattern_options: ["detail"],
			pattern_caption: true,
			pattern_layer: "tertiary",
			notuck: 0,
			location: 0,
			iconFile: "floralribbontrainers.png",
			accIcon: "floralribbontrainers-acc.png",
			detailIcon: "floralribbontrainers-detail.png",
		}),
		new ClothesItem({
			index: 61,
			slot: "feet",
			name: "fuzzy-bow boots",
			name_cap: "Fuzzy-bow boots",
			variable: "fuzzybowboots",
			combat: {
			reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1,
			reveal: 250,
			word: "",
			plural: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 3,
			cost: 4500,
			description: "귀여움이 넘칩니다.",
			shop: ["clothing"],
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			notuck: 0,
			location: 0,
			iconFile: "fuzzybowboots.png",
			accIcon: "fuzzybowboots-acc.png",
		}),
		new ClothesItem({
			index: 62,
			slot: "feet",
			name: "heeled trainers",
			name_cap: "Heeled trainers",
			variable: "heeledtrainers",
			description: "달리는 데 도움은 되지 않습니다.",
			cost: 5500,
			shop: ["clothing"],
			type: ["normal", "heels"],
			combat: {
				reference: "stripperheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "f",
			femininity: 100,
			warmth: 1,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "heeledtrainers.png",
			accIcon: "heeledtrainers-acc.png",
		}),
		new ClothesItem({
			index: 63,
			slot: "feet",
			name: "high heel ankle boots",
			name_cap: "High heel ankle boots",
			variable: "highheelankleboots",
			description: "클래식합니다.",
			cost: 9500,
			shop: ["clothing"],
			type: ["normal", "heels", "formal"],
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 300,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "f",
			femininity: 100,
			warmth: 3,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "highheelankleboots.png",
			accIcon: "highheelankleboots-acc.png",
		}),
		new ClothesItem({
			index: 64,
			slot: "feet",
			name: "knee fur boots",
			name_cap: "Knee fur boots",
			variable: "kneefurboots",
			description: "뒷면에 지퍼가 있습니다.",
			cost: 9500,
			shop: ["clothing"],
			type: ["normal", "heels"],
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 300,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "n",
			warmth: 4,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "kneefurboots.png",
			accIcon: "kneefurboots-acc.png",
		}),
		new ClothesItem({
			index: 65,
			slot: "feet",
			name: "knit cuff ankle boots",
			name_cap: "Knit cuff ankle boots",
			variable: "knitcuffankleboots",
			description: "가을에 완벽합니다.",
			cost: 6000,
			shop: ["clothing"],
			type: ["normal"],
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 50,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "n",
			warmth: 4,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "knitcuffankleboots.png",
			accIcon: "knitcuffankleboots-acc.png",
		}),
		new ClothesItem({
			index: 66,
			slot: "feet",
			name: "lace up heels",
			name_cap: "Lace up heels",
			variable: "laceupheels",
			description: "아름다움에는 시간이 걸립니다.",
			cost: 10500,
			shop: ["clothing"],
			type: ["normal", "heels"],
			combat: {
				reference: "stripperheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 300,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "f",
			femininity: 200,
			warmth: 1,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "laceupheels.png",
			accIcon: "laceupheels-acc.png",
		}),
		new ClothesItem({
			index: 67,
			slot: "feet",
			name: "lace up mary janes",
			name_cap: "Lace up mary janes",
			variable: "laceupmaryjanes",
			description: "우아함으로 묶여 있습니다.",
			cost: 18000,
			shop: ["clothing"],
			type: ["normal", "heels", "formal"],
			combat: {
				reference: "stripperheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 400,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "f",
			femininity: 200,
			warmth: 1,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "laceupmaryjanes.png",
			accIcon: "laceupmaryjanes-acc.png",
		}),
		new ClothesItem({
			index: 68,
			slot: "feet",
			name: "long puff boots",
			name_cap: "Long puff boots",
			variable: "longpuffboots",
			description: "겨울 날씨에 아주 좋습니다.",
			cost: 7000,
			shop: ["clothing"],
			type: ["normal"],
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "n",
			warmth: 6,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "longpuffboots.png",
			accIcon: "longpuffboots-acc.png",
		}),
		new ClothesItem({
			index: 69,
			slot: "feet",
			name: "mary jane heels",
			name_cap: "Mary jane heels",
			variable: "maryjaneheels",
			description: "빈티지한 매력.",
			cost: 10500,
			shop: ["clothing"],
			type: ["normal", "formal", "heels"],
			combat: {
				reference: "kittenheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			gender: "f",
			femininity: 100,
			warmth: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "maryjaneheels.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 70,
			slot: "feet",
			name: "over-the-knee boots",
			name_cap: "Over-the-knee boots",
			variable: "overthekneeboots",
			description: "다리를 감싸줍니다.",
			cost: 14000,
			shop: ["clothing"],
			type: ["normal", "heels"],
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 300,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "f",
			femininity: 100,
			warmth: 4,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "overthekneeboots.png",
			accIcon: "overthekneeboots-acc.png",
		}),
		new ClothesItem({
			index: 71,
			slot: "feet",
			name: "platform ankle boots",
			name_cap: "Platform ankle boots",
			variable: "platformankleboots",
			description: "귀엽습니다.",
			cost: 5500,
			shop: ["clothing"],
			type: ["normal"],
			combat: {
				reference: "lightuptrainers",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "n",
			warmth: 2,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "platformankleboots.png",
			accIcon: "platformankleboots-acc.png",
		}),
		new ClothesItem({
			index: 72,
			slot: "feet",
			name: "platform clogs with fur",
			name_cap: "Platform clogs with fur",
			variable: "platformclogswithfur",
			description: "아늑합니다.",
			cost: 15500,
			shop: ["clothing"],
			type: ["normal"],
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 300,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			pattern: 0,
			pattern_options: ["detail"],
			pattern_layer: "tertiary",
			gender: "n",
			warmth: 4,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "platformclogswithfur.png",
			accIcon: "platformclogswithfur-acc.png",
			detailIcon: "platformclogswithfur-detail.png",
		}),
		new ClothesItem({
			index: 73,
			slot: "feet",
			name: "platform loafers",
			name_cap: "Platform loafers",
			variable: "platformloafers",
			description: "키를 높여주는 슬립온.",
			cost: 8000,
			shop: ["clothing"],
			type: ["normal"],
			combat: {
				reference: "wedgesandals",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			pattern: 0,
			pattern_options: ["detail"],
			pattern_layer: "tertiary",
			gender: "n",
			warmth: 3,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "platformloafers.png",
			accIcon: "platformloafers-acc.png",
			detailIcon: "platformloafers-detail.png",
		}),
		new ClothesItem({
			index: 74,
			slot: "feet",
			name: "polka dot rain boots",
			name_cap: "Polka dot rain boots",
			variable: "polkadotrainboots",
			description: "웅덩이에 들어갈 준비가 되었습니다.",
			cost: 5500,
			shop: ["clothing"],
			type: ["normal", "waterproof"],
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 50,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "n",
			warmth: 3,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "polkadotrainboots.png",
			accIcon: "polkadotrainboots-acc.png",
		}),
		new ClothesItem({
			index: 75,
			slot: "feet",
			name: "puff boots",
			name_cap: "Puff boots",
			variable: "puffboots",
			description: "구름 같은 편안함.",
			cost: 8500,
			shop: ["clothing"],
			type: ["normal"],
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "n",
			warmth: 4,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "puffboots.png",
			accIcon: "puffboots-acc.png",
		}),
		new ClothesItem({
			index: 76,
			slot: "feet",
			name: "rose platform heels",
			name_cap: "Rose platform heels",
			variable: "roseplatformheels",
			description: "장미 향기를 맡아보세요.",
			cost: 21000,
			shop: ["clothing"],
			type: ["normal", "formal", "heels"],
			combat: {
				reference: "stripperheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 400,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "f",
			femininity: 200,
			warmth: 1,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "roseplatformheels.png",
			accIcon: "roseplatformheels-acc.png",
		}),
		new ClothesItem({
			index: 77,
			slot: "feet",
			name: "rose pumps",
			name_cap: "Rose pumps",
			variable: "rosepumps",
			description: "아주 두껍습니다.",
			cost: 16000,
			shop: ["clothing"],
			type: ["normal"],
			combat: {
				reference: "courtheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 350,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "f",
			femininity: 100,
			warmth: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "rosepumps.png",
			accIcon: "rosepumps-acc.png",
		}),
		new ClothesItem({
			index: 78,
			slot: "feet",
			name: "satin ribbon heels",
			name_cap: "Satin ribbon heels",
			variable: "satinribbonheels",
			description: "발목을 감쌉니다.",
			cost: 19500,
			shop: ["clothing"],
			type: ["normal", "formal", "heels"],
			combat: {
				reference: "stripperheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 400,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "f",
			femininity: 200,
			warmth: 1,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "satinribbonheels.png",
			accIcon: "satinribbonheels-acc.png",
		}),
		new ClothesItem({
			index: 79,
			slot: "feet",
			name: "shark slippers",
			name_cap: "Shark slippers",
			variable: "sharkslippers",
			description: "작은 발을 위한 신발입니다.",
			cost: 3500,
			shop: ["clothing"],
			type: ["normal"],
			combat: {
				reference: "wedgesandals",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			gender: "n",
			warmth: 2,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "sharkslippers.png",
			accIcon: "sharkslippers-acc.png",
		}),
		new ClothesItem({
			index: 80,
			slot: "feet",
			name: "snowball heels",
			name_cap: "Snowball heels",
			variable: "snowballheels",
			description: "통통 튀는 폼폼을 주의하세요.",
			cost: 11500,
			shop: ["clothing"],
			type: ["normal", "heels"],
			combat: {
				reference: "stripperheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 350,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "f",
			femininity: 200,
			warmth: 3,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "snowballheels.png",
			accIcon: "snowballheels-acc.png",
		}),
		new ClothesItem({
			index: 81,
			slot: "feet",
			name: "bow snow boots",
			name_cap: "Bow snow boots",
			variable: "bowsnowboots",
			combat: {
				reference: "lightuptrainers",
				hasMainImg: false,
				accColour: "primary",
			},
			description: "발을 따뜻하게 유지한다.",
			cost: 8000,
			shop: ["clothing"],
			type: ["normal"],
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 100,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			pattern: 0,
			pattern_options: ["detail"],
			pattern_layer: "tertiary",
			gender: "n",
			warmth: 4,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "bowsnowboots.png",
			accIcon: "bowsnowboots-acc.png",
		}),
		new ClothesItem({
			index: 82,
			slot: "feet",
			name: "soft slippers",
			name_cap: "Soft slippers",
			variable: "softslippers",
			description: "편안한 데일리 웨어입니다.",
			cost: 2500,
			shop: ["clothing"],
			type: ["normal"],
			combat: {
				reference: "wedgesandals",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "n",
			warmth: 2,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "softslippers.png",
			accIcon: "softslippers-acc.png",
		}),
		new ClothesItem({
			index: 83,
			slot: "feet",
			name: "strawberry slippers",
			name_cap: "Strawberry slippers",
			variable: "strawberryslippers",
			description: "아쉽게도 먹을 수는 없습니다.",
			cost: 3500,
			shop: ["clothing"],
			type: ["sleep"],
			combat: {
				reference: "lightuptrainers",
				accColour: "#ffffff",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			gender: "n",
			warmth: 2,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "strawberryslippers.png",
			accIcon: "strawberryslippers-acc.png",
		}),
		new ClothesItem({
			index: 84,
			slot: "feet",
			name: "suede pumps",
			name_cap: "Suede pumps",
			variable: "suedepumps",
			description: "출근용으로 좋습니다.",
			cost: 12000,
			shop: ["clothing"],
			type: ["normal", "formal"],
			combat: {
				reference: "kittenheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			gender: "f",
			femininity: 100,
			warmth: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "suedepumps.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 85,
			slot: "feet",
			name: "t-strap heels",
			name_cap: "T-strap heels",
			variable: "tstrapheels",
			description: "변치 않는 우아함.",
			cost: 13500,
			shop: ["clothing"],
			type: ["normal", "formal", "heels"],
			combat: {
				reference: "kittenheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 400,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "tstrapheels.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 86,
			slot: "feet",
			name: "wrinkled long boots",
			name_cap: "Wrinkled long boots",
			variable: "wrinkledlongboots",
			description: "부드러운 가죽으로 만들어졌습니다.",
			cost: 16000,
			shop: ["clothing"],
			type: ["normal", "heels"],
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 350,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			gender: "f",
			femininity: 100,
			warmth: 3,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "wrinkledlongboots.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 87,
			slot: "feet",
			name: "spat shoes",
			name_cap: "Spat shoes",
			variable: "spat shoes",
			combat: {
				reference: "lightuptrainers",
				hasMainImg: false,
			},
			description: "클래식한 빈티지 스타일이다.",
			cost: 10000,
			shop: ["clothing"],
			type: ["formal"],
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 1,
			colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			accessory: 1,
			accessory_colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			gender: "n",
			warmth: 2,
			iconFile: "spat-shoes.png",
			accIcon: "spat-shoes-acc.png",
		}),
	];
	setup.clothes.feet = clothing;

	/*
		Clothes that modders add go into this array. This should be empty in the base game at all times.
		These items should have a `modder` variable with the modder's name in a short string.
	*/
	setup.moddedClothes.feet = [];

	setup.moddedClothes.feet.forEach((x, i) => (x.index = setup.clothes.feet.length + i));
	setup.clothes.feet.push(...setup.moddedClothes.feet);
}
window.initFeet = initFeet;
