/* globals Dict */
// @ts-check

function finalizefoodstuff() {
	/** @type {Dict<FoodstuffItem>} */
	const sortedCatalog = {};
	Object.keys(setup.foodstuff)
		.sort()
		.forEach(key => {
			sortedCatalog[key] = setup.foodstuff[key];
		});

	setup.foodstuff = sortedCatalog;
}

function initFoodstuff() {
	/** @type {Dict<FoodstuffItem>} */
	setup.foodstuff = {
		red_rose: {
			index: 0,
			name: "red rose",
			singular: "red rose",
			plural: "red roses",
			icon: "red-rose.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 14,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 350,
			},
		},
		white_rose: {
			index: 1,
			name: "white rose",
			singular: "white rose",
			plural: "white roses",
			icon: "white-rose.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 14,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 350,
			},
		},
		orchid: {
			index: 2,
			name: "orchid",
			singular: "orchid",
			plural: "orchids",
			icon: "orchid.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 28,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["summer"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 500,
			},
		},
		daisy: {
			index: 3,
			name: "daisy",
			singular: "daisy",
			plural: "daisies",
			icon: "daisy.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 7,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn"],
				tags: [],
				featCost: 1,
			},
			shop: {
				sell_price: 150,
			},
		},
		tulip: {
			index: 4,
			name: "tulip",
			singular: "tulip",
			plural: "tulips",
			icon: "tulip.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 12,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 200,
			},
		},
		lotus: {
			index: 5,
			name: "lotus",
			singular: "lotus",
			plural: "lotuses",
			icon: "lotus.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "water",
				growth_days: 5,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn", "winter"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 300,
			},
		},
		lily: {
			index: 6,
			name: "lily",
			singular: "lily",
			plural: "lilies",
			icon: "lily.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 10,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 200,
			},
		},
		poppy: {
			index: 7,
			name: "poppy",
			singular: "poppy",
			plural: "poppies",
			icon: "poppy.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 8,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 200,
			},
		},
		apple: {
			index: 8,
			name: "apple",
			singular: "apple",
			plural: "apples",
			icon: "apple.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 50,
			},
			is_fishing_bait: true,
		},
		orange: {
			index: 9,
			name: "orange",
			singular: "orange",
			plural: "oranges",
			icon: "orange.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 300,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		banana: {
			index: 10,
			name: "banana",
			singular: "banana",
			plural: "bananas",
			icon: "banana.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 100,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		lemon: {
			index: 11,
			name: "lemon",
			singular: "lemon",
			plural: "lemons",
			icon: "lemon.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 120,
			},
			is_fishing_bait: true,
		},
		blood_lemon: {
			index: 12,
			name: "blood lemon",
			singular: "blood lemon",
			plural: "blood lemons",
			icon: "blood-lemon.gif",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 400,
			},
			food: {
				tags: ["aphrodisiac"],
			},
			is_fishing_bait: true,
		},
		pear: {
			index: 13,
			name: "pear",
			singular: "pear",
			plural: "pears",
			icon: "pear.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 80,
			},
			is_fishing_bait: true,
		},
		strawberry: {
			index: 14,
			name: "strawberry",
			singular: "strawberry",
			plural: "strawberries",
			icon: "strawberry.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 180,
			},
			is_fishing_bait: true,
		},
		peach: {
			index: 15,
			name: "peach",
			singular: "peach",
			plural: "peaches",
			icon: "peach.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 65,
			},
			is_fishing_bait: true,
		},
		plum: {
			index: 16,
			name: "plum",
			singular: "plum",
			plural: "plums",
			icon: "plum.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 80,
			},
			is_fishing_bait: true,
		},
		mushroom: {
			index: 17,
			name: "mushroom",
			singular: "mushroom",
			plural: "mushrooms",
			icon: "mushroom.png",
			category: "mushroom",
			kitchen_item_type_icon: "recipe-shroom.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 100,
			},
		},
		wolfshroom: {
			index: 18,
			name: "wolfshroom",
			singular: "wolfshroom",
			plural: "wolfshrooms",
			icon: "wolfshroom.png",
			category: "mushroom",
			kitchen_item_type_icon: "recipe-shroom.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 300,
			},
			food: {
				tags: ["aphrodisiac"],
			},
		},
		wild_honeycomb: {
			index: 19,
			name: "wild honeycomb",
			singular: "wild honeycomb",
			plural: "wild honeycombs",
			icon: "wild-honeycomb.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			shop: {
				sell_price: 12000,
				stall_size: "large",
			},
		},
		wild_carrot: {
			index: 20,
			name: "wild carrot",
			singular: "wild carrot",
			plural: "carrots",
			icon: "carrot.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 10,
				yield_multiplier: 3,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 80,
			},
			is_fishing_bait: true,
		},
		onion: {
			index: 21,
			name: "onion",
			singular: "onion",
			plural: "onions",
			icon: "onion.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 12,
				yield_multiplier: 3,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 120,
			},
			is_fishing_bait: true,
		},
		garlic_bulb: {
			index: 22,
			name: "garlic bulb",
			singular: "garlic bulb",
			plural: "garlic bulbs",
			icon: "garlic.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 8,
				yield_multiplier: 3,
				has_seeds: true,
				seasons: ["autumn"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 100,
			},
			is_fishing_bait: true,
		},
		potato: {
			index: 23,
			name: "potato",
			singular: "potato",
			plural: "potatoes",
			icon: "potato.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 7,
				yield_multiplier: 5,
				has_seeds: true,
				seasons: ["spring", "autumn", "winter"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 50,
			},
			is_fishing_bait: true,
		},
		strange_flower: {
			index: 24,
			name: "strange flower",
			singular: "strange flower",
			plural: "strange flowers",
			icon: "strange-flower.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			ingredient_alternatives: {
				normal: ["blood_lemon"],
				lewd: [],
			},
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 28,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn", "winter"],
				tags: [],
			},
			shop: {
				sell_price: 400,
			},
			food: {
				tags: ["aphrodisiac"],
			},
		},
		truffle: {
			index: 25,
			name: "truffle",
			singular: "truffle",
			plural: "truffles",
			icon: "truffle.png",
			category: "mushroom",
			kitchen_item_type_icon: "recipe-shroom.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 800,
			},
		},
		bottle_of_milk: {
			index: 26,
			name: "bottle of milk",
			singular: "bottle of milk",
			plural: "bottles of milk",
			icon: "milk.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			ingredient_alternatives: {
				normal: [],
				lewd: ["baby_bottle_of_breast_milk"],
			},
			tending: {
				affected_by_tending_skill: false,
				tags: [],
			},
			shop: {
				sell_price: 100,
			},
		},
		chicken_egg: {
			index: 27,
			name: "chicken egg",
			singular: "chicken egg",
			plural: "chicken eggs",
			icon: "egg.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			ingredient_alternatives: {
				normal: ["bird_egg"],
				lewd: [],
			},
			tending: {
				affected_by_tending_skill: false,
				tags: [],
			},
			shop: {
				sell_price: 40,
			},
		},
		bottle_of_breast_milk: {
			index: 28,
			name: "bottle of breast milk",
			singular: "bottle of breast milk",
			plural: "bottles of breast milk",
			icon: "breastmilk.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			shop: {
				sell_price: 3000,
				stall_size: "large",
			},
		},
		bottle_of_semen: {
			index: 29,
			name: "bottle of semen",
			singular: "bottle of semen",
			plural: "bottles of semen",
			icon: "semenbottle.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: false,
				tags: [],
			},
			shop: {
				sell_price: 3000,
				stall_size: "large",
			},
		},
		cabbage: {
			index: 30,
			name: "cabbage",
			singular: "cabbage",
			plural: "cabbages",
			icon: "cabbage.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 8,
				yield_multiplier: 3,
				has_seeds: true,
				seasons: ["spring", "winter"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 90,
			},
		},
		turnip: {
			index: 31,
			name: "turnip",
			singular: "turnip",
			plural: "turnips",
			icon: "turnip.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 12,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn", "winter"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 130,
			},
		},
		broccoli: {
			index: 32,
			name: "broccoli",
			singular: "broccoli",
			plural: "broccoli",
			icon: "broccoli.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 10,
				yield_multiplier: 3,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 100,
			},
		},
		ghostshroom: {
			index: 33,
			name: "ghostshroom",
			singular: "ghostshroom",
			plural: "ghostshrooms",
			icon: "ghostshroom.png",
			category: "mushroom",
			kitchen_item_type_icon: "recipe-shroom.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 200,
			},
		},
		blackberry: {
			index: 34,
			name: "blackberry",
			singular: "blackberry",
			plural: "blackberries",
			icon: "blackberry.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 7,
				stall_size: "small",
			},
			is_fishing_bait: true,
		},
		carnation: {
			index: 35,
			name: "carnation",
			singular: "carnation",
			plural: "carnations",
			icon: "carnation.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 3,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["autumn"],
				tags: [],
				featCost: 20,
			},
			shop: {
				sell_price: 200,
			},
		},
		bird_egg: {
			index: 36,
			name: "bird egg",
			singular: "bird egg",
			plural: "bird eggs",
			icon: "bird-egg.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			shop: {
				sell_price: 200,
			},
		},
		baby_bottle_of_breast_milk: {
			index: 37,
			name: "baby bottle of breast milk",
			singular: "baby bottle of breast milk",
			plural: "baby bottles of breast milk",
			icon: "babybottle.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: false,
				tags: [],
			},
			shop: {
				sell_price: 200,
			},
		},
		plumeria: {
			index: 38,
			name: "plumeria",
			singular: "plumeria",
			plural: "plumerias",
			icon: "plumeria.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 12,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 250,
			},
		},
		oyster_pearl: {
			index: 39,
			name: "oyster pearl",
			singular: "oyster pearl",
			plural: "oyster pearls",
			icon: "oyster-pearl.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			shop: {
				sell_price: 50000,
				stall_size: "large",
			},
		},
		bread: {
			index: 40,
			name: "bread",
			singular: "piece of bread",
			plural: "pieces of bread",
			icon: "bread.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			is_fishing_bait: true,
			recipe: {
				recipe_name: "bread",
				difficulty: 1,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["flour", "salt", "vegetable_oil"],
				tags: [],
			},
			food: {
				tags: ["vegan"],
			},
		},
		flour: {
			index: 41,
			name: "flour",
			singular: "spoonful of flour",
			plural: "spoonfuls of flour",
			icon: "flour.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 10,
			},
			recipe: {
				recipe_name: "flour",
				difficulty: 1,
				cook_minutes: 20,
				servings: 10,
				ingredients: ["wheat"],
				tags: [],
			},
		},
		salt: {
			index: 42,
			name: "salt",
			singular: "pinch of salt",
			plural: "pinches of salt",
			icon: "salt.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 5,
				available_in: ["supermarket"],
				bought_in_bulk: 25,
			},
		},
		vegetable_oil: {
			index: 43,
			name: "vegetable oil",
			singular: "spoonful of vegetable oil",
			plural: "spoonfuls of vegetable oil",
			icon: "vegetable-oil.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 10,
				available_in: ["supermarket"],
				bought_in_bulk: 25,
			},
		},
		pizza: {
			index: 44,
			name: "pizza",
			singular: "pizza",
			plural: "pizzas",
			icon: "pizza.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "pizza",
				difficulty: 2,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["bread", "tomato", "garlic_bulb", "cheese"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian"],
			},
		},
		tomato: {
			index: 45,
			name: "tomato",
			singular: "tomato",
			plural: "tomatoes",
			icon: "tomato.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 10,
				yield_multiplier: 4,
				has_seeds: true,
				seasons: ["summer", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 70,
			},
		},
		cheese: {
			index: 46,
			name: "cheese",
			singular: "piece of cheese",
			plural: "pieces of cheese",
			icon: "cheese.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 500,
			},
			recipe: {
				recipe_name: "cheese",
				difficulty: 1,
				cook_minutes: 60,
				servings: 1,
				ingredients: ["bottle_of_milk"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian"],
			},
		},
		macaroni_cheese: {
			index: 47,
			name: "macaroni cheese",
			singular: "serving of macaroni and cheese",
			plural: "servings of macaroni and cheese",
			icon: "macaroni-cheese.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 800,
			},
			recipe: {
				recipe_name: "macaroni and cheese",
				difficulty: 2,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["bottle_of_milk", "cheese", "flour", "pasta", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		pasta: {
			index: 48,
			name: "pasta",
			singular: "serving of pasta",
			plural: "servings of pasta",
			icon: "pasta.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 200,
			},
			recipe: {
				recipe_name: "pasta",
				difficulty: 1,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["flour", "chicken_egg", "vegetable_oil", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		cauliflower_cheese: {
			index: 49,
			name: "cauliflower cheese",
			singular: "serving of cauliflower cheese",
			plural: "servings of cauliflower cheese",
			icon: "cauliflower-cheese.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "cauliflower cheese",
				difficulty: 2,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["cauliflower", "cheese", "garlic_bulb", "bottle_of_milk"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		wheat: {
			index: 50,
			name: "wheat",
			singular: "cup of wheat",
			plural: "cups of wheat",
			icon: "wheat.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 9,
				yield_multiplier: 12,
				has_seeds: true,
				seed_name: "wheat",
				seasons: ["spring", "summer", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 40,
			},
		},
		prawn_bisque: {
			index: 51,
			name: "prawn bisque",
			singular: "serving of prawn bisque",
			plural: "servings of prawn bisque",
			icon: "prawn-bisque.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1500,
			},
			recipe: {
				recipe_name: "prawn bisque",
				difficulty: 3,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["prawn", "onion", "garlic_bulb", "vegetable_oil", "cream", "lemon"],
				tags: [],
			},
			food: {
				tags: ["seafood"],
			},
		},
		cream: {
			index: 52,
			name: "cream",
			singular: "spoonful of cream",
			plural: "spoonfuls of cream",
			icon: "cream.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			ingredient_alternatives: {
				normal: [],
				lewd: ["bottle_of_semen"],
			},
			shop: {
				sell_price: 100,
			},
		},
		chelsea_bun: {
			index: 53,
			name: "chelsea bun",
			singular: "Chelsea bun",
			plural: "Chelsea buns",
			icon: "chelsea-bun.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 200,
			},
			recipe: {
				recipe_name: "Chelsea buns",
				difficulty: 2,
				cook_minutes: 60,
				servings: 4,
				ingredients: ["flour", "salt", "butter", "sugar", "bottle_of_milk", "honey"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		honey: {
			index: 54,
			name: "honey",
			singular: "spoonful of honey",
			plural: "spoonfuls of honey",
			icon: "honey.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 10,
			},
			recipe: {
				recipe_name: "honey",
				difficulty: 1,
				cook_minutes: 60,
				servings: 1200,
				ingredients: ["wild_honeycomb"],
				tags: [],
			},
		},
		butter: {
			index: 55,
			name: "butter",
			singular: "spoonful of butter",
			plural: "spoonfuls of butter",
			icon: "butter.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 10,
			},
			recipe: {
				recipe_name: "butter",
				difficulty: 1,
				cook_minutes: 20,
				servings: 10,
				ingredients: ["bottle_of_milk"],
				tags: [],
			},
		},
		naan_bread: {
			index: 56,
			name: "naan bread",
			singular: "piece of naan bread",
			plural: "pieces of naan bread",
			icon: "naan-bread.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 200,
			},
			recipe: {
				recipe_name: "naan bread",
				difficulty: 2,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["bottle_of_milk", "flour", "vegetable_oil", "chicken_egg", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		pastry: {
			index: 57,
			name: "pastry",
			singular: "piece of pastry",
			plural: "pieces of pastry",
			icon: "pastry.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 150,
			},
			recipe: {
				recipe_name: "pastries",
				difficulty: 1,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["butter", "flour", "salt"],
				tags: [],
			},
		},
		quiche: {
			index: 58,
			name: "quiche",
			singular: "serving of quiche",
			plural: "servings of quiche",
			icon: "quiche.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 200,
			},
			recipe: {
				recipe_name: "quiche",
				difficulty: 3,
				cook_minutes: 20,
				servings: 6,
				ingredients: ["pastry", "bottle_of_milk", "chicken_egg", "bacon", "cheese", "tomato"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		bacon: {
			index: 59,
			name: "bacon",
			singular: "rasher of bacon",
			plural: "rashers of bacon",
			icon: "bacon.png",
			category: "meat",
			kitchen_item_type_icon: "recipe-meat.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 200,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		mince_pie: {
			index: 60,
			name: "mince pie",
			singular: "mince pie",
			plural: "mince pies",
			icon: "mince-pie.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 400,
			},
			recipe: {
				recipe_name: "mince pie",
				difficulty: 2,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["pastry", "blackberry", "sugar"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		sugar: {
			index: 61,
			name: "sugar",
			singular: "spoonful of sugar",
			plural: "spoonfuls of sugar",
			icon: "sugar.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 5,
				available_in: ["supermarket"],
				bought_in_bulk: 25,
			},
		},
		sausage_roll: {
			index: 62,
			name: "sausage roll",
			singular: "sausage roll",
			plural: "sausage rolls",
			icon: "sausage-roll.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 150,
			},
			recipe: {
				recipe_name: "sausage rolls",
				difficulty: 2,
				cook_minutes: 40,
				servings: 6,
				ingredients: ["pastry", "salt", "sausage", "chicken_egg", "lemon"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		sausage: {
			index: 63,
			name: "sausage",
			singular: "sausage",
			plural: "sausages",
			icon: "sausage.png",
			category: "meat",
			kitchen_item_type_icon: "recipe-meat.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 200,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		potato_pancake: {
			index: 64,
			name: "potato pancake",
			singular: "potato pancake",
			plural: "potato pancakes",
			icon: "potato-pancake.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "potato pancakes",
				difficulty: 2,
				cook_minutes: 10,
				servings: 4,
				ingredients: ["potato", "onion", "chicken_egg", "vegetable_oil"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		onion_bhaji: {
			index: 65,
			name: "onion bhaji",
			singular: "onion bhaji",
			plural: "onion bhajis",
			icon: "onion-bhaji.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "onion bhajis",
				difficulty: 2,
				cook_minutes: 10,
				servings: 4,
				ingredients: ["flour", "onion", "chilli_pepper"],
				tags: [],
			},
			food: {
				tags: ["vegan", "spicy"],
			},
		},
		chilli_pepper: {
			index: 66,
			name: "chilli pepper",
			singular: "chilli pepper",
			plural: "chilli peppers",
			icon: "chilli-pepper.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				planting_bed: "earth",
				growth_days: 22,
				yield_multiplier: 6,
				has_seeds: true,
				seasons: ["summer", "autumn"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 80,
			},
			is_fishing_bait: true,
		},
		samosa: {
			index: 67,
			name: "samosa",
			singular: "samosa",
			plural: "samosas",
			icon: "samosa.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 60,
			},
			recipe: {
				recipe_name: "samosas",
				difficulty: 3,
				cook_minutes: 15,
				servings: 5,
				ingredients: ["pastry", "potato", "chilli_pepper", "lemon"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "spicy"],
			},
		},
		sweet_and_sour_chicken: {
			index: 68,
			name: "sweet and sour chicken",
			singular: "serving of sweet and sour chicken",
			plural: "servings of sweet and sour chicken",
			icon: "sweet-and-sour-chicken.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 800,
			},
			recipe: {
				recipe_name: "sweet and sour chicken",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["chicken", "vegetable_oil", "pepper", "sugar", "onion"],
				tags: [],
			},
			food: {
				tags: ["spicy"],
			},
		},
		chicken: {
			index: 69,
			name: "chicken",
			singular: "serving of chicken",
			plural: "servings of chicken",
			icon: "chicken.png",
			category: "meat",
			kitchen_item_type_icon: "recipe-meat.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 300,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		pepper: {
			index: 70,
			name: "pepper",
			singular: "pepper",
			plural: "peppers",
			icon: "pepper.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 15,
				yield_multiplier: 4,
				has_seeds: true,
				seasons: ["spring", "summer", "winter"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 100,
			},
			is_fishing_bait: true,
		},
		kedgeree: {
			index: 71,
			name: "kedgeree",
			singular: "serving of kedgeree",
			plural: "servings of kedgeree",
			icon: "kedgeree.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1600,
			},
			recipe: {
				recipe_name: "kedgeree",
				difficulty: 3,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["haddock", "rice", "chicken_egg", "butter", "vegetable_oil", "lemon", "cream"],
				ingredient_alternatives: {
					normal: {
						haddock: ["cod", "herring", "mackerel", "salmon", "trout", "whiting", "eel"],
					},
					lewd: {},
				},
				tags: [],
			},
			food: {
				tags: ["seafood"],
			},
		},
		rice: {
			index: 72,
			name: "rice",
			singular: "cup of rice",
			plural: "cups of rice",
			icon: "rice.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "water",
				growth_days: 26,
				yield_multiplier: 20,
				has_seeds: true,
				seed_name: "rice",
				seasons: ["spring", "summer", "autumn"],
				tags: [],
				featCost: 20,
			},
			shop: {
				sell_price: 50,
			},
		},
		haddock: {
			index: 73,
			name: "haddock",
			singular: "haddock",
			plural: "haddock",
			icon: "haddock.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 600,
				available_in: ["supermarket"],
			},
		},
		honeyed_pork: {
			index: 74,
			name: "honeyed pork",
			singular: "serving of honeyed pork",
			plural: "servings of honeyed pork",
			icon: "honeyed-pork.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1100,
			},
			recipe: {
				recipe_name: "honeyed pork",
				difficulty: 2,
				cook_minutes: 45,
				servings: 1,
				ingredients: ["pork", "salt", "honey", "chicken_egg"],
				tags: [],
			},
			food: {
				tags: ["carnivore"],
			},
		},
		beef_wellington: {
			index: 75,
			name: "beef wellington",
			singular: "serving of beef wellington",
			plural: "servings of beef wellington",
			icon: "beef-wellington.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1800,
			},
			recipe: {
				recipe_name: "beef wellington",
				difficulty: 4,
				cook_minutes: 60,
				servings: 1,
				ingredients: ["beef", "onion", "pastry", "chicken_egg", "salt", "mushroom"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		salmon_wellington: {
			index: 76,
			name: "salmon wellington",
			singular: "serving of salmon wellington",
			plural: "servings of salmon wellington",
			icon: "salmon-wellington.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1800,
			},
			recipe: {
				recipe_name: "salmon wellington",
				difficulty: 3,
				cook_minutes: 60,
				servings: 1,
				ingredients: ["salmon", "broccoli", "pastry", "chicken_egg", "salt"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		hamburger: {
			index: 77,
			name: "hamburger",
			singular: "hamburger",
			plural: "hamburgers",
			icon: "burger.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 600,
			},
			recipe: {
				recipe_name: "hamburgers",
				difficulty: 1,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["beef", "bread", "onion", "tomato"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		cheeseburger: {
			index: 78,
			name: "cheeseburger",
			singular: "cheeseburger",
			plural: "cheeseburgers",
			icon: "cheeseburger.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 800,
			},
			recipe: {
				recipe_name: "cheeseburgers",
				difficulty: 1,
				cook_minutes: 15,
				servings: 2,
				ingredients: ["beef", "bread", "onion", "tomato", "cheese"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		chips: {
			index: 79,
			name: "chips",
			singular: "packet of chips",
			plural: "packets of chips",
			icon: "chips.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 400,
			},
			recipe: {
				recipe_name: "chips",
				difficulty: 2,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["potato", "vegetable_oil", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegan"],
			},
		},
		cheese_topped_trout: {
			index: 80,
			name: "cheese topped trout",
			singular: "serving of cheese topped trout",
			plural: "servings of cheese topped trout",
			icon: "cheese-topped-trout.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1600,
			},
			recipe: {
				recipe_name: "cheese topped trout",
				difficulty: 3,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["trout", "bread", "cheese", "vegetable_oil", "butter", "lemon"],
				tags: [],
			},
			food: {
				tags: ["seafood"],
			},
		},
		salmon: {
			index: 81,
			name: "salmon",
			singular: "salmon",
			plural: "salmon",
			icon: "salmon.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 600,
				available_in: ["supermarket"],
			},
		},
		trout: {
			index: 82,
			name: "trout",
			singular: "trout",
			plural: "trout",
			icon: "trout.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 800,
				available_in: ["supermarket"],
			},
		},
		spaghetti_bolognese: {
			index: 83,
			name: "spaghetti bolognese",
			singular: "serving of spaghetti bolognese",
			plural: "servings of spaghetti bolognese",
			icon: "spaghetti-bolognese.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1100,
			},
			recipe: {
				recipe_name: "spaghetti bolognese",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["pasta", "beef", "vegetable_oil", "garlic_bulb", "tomato"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		lasagne: {
			index: 84,
			name: "lasagne",
			singular: "serving of lasagne",
			plural: "servings of lasagne",
			icon: "lasagne.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1400,
			},
			recipe: {
				recipe_name: "lasagne",
				difficulty: 3,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["pasta", "beef", "cheese", "flour", "garlic_bulb", "tomato"],
				ingredient_alternatives: {
					normal: {
						beef: ["chicken"],
					},
					lewd: {},
				},
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		carbonara: {
			index: 85,
			name: "carbonara",
			singular: "serving of carbonara",
			plural: "servings of carbonara",
			icon: "carbonara.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "carbonara",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["pasta", "cheese", "flour", "bottle_of_milk", "pork"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		chicken_tikka_masala: {
			index: 86,
			name: "chicken tikka masala",
			singular: "serving of chicken tikka masala",
			plural: "servings of chicken tikka masala",
			icon: "chicken-tikka-masala.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1700,
			},
			recipe: {
				recipe_name: "chicken tikka masala",
				difficulty: 3,
				cook_minutes: 45,
				servings: 1,
				ingredients: ["chicken", "vegetable_oil", "onion", "garlic_bulb", "tomato", "butter", "lemon", "naan_bread", "rice"],
				tags: [],
			},
			food: {
				tags: ["spicy"],
			},
		},
		chilli_con_carne: {
			index: 87,
			name: "chilli con carne",
			singular: "serving of chilli con carne",
			plural: "servings of chilli con carne",
			icon: "chilli-con-carne.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1300,
			},
			recipe: {
				recipe_name: "chilli con carne",
				difficulty: 3,
				cook_minutes: 45,
				servings: 1,
				ingredients: ["beef", "vegetable_oil", "onion", "garlic_bulb", "tomato", "chilli_pepper"],
				tags: [],
			},
			food: {
				tags: ["spicy"],
			},
		},
		rich_biscuit: {
			index: 88,
			name: "rich biscuit",
			singular: "rich biscuit",
			plural: "rich biscuits",
			icon: "rich-biscuit.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 50,
			},
			recipe: {
				recipe_name: "rich biscuits",
				difficulty: 1,
				cook_minutes: 20,
				servings: 10,
				ingredients: ["chicken_egg", "flour", "sugar", "lemon"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		shortbread: {
			index: 89,
			name: "shortbread",
			singular: "piece of shortbread",
			plural: "pieces of shortbread",
			icon: "shortbread.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 150,
			},
			recipe: {
				recipe_name: "shortbread",
				difficulty: 2,
				cook_minutes: 35,
				servings: 5,
				ingredients: ["butter", "flour", "sugar"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		melting_moment: {
			index: 90,
			name: "melting moment",
			singular: "melting moment",
			plural: "melting moments",
			icon: "melting-moment.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 80,
			},
			recipe: {
				recipe_name: "melting moments",
				difficulty: 1,
				cook_minutes: 20,
				servings: 5,
				ingredients: ["butter", "flour", "sugar", "jam"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		choc_chip_cookie: {
			index: 91,
			name: "choc chip cookie",
			singular: "chocolate chip cookie",
			plural: "chocolate chip cookies",
			icon: "choc-chip-cookie.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "chocolate chip cookies",
				difficulty: 1,
				cook_minutes: 15,
				servings: 10,
				ingredients: ["butter", "flour", "sugar", "chicken_egg", "chocolate"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		cocoa_powder: {
			index: 92,
			name: "cocoa powder",
			singular: "cup of cocoa powder",
			plural: "cups of cocoa powder",
			icon: "cocoa-powder.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 200,
				available_in: ["supermarket"],
				bought_in_bulk: 5,
			},
		},
		chocolate: {
			index: 93,
			name: "chocolate",
			singular: "slab of chocolate",
			plural: "slabs of chocolate",
			icon: "chocolate.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 700,
			},
			recipe: {
				recipe_name: "chocolate",
				difficulty: 1,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["butter", "bottle_of_milk", "cocoa_powder"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		apple_strudel: {
			index: 94,
			name: "apple strudel",
			singular: "apple strudel",
			plural: "apple strudels",
			icon: "apple-strudel.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "apple strudels",
				difficulty: 2,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["pastry", "apple", "sugar", "honey", "butter"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		souffle: {
			index: 95,
			name: "soufflé",
			singular: "soufflé",
			plural: "soufflés",
			icon: "souffle.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 3000,
			},
			recipe: {
				recipe_name: "souffl\u00E9s",
				difficulty: 4,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["chicken_egg", "cream", "sugar", "butter", "flour", "lemon"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		tart: {
			index: 96,
			name: "tart",
			singular: "tart",
			plural: "tarts",
			icon: "tart.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "tarts",
				difficulty: 2,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["pastry", "chocolate"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		lemon_meringue_pie: {
			index: 97,
			name: "lemon meringue pie",
			singular: "lemon meringue pie",
			plural: "lemon meringue pies",
			icon: "lemon-meringue-pie.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1600,
			},
			recipe: {
				recipe_name: "lemon meringue pie",
				difficulty: 3,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["pastry", "lemon", "sugar", "butter", "chicken_egg"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		sponge_cake: {
			index: 98,
			name: "sponge cake",
			singular: "sponge cake",
			plural: "sponge cakes",
			icon: "sponge-cake.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "sponge cake",
				difficulty: 2,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["flour", "butter", "sugar", "cream", "chicken_egg", "jam"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		swiss_roll: {
			index: 99,
			name: "swiss roll",
			singular: "Swiss roll",
			plural: "Swiss rolls",
			icon: "swiss-roll.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1500,
			},
			recipe: {
				recipe_name: "Swiss rolls",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["flour", "butter", "cream", "chicken_egg", "jam", "orange", "sugar"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		scone: {
			index: 100,
			name: "scone",
			singular: "scone",
			plural: "scones",
			icon: "scone.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 150,
			},
			recipe: {
				recipe_name: "scones",
				difficulty: 2,
				cook_minutes: 20,
				servings: 4,
				ingredients: ["flour", "butter", "sugar", "salt", "bottle_of_milk"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		brownie: {
			index: 101,
			name: "brownie",
			singular: "brownie",
			plural: "brownies",
			icon: "brownie.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 300,
			},
			recipe: {
				recipe_name: "brownies",
				difficulty: 2,
				cook_minutes: 50,
				servings: 4,
				ingredients: ["butter", "flour", "chocolate", "chicken_egg", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		carrot_cake: {
			index: 102,
			name: "carrot cake",
			singular: "carrot cake",
			plural: "carrot cakes",
			icon: "carrot-cake.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1400,
			},
			recipe: {
				recipe_name: "carrot cake",
				difficulty: 2,
				cook_minutes: 50,
				servings: 1,
				ingredients: ["wild_carrot", "sugar", "chicken_egg", "vegetable_oil", "flour", "lemon", "cream", "butter"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		creme_brulee: {
			index: 103,
			name: "crème brûlée",
			singular: "pot of crème brûlée",
			plural: "pots of crème brûlée",
			icon: "creme-brulee.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 600,
			},
			recipe: {
				recipe_name: "crème brûlée",
				difficulty: 2,
				cook_minutes: 50,
				servings: 1,
				ingredients: ["bottle_of_milk", "cream", "sugar", "chicken_egg"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		date: {
			index: 104,
			name: "date",
			singular: "date",
			plural: "dates",
			icon: "date.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 50,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		sticky_toffee_pudding: {
			index: 105,
			name: "sticky toffee pudding",
			singular: "sticky toffee pudding",
			plural: "sticky toffee puddings",
			icon: "sticky-toffee-pudding.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "sticky toffee pudding",
				difficulty: 2,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["date", "flour", "chicken_egg", "butter", "sugar", "bottle_of_milk", "cream"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		chicken_vindaloo: {
			index: 106,
			name: "chicken vindaloo",
			singular: "serving of chicken vindaloo",
			plural: "servings of chicken vindaloo",
			icon: "chicken-vindaloo.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1800,
			},
			recipe: {
				recipe_name: "chicken vindaloo",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["chicken", "vegetable_oil", "chilli_pepper", "onion", "tomato", "lemon", "garlic_bulb", "naan_bread", "rice"],
				tags: [],
			},
			food: {
				tags: ["spicy"],
			},
		},
		flapjack: {
			index: 107,
			name: "flapjack",
			singular: "flapjack square",
			plural: "flapjack squares",
			icon: "flapjack.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "flapjack squares",
				difficulty: 2,
				cook_minutes: 25,
				servings: 6,
				ingredients: ["butter", "sugar", "oats", "lemon"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		cherry: {
			index: 108,
			name: "cherry",
			singular: "cherry",
			plural: "cherries",
			icon: "cherry.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 20,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		belgian_bun: {
			index: 109,
			name: "belgian bun",
			singular: "Belgian bun",
			plural: "Belgian buns",
			icon: "belgian-bun.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "Belgian buns",
				difficulty: 2,
				cook_minutes: 40,
				servings: 10,
				ingredients: ["flour", "sugar", "bottle_of_milk", "chicken_egg", "lemon", "cherry"],
				tags: [],
			},
			food: {
				tags: ["sweet"],
			},
		},
		lime: {
			index: 110,
			name: "lime",
			singular: "lime",
			plural: "limes",
			icon: "lime.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 250,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		linguine: {
			index: 111,
			name: "linguine",
			singular: "serving of linguine",
			plural: "servings of linguine",
			icon: "linguine.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 700,
			},
			recipe: {
				recipe_name: "linguine",
				difficulty: 3,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["vegetable_oil", "lemon", "pasta", "cream"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		steak: {
			index: 112,
			name: "steak",
			singular: "serving of steak",
			plural: "servings of steak",
			icon: "steak.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "steak",
				difficulty: 3,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["vegetable_oil", "beef"],
				tags: [],
			},
			food: {
				tags: ["carnivore"],
			},
		},
		full_english_breakfast: {
			index: 113,
			name: "full english breakfast",
			singular: "full English breakfast",
			plural: "full English breakfasts",
			icon: "full-english-breakfast.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 900,
			},
			recipe: {
				recipe_name: "Full English breakfast",
				difficulty: 2,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["vegetable_oil", "bacon", "sausage", "mushroom", "tomato", "chicken_egg"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		apple_crumble: {
			index: 114,
			name: "apple crumble",
			singular: "serving of apple crumble",
			plural: "servings of apple crumble",
			icon: "apple-crumble.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 700,
			},
			recipe: {
				recipe_name: "apple crumble",
				difficulty: 2,
				cook_minutes: 35,
				servings: 1,
				ingredients: ["apple", "sugar", "flour", "butter", "oats", "cream"],
				tags: [],
			},
			food: {
				tags: ["sweet"],
			},
		},
		bakewell_tart: {
			index: 115,
			name: "Bakewell tart",
			singular: "Bakewell tart",
			plural: "Bakewell tarts",
			icon: "bakewell-tart.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "Bakewell tarts",
				difficulty: 3,
				cook_minutes: 35,
				servings: 1,
				ingredients: ["shortbread", "cream", "cherry"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["sweet"],
			},
		},
		cod: {
			index: 116,
			name: "cod",
			singular: "cod",
			plural: "cod",
			icon: "cod.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 700,
				available_in: [],
			},
		},
		fish_and_chips: {
			index: 117,
			name: "fish and chips",
			singular: "serving of fish and chips",
			plural: "servings of fish and chips",
			icon: "fish-and-chips.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1400,
			},
			recipe: {
				recipe_name: "fish and chips",
				difficulty: 2,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["cod", "chips", "vegetable_oil", "flour"],
				ingredient_alternatives: {
					normal: {
						cod: ["haddock", "whiting", "flounder", "bass", "perch", "pike"],
					},
					lewd: {},
				},
				tags: [],
			},
			food: {
				tags: ["seafood"],
			},
		},
		clam: {
			index: 118,
			name: "clam",
			singular: "clam",
			plural: "clams",
			icon: "clam.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 400,
				available_in: ["supermarket"],
			},
		},
		clam_chowder: {
			index: 119,
			name: "clam chowder",
			singular: "serving of clam chowder",
			plural: "servings of clam chowder",
			icon: "clam-chowder.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1300,
			},
			recipe: {
				recipe_name: "clam chowder",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["clam", "butter", "bacon", "onion", "flour", "bottle_of_milk", "cream", "potato"],
				tags: [],
			},
			food: {
				tags: ["seafood"],
			},
		},
		cheese_and_crackers: {
			index: 120,
			name: "cheese and crackers",
			singular: "serving of cheese and crackers",
			plural: "servings of cheese and crackers",
			icon: "cheese-and-crackers.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 800,
			},
			recipe: {
				recipe_name: "cheese and crackers",
				difficulty: 1,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["flour", "salt", "sugar", "vegetable_oil", "cheese"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		bangers_and_mash: {
			index: 121,
			name: "bangers and mash",
			singular: "serving of bangers and mash",
			plural: "servings of bangers and mash",
			icon: "bangers-and-mash.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "bangers and mash",
				difficulty: 2,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["vegetable_oil", "sausage", "butter", "bottle_of_milk", "potato"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		yorkshire_pudding: {
			index: 122,
			name: "yorkshire pudding",
			singular: "yorkshire pudding",
			plural: "yorkshire puddings",
			icon: "yorkshire-pudding.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "yorkshire pudding",
				difficulty: 2,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["flour", "chicken_egg", "bottle_of_milk", "vegetable_oil"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		stuffing: {
			index: 123,
			name: "stuffing",
			singular: "stuffing ball",
			plural: "stuffing balls",
			icon: "stuffing.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "stuffing",
				difficulty: 2,
				cook_minutes: 40,
				servings: 6,
				ingredients: ["butter", "vegetable_oil", "onion", "garlic_bulb", "bread", "chicken_egg"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		roast_dinner: {
			index: 124,
			name: "roast dinner",
			singular: "serving of roast dinner",
			plural: "servings of roast dinner",
			icon: "roast-dinner.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 2400,
			},
			recipe: {
				recipe_name: "roast dinner",
				difficulty: 3,
				cook_minutes: 60,
				servings: 1,
				ingredients: [
					"yorkshire_pudding",
					"stuffing",
					"chicken",
					"beef",
					"pork",
					"potato",
					"wild_carrot",
					"cabbage",
					"onion",
					"turnip",
					"vegetable_oil",
					"salt",
				],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		crumpet: {
			index: 125,
			name: "crumpet",
			singular: "crumpet",
			plural: "crumpets",
			icon: "crumpet.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "crumpets",
				difficulty: 2,
				cook_minutes: 20,
				servings: 5,
				ingredients: ["flour", "butter", "salt", "sugar"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		orange_juice: {
			index: 126,
			name: "orange juice",
			singular: "glass of orange juice",
			plural: "glasses of orange juice",
			icon: "orange-juice.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "drink",
			shop: {
				sell_price: 55,
			},
			recipe: {
				recipe_name: "orange juice",
				difficulty: 1,
				cook_minutes: 5,
				servings: 2,
				ingredients: ["orange", "sugar"],
				tags: [],
			},
			food: {
				tags: ["vegan", "drink"],
			},
		},
		lemonade: {
			index: 127,
			name: "lemonade",
			singular: "glass of lemonade",
			plural: "glasses of lemonade",
			icon: "lemonade.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "drink",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "lemonade",
				difficulty: 1,
				cook_minutes: 5,
				servings: 2,
				ingredients: ["lemon", "sugar"],
				tags: [],
			},
			food: {
				tags: ["vegan", "drink"],
			},
		},
		banana_bread: {
			index: 128,
			name: "banana bread",
			singular: "loaf of banana bread",
			plural: "loaves of banana bread",
			icon: "banana-bread.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 500,
			},
			recipe: {
				recipe_name: "banana bread",
				difficulty: 2,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["butter", "sugar", "chicken_egg", "flour", "banana"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
			is_fishing_bait: true,
		},
		red_wine: {
			index: 129,
			name: "red wine",
			singular: "bottle of red wine",
			plural: "bottles of red wine",
			icon: "red-wine.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "drink",
			shop: {
				sell_price: 600,
				available_in: ["supermarket"],
			},
		},
		white_wine: {
			index: 130,
			name: "white wine",
			singular: "bottle of white wine",
			plural: "bottles of white wine",
			icon: "white-wine.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "drink",
			shop: {
				sell_price: 600,
				available_in: ["supermarket"],
			},
		},
		poached_pear: {
			index: 131,
			name: "poached pear",
			singular: "poached pear",
			plural: "poached pears",
			icon: "poached-pear.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "poached pears",
				difficulty: 3,
				cook_minutes: 21,
				servings: 1,
				ingredients: ["pear", "sugar", "red_wine"],
				tags: [],
			},
			food: {
				tags: ["vegan", "alcohol", "sweet"],
			},
		},
		peach_panzanella: {
			index: 132,
			name: "peach panzanella",
			singular: "serving of peach panzanella",
			plural: "servings of peach panzanella",
			icon: "peach-panzanella.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 600,
			},
			recipe: {
				recipe_name: "peach panzanella",
				difficulty: 2,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["peach", "bread", "cheese", "vegetable_oil", "lemon"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		plum_pudding: {
			index: 133,
			name: "plum pudding",
			singular: "serving of plum pudding",
			plural: "servings of plum pudding",
			icon: "plum-pudding.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1400,
			},
			recipe: {
				recipe_name: "plum pudding",
				difficulty: 3,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["plum", "flour", "bread", "sugar", "orange", "lemon", "cherry", "wild_carrot"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		spinach: {
			index: 134,
			name: "spinach",
			singular: "spinach leaf",
			plural: "spinach leaves",
			icon: "spinach.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 10,
				yield_multiplier: 6,
				has_seeds: true,
				seed_name: "spinach",
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 60,
			},
		},
		salad: {
			index: 135,
			name: "salad",
			singular: "serving of salad",
			plural: "servings of salad",
			icon: "salad.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1100,
			},
			recipe: {
				recipe_name: "salad",
				difficulty: 2,
				cook_minutes: 10,
				servings: 1,
				ingredients: ["spinach", "tomato", "onion", "garlic_bulb", "chilli_pepper", "pepper", "lime"],
				tags: [],
			},
			food: {
				tags: ["vegan"],
			},
		},
		arancini: {
			index: 136,
			name: "arancini",
			singular: "arancini ball",
			plural: "arancini balls",
			icon: "arancini.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 700,
			},
			recipe: {
				recipe_name: "arancini",
				difficulty: 3,
				cook_minutes: 40,
				servings: 4,
				ingredients: ["vegetable_oil", "butter", "onion", "rice", "garlic_bulb", "white_wine", "cheese", "lemon", "flour", "chicken_egg", "truffle"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		wolfbrew: {
			index: 137,
			name: "wolfbrew",
			singular: "bottle of wolfbrew",
			plural: "bottles of wolfbrew",
			icon: "wolfbrew.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "drink",
			shop: {
				sell_price: 3000,
			},
			recipe: {
				recipe_name: "wolfbrew",
				difficulty: 5,
				cook_minutes: 60,
				servings: 1,
				ingredients: ["wolfshroom", "red_wine", "strange_flower"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "drink", "alcohol", "tainted"],
			},
		},
		ghostbrew: {
			index: 138,
			name: "ghostbrew",
			singular: "bottle of ghostbrew",
			plural: "bottles of ghostbrew",
			icon: "ghostbrew.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "drink",
			shop: {
				sell_price: 3000,
			},
			recipe: {
				recipe_name: "ghostbrew",
				difficulty: 5,
				cook_minutes: 60,
				servings: 1,
				ingredients: ["ghostshroom", "white_wine", "strange_flower"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "drink", "alcohol", "tainted"],
			},
		},
		beef: {
			index: 139,
			name: "beef",
			singular: "serving of beef",
			plural: "servings of beef",
			icon: "beef.png",
			category: "meat",
			kitchen_item_type_icon: "recipe-meat.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 1000,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		pork: {
			index: 140,
			name: "pork",
			singular: "serving of pork",
			plural: "servings of pork",
			icon: "pork.png",
			category: "meat",
			kitchen_item_type_icon: "recipe-meat.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 700,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		cauliflower: {
			index: 141,
			name: "cauliflower",
			singular: "cauliflower",
			plural: "cauliflowers",
			icon: "cauliflower.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 30,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn", "winter"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 400,
			},
		},
		oats: {
			index: 142,
			name: "oats",
			singular: "cup of oat",
			plural: "cups of oats",
			icon: "oats.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 100,
				available_in: ["supermarket"],
				bought_in_bulk: 5,
			},
		},
		prawn: {
			index: 143,
			name: "prawn",
			singular: "prawn",
			plural: "prawns",
			icon: "prawn.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 300,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		omelette: {
			index: 144,
			name: "omelette",
			singular: "omelette",
			plural: "omelettes",
			icon: "omelette.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 300,
			},
			recipe: {
				recipe_name: "omelettes",
				difficulty: 1,
				cook_minutes: 5,
				servings: 1,
				ingredients: ["chicken_egg", "vegetable_oil", "butter"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		porridge: {
			index: 145,
			name: "porridge",
			singular: "serving of porridge",
			plural: "servings of porridge",
			icon: "porridge.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 250,
			},
			recipe: {
				recipe_name: "porridge",
				difficulty: 1,
				cook_minutes: 5,
				servings: 1,
				ingredients: ["oats", "bottle_of_milk"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		turnip_soup: {
			index: 146,
			name: "turnip soup",
			singular: "serving of turnip soup",
			plural: "servings of turnip soup",
			icon: "turnip-soup.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 250,
			},
			recipe: {
				recipe_name: "turnip soup",
				difficulty: 1,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["turnip", "potato", "onion", "vegetable_oil", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegan"],
			},
		},
		pink_rose: {
			index: 147,
			name: "pink rose",
			singular: "pink rose",
			plural: "pink roses",
			icon: "pink-rose.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 14,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
			},
			shop: {
				sell_price: 400,
			},
		},
		valentines_chocolate: {
			index: 148,
			name: "valentines chocolate",
			singular: "slab of valentines chocolate",
			plural: "slabs of valentines chocolate",
			icon: "valentines-chocolate.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 900,
			},
			recipe: {
				recipe_name: "valentines chocolate",
				difficulty: 1,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["butter", "bottle_of_milk", "cocoa_powder", "pear"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		sunflower: {
			index: 149,
			name: "sunflower",
			singular: "sunflower",
			plural: "sunflowers",
			icon: "sunflower.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				planting_bed: "earth",
				growth_days: 7,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["summer"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 300,
			},
		},
		jammie_dodger: {
			index: 94,
			name: "jammie dodger",
			singular: "jammie dodger",
			plural: "jammie dodgers",
			icon: "jammie-dodger.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 80,
			},
			recipe: {
				recipe_name: "jammie dodgers",
				difficulty: 1,
				cook_minutes: 10,
				servings: 5,
				ingredients: ["flour", "sugar", "butter", "chicken_egg", "jam"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		jam: {
			index: 95,
			name: "jam",
			singular: "cup of jam",
			plural: "cups of jam",
			icon: "jam.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 200,
			},
			recipe: {
				recipe_name: "jam",
				difficulty: 1,
				cook_minutes: 5,
				servings: 1,
				ingredients: ["strawberry", "sugar"],
				tags: [],
			},
		},
		herring: {
			index: 152,
			name: "herring",
			singular: "herring",
			plural: "herring",
			icon: "herring.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 150,
			},
		},
		whiting: {
			index: 153,
			name: "whiting",
			singular: "whiting",
			plural: "whiting",
			icon: "whiting.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 300,
			},
		},
		mackerel: {
			index: 154,
			name: "mackerel",
			singular: "mackerel",
			plural: "mackerel",
			icon: "mackerel.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 200,
			},
		},
		flounder: {
			index: 155,
			name: "flounder",
			singular: "flounder",
			plural: "flounder",
			icon: "flounder.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 400,
			},
		},
		bass: {
			index: 156,
			name: "bass",
			singular: "bass",
			plural: "bass",
			icon: "bass.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 800,
			},
		},
		roach: {
			index: 157,
			name: "roach",
			singular: "roach",
			plural: "roach",
			icon: "roach.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 80,
			},
		},
		perch: {
			index: 158,
			name: "perch",
			singular: "perch",
			plural: "perch",
			icon: "perch.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 250,
			},
		},
		chub: {
			index: 159,
			name: "chub",
			singular: "chub",
			plural: "chub",
			icon: "chub.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 150,
			},
		},
		pike: {
			index: 160,
			name: "pike",
			singular: "pike",
			plural: "pike",
			icon: "pike.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 800,
			},
		},
		eel: {
			index: 162,
			name: "eel",
			singular: "eel",
			plural: "eels",
			icon: "eel.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 700,
			},
		},
		grayling: {
			index: 163,
			name: "grayling",
			singular: "grayling",
			plural: "grayling",
			icon: "grayling.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 900,
			},
		},
		baitfish: {
			index: 164,
			name: "baitfish",
			singular: "baitfish",
			plural: "baitfish",
			icon: "baitfish.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			is_fishing_bait: true,
			shop: {
				sell_price: 0,
			},
		},
		bait_worm: {
			index: 165,
			name: "bait worm",
			singular: "bait worm",
			plural: "bait worms",
			icon: "bait-worm.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			is_fishing_bait: true,
			shop: {
				sell_price: 0,
			},
		},
	};
	finalizefoodstuff();
}
window.initFoodstuff = initFoodstuff;
