function initFishingFishConfig() {
	setup.fishing = { lootTables: {} };
	setup.fishing.lootTables.fish = {
		haddock: {
			minSize: 35,
			maxSize: 90,
			preferredSeason: ["autumn"],
			preferredLocation: ["fishingPier"],
			locations: {
				fishingPier: 0.5,
				fishingCoastPath: 0.5,
			},
			cookable: true,
			minigame: {
				behavior: "runner",
				maxStamina: 6,
				armFatigueDifficulty: 2000,
			},
			icon: "fish/haddock.png",
			preferredBait: "apple",
		},
		salmon: {
			minSize: 45,
			maxSize: 120,
			preferredSeason: ["autumn"],
			preferredLocation: ["fishingForestLake", "fishingCoastPath", "fishingPier"],
			locations: {
				fishingPier: 1,
				fishingCoastPath: 1,
				fishingForestLake: 0.5,
			},
			cookable: true,
			minigame: {
				behavior: "panicked",
				maxStamina: 5,
				armFatigueDifficulty: 2000,
			},
			icon: "fish/salmon.png",
			preferredBait: "wild_carrot",
		},
		trout: {
			minSize: 25,
			maxSize: 80,
			preferredSeason: ["spring"],
			preferredLocation: ["fishingForestLake"],
			locations: {
				fishingForestLake: 1,
				fishingMoor: 1,
			},
			cookable: true,
			minigame: {
				behavior: "darter",
				maxStamina: 5,
				armFatigueDifficulty: 2900,
			},
			icon: "fish/trout.png",
			preferredBait: "onion",
		},
		herring: {
			minSize: 20,
			maxSize: 45,
			preferredSeason: ["autumn", "winter"],
			preferredLocation: ["fishingBeach", "fishingPier"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 0.5,
			},
			cookable: false,
			minigame: {
				behavior: "panicked",
				maxStamina: 4,
				armFatigueDifficulty: 1600,
			},
			icon: "fish/herring.png",
			preferredBait: "pear",
		},
		whiting: {
			minSize: 25,
			maxSize: 60,
			preferredSeason: ["winter"],
			preferredLocation: ["fishingPier", "fishingCoastPath"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 1,
			},
			cookable: false,
			minigame: {
				behavior: "runner",
				maxStamina: 4,
				armFatigueDifficulty: 1800,
			},
			icon: "fish/whiting.png",
			preferredBait: "potato",
		},
		mackerel: {
			minSize: 22,
			maxSize: 50,
			preferredSeason: ["summer"],
			preferredLocation: ["fishingBeach", "fishingCoastPath"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 1,
			},
			cookable: false,
			minigame: {
				behavior: "panicked",
				maxStamina: 4,
				armFatigueDifficulty: 1600,
			},
			icon: "fish/mackerel.png",
			preferredBait: "bread",
		},
		flounder: {
			minSize: 25,
			maxSize: 60,
			preferredSeason: ["spring", "summer"],
			preferredLocation: ["fishingBeach", "fishingCoastPath"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 1,
			},
			cookable: false,
			minigame: {
				behavior: "runner",
				maxStamina: 5,
				armFatigueDifficulty: 2000,
			},
			icon: "fish/flounder.png",
			preferredBait: "peach",
		},
		bass: {
			minSize: 35,
			maxSize: 95,
			preferredSeason: ["summer", "autumn"],
			preferredLocation: ["fishingPier", "fishingCoastPath"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 1,
			},
			cookable: true,
			minigame: {
				behavior: "darter",
				maxStamina: 6,
				armFatigueDifficulty: 2600,
			},
			icon: "fish/bass.png",
			preferredBait: "lemon",
		},
		roach: {
			minSize: 15,
			maxSize: 45,
			preferredSeason: ["spring", "summer"],
			preferredLocation: ["fishingForestLake", "fishingMoor"],
			locations: {
				fishingForestLake: 1,
				fishingMoor: 0.5,
			},
			cookable: false,
			minigame: {
				behavior: "darter",
				maxStamina: 4,
				armFatigueDifficulty: 1400,
			},
			icon: "fish/roach.png",
			preferredBait: "pepper",
		},
		perch: {
			minSize: 20,
			maxSize: 60,
			preferredSeason: ["autumn"],
			preferredLocation: ["fishingForestLake", "fishingMoor"],
			locations: {
				fishingForestLake: 1,
				fishingMoor: 1,
			},
			cookable: true,
			minigame: {
				behavior: "panicked",
				maxStamina: 4,
				armFatigueDifficulty: 2000,
			},
			icon: "fish/perch.png",
			preferredBait: "garlic_bulb",
		},
		chub: {
			minSize: 25,
			maxSize: 80,
			preferredSeason: ["summer", "autumn"],
			preferredLocation: ["fishingForestLake", "fishingMoor"],
			locations: {
				fishingForestLake: 0.5,
				fishingMoor: 0.25,
			},
			cookable: false,
			minigame: {
				behavior: "runner",
				maxStamina: 4,
				armFatigueDifficulty: 2000,
			},
			icon: "fish/chub.png",
			preferredBait: "strawberry",
		},
		grayling: {
			minSize: 45,
			maxSize: 60,
			preferredSeason: ["winter"],
			preferredLocation: ["fishingForestLake"],
			locations: {
				fishingForestLake: 0.25,
			},
			cookable: false,
			minigame: {
				behavior: "darter",
				maxStamina: 4,
				armFatigueDifficulty: 1800,
			},
			icon: "fish/grayling.png",
			preferredBait: "blackberry",
		},
		cod: {
			minSize: 55,
			maxSize: 140,
			preferredSeason: ["winter"],
			preferredLocation: ["fishingCoastPath"],
			locations: {
				fishingBeach: 0.5,
				fishingPier: 0.65,
				fishingCoastPath: 0.8,
			},
			requiresBaitFish: true,
			cookable: true,
			minigame: {
				behavior: "anchor",
				maxStamina: 3,
				armFatigueDifficulty: 2500,
			},
			icon: "fish/cod.png",
		},
		pike: {
			minSize: 45,
			maxSize: 130,
			preferredSeason: ["autumn", "winter"],
			preferredLocation: ["fishingForestLake", "fishingMoor"],
			locations: {
				fishingForestLake: 1,
			},
			requiresBaitFish: true,
			cookable: true,
			minigame: {
				behavior: "thrasher",
				maxStamina: 2,
				armFatigueDifficulty: 3000,
			},
			icon: "fish/pike.png",
		},
		eel: {
			minSize: 45,
			maxSize: 120,
			preferredSeason: ["summer", "autumn"],
			preferredLocation: ["fishingForestLake", "fishingMoor"],
			locations: {
				fishingMoor: 1,
			},
			requiresBaitFish: true,
			cookable: false,
			minigame: {
				behavior: "slipper",
				maxStamina: 3,
				armFatigueDifficulty: 2000,
			},
			icon: "fish/eel.png",
		},
		baitfish: {
			minSize: 4,
			maxSize: 14,
			preferredSeason: ["spring", "summer", "autumn", "winter"],
			preferredLocation: ["fishingForestLake", "fishingBeach"],
			locations: {
				fishingForestLake: 1,
				fishingBeach: 1,
			},
			cookable: false,
			icon: "fish/baitfish.png",
			isBaitFish: true,
			preferredBait: "bait_worm",
		},
	};

	setup.fishing.lootTables.fishingTrash = {
		boot: { weight: 1, isLitter: true },
		plasticBag: { weight: 1.5, isLitter: true },
		fishingLine: { weight: 1, isLitter: true },
		netting: { weight: 0.75, isLitter: true },
		tinCan: { weight: 1.25, isLitter: true },
		brokenBottle: { weight: 0.75, isLitter: true },
		leadSinkers: { weight: 0.75, isLitter: true },
		seaweed: { weight: 1.5, isLitter: false, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		conchShell: { weight: 0.75, isLitter: false, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		mussel: { weight: 1, isLitter: false, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		driedCrabShell: { weight: 0.75, isLitter: false, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		barnacledRope: { weight: 0.5, isLitter: false, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		pondweed: { weight: 1.5, isLitter: false, locations: ["fishingForestLake", "fishingMoor"] },
		duckweed: { weight: 1.25, isLitter: false, locations: ["fishingForestLake", "fishingMoor"] },
		rottingStick: { weight: 1, isLitter: false, locations: ["fishingForestLake", "fishingMoor"] },
		waterLilyPad: { weight: 0.5, isLitter: false, locations: ["fishingForestLake", "fishingMoor"] },
	};

	setup.fishing.lootTables.fishingClothing = {
		"bikini top": { weight: 1, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		"bikini bottoms": { weight: 1, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		"board shorts": { weight: 1, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		"swim shirt": { weight: 1, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		"school swim top": { weight: 0.5, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		"school swim bottoms": { weight: 0.5, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
	};
}
window.initFishingFishConfig = initFishingFishConfig;
