/* Create the sky canvas instance */
Weather.sidebar = new Weather.Renderer.Sky({
	id: "canvasSkybox",
	setup: setup.SkySettings.canvas.sidebar,
	layers: [
		"sky",
		"starField",
		"sun",
		"moon",
		"cirrusClouds",
		"overcastClouds",
		"clouds",
		"horizonGlow",
		"location",
		"precipitation",
		"lightningNear",
		"lightningMid",
		"lightningFar",
		"lightningExtra",
		"bloodGlow",
		"sunGlow",
		"fog",
		"locationSmoke",
	],
});
