// @ts-check
/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites.

Warmth checklist:
	Base: 0
	Normal: 0
	Thick: +2
	Very thick: +4

	Max warmth: 4
*/
function initNeck() {
	/** @type {ClothesItem[]} */
	const clothing = [
		new ClothesItem({
			index: 0,
			slot: "neck",
			name: "naked",
			name_cap: "Naked",
			variable: "naked",
			state: 0,
			state_base: 0,
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "벗었습니다.",
			shop: [],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		}),
		new ClothesItem({
			index: 1,
			slot: "neck",
			name: "collar",
			name_cap: "Collar",
			variable: "collar",
			combat: {
				reference: "clothchoker",
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 1000,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish"],
			gender: "n",
			warmth: 0,
			cost: 20000,
			description: "잠금을 해제하려면 특수 도구가 필요합니다.",
			shop: [],
			collared: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "collar.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 2,
			slot: "neck",
			name: "bunny collar",
			name_cap: "Bunny collar",
			variable: "bunnycollar",
			combat: {
				reference: "clothchoker",
				mainColour: "#000000",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["white", "custom"],
			colour_sidebar: 1,
			colour_combat: "white",
			type: ["costume", "serving"],
			gender: "n",
			warmth: 0,
			cost: 3000,
			description: "칼라와 타이. 토끼 의상 세트의 일부입니다.",
			shop: ["adult"],
			collared: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "bunny_collar.png",
			accIcon: "bunny_collar_acc.png",
		}),
		new ClothesItem({
			index: 3,
			slot: "neck",
			name: "holy pendant",
			name_cap: "Holy pendant",
			variable: "holypendant",
			combat: {
				reference: "naked",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "yellow",
			type: ["holy"],
			gender: "n",
			warmth: 0,
			cost: 1000,
			description: "무겁습니다. 착용 중이라는 사실을 잊지 않게 해줍니다.",
			shop: ["forest"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "holy-pendant.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 4,
			slot: "neck",
			name: "dark pendant",
			name_cap: "Dark pendant",
			variable: "darkpendant",
			combat: {
				reference: "naked",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["dark"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "모든 빛을 흡수합니다.",
			shop: ["forest"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "dark_pendant.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 5,
			slot: "neck",
			name: "stone pendant",
			name_cap: "Stone pendant",
			variable: "stonependant",
			combat: {
				reference: "naked",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["holy"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "소박한 끈에 매달린 오래된 성스러운 상징입니다.",
			shop: ["forest"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "stone-pendant.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 6,
			slot: "neck",
			name: "gold choker",
			name_cap: "Gold choker",
			variable: "goldchoker",
			combat: {
				reference: "clothchoker",
				mainColour: "#d8b608",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "serving"],
			gender: "n",
			warmth: 0,
			cost: 25000,
			description: "이국적이고 눈길을 끕니다.",
			shop: ["adult"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "gold_choker.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 7,
			slot: "neck",
			name: "cat bell collar",
			name_cap: "Cat bell collar",
			variable: "cat",
			combat: {
				reference: "cow",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "red",
			type: ["costume", "serving", "unstealthy", "eerie"],
			gender: "n",
			warmth: 0,
			cost: 1500,
			description: "딸랑거립니다.",
			shop: ["clothing", "adult"],
			collared: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["gold", "silver", "rose gold", "bronze"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "cat_bell_collar.png",
			accIcon: "cat_bell_collar_acc.png",
		}),
		new ClothesItem({
			index: 8,
			slot: "neck",
			name: "cow bell",
			name_cap: "Cow bell",
			variable: "cow",
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "brown", "light pink", "light blue", "light green", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume", "eerie", "unstealthy"],
			gender: "n",
			warmth: 0,
			cost: 1500,
			description: "덜렁거립니다.",
			shop: ["forest"],
			collared: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["gold", "silver", "rose gold", "bronze", "steel", "blue steel"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "cow_bell.png",
			accIcon: "cow_bell_acc.png",
		}),
		new ClothesItem({
			index: 9,
			slot: "neck",
			name: "lace choker",
			name_cap: "Lace choker",
			variable: "lacechoker",
			combat: {
				reference: "clothchoker",
			},
			state: 0,
			state_base: 0,
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["formal"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 1800,
			description: "매혹적입니다.",
			shop: ["clothing", "adult"],
			shopGroup: "lacechoker",
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "lace_choker.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 10,
			slot: "neck",
			name: "spiked collar",
			name_cap: "Spiked collar",
			variable: "spiked",
			combat: {
				reference: "clothchoker",
				mainColour: "#000000",
			},
			state: 0,
			state_base: 0,
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["fetish", "costume", "eerie"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 1500,
			description: "강철 스파이크가 위협적입니다.",
			shop: ["clothing", "adult"],
			collared: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "spiked_collar.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 11,
			slot: "neck",
			name: "heart choker",
			name_cap: "Heart choker",
			variable: "heartchoker",
			combat: {
				reference: "clothchoker",
				mainColour: "#000000",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 2100,
			description: "귀엽습니다.",
			shop: ["clothing", "adult"],
			collared: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["red", "pink", "lilac", "purple", "light pink", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "heart_choker.png",
			accIcon: "heart_choker_acc.png",
		}),
		new ClothesItem({
			index: 12,
			slot: "neck",
			name: "ringed collar",
			name_cap: "Ringed collar",
			variable: "ringedcollar",
			combat: {
				reference: "clothchoker",
				mainColour: "#000000",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["fetish"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 2500,
			description: "목줄을 걸 수 있게 되어 있습니다.",
			shop: ["clothing", "adult"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "ringed_collar.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 13,
			slot: "neck",
			name: "necktie",
			name_cap: "Necktie",
			variable: "tie",
			combat: {
				accessory: false,
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "m",
			femininity: -100,
			warmth: 0,
			cost: 3000,
			description: "사무직 직장인을 위한 클래식 액세서리입니다.",
			shop: ["clothing", "adult"],
			collared: 0,
			has_collar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			altposition: "none",
			altdisabled: [],
			iconFile: "necktie.png",
			accIcon: "necktie_acc.png",
		}),
		new ClothesItem({
			index: 14,
			slot: "neck",
			name: "suspenders",
			name_cap: "Suspenders",
			variable: "suspenders",
			combat: {
				reference: "naked",
				accessory: false,
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 0,
			cost: 2000,
			description: "바지를 고정해줍니다.",
			shop: ["clothing", "adult"],
			collared: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["steel", "blue steel", "bronze", "gold", "rose gold", "silver"],
			accessory_colour_sidebar: 1,
			mask_img: 1,
			cursed: 0,
			location: 0,
			iconFile: "suspenders.png",
			accIcon: 0,
			altposition: "none",
			altdisabled: [],
		}),
		new ClothesItem({
			index: 15,
			slot: "neck",
			name: "cloth choker",
			name_cap: "Cloth choker",
			variable: "clothchoker",
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 1500,
			description: "개성이 넘칩니다.",
			shop: ["clothing", "adult"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "cloth_choker.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 16,
			slot: "neck",
			name: "scarf",
			name_cap: "Scarf",
			variable: "scarf",
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [
				"black",
				"navy blue",
				"blue",
				"neon blue",
				"wine",
				"brown",
				"green",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 4,
			cost: 1200,
			description: "포근합니다.",
			shop: ["clothing"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "scarf.png",
			accIcon: 0,
			zIndex: "head",
		}),
		new ClothesItem({
			index: 17,
			slot: "neck",
			name: "gold chain",
			name_cap: "Gold chain",
			variable: "chaingold",
			combat: {
				reference: "clothchoker",
				mainColour: "#d8b608",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 500,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 0,
			cost: 11000,
			description: "호화로운 남성용 장신구입니다.",
			shop: ["clothing", "adult"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "gold_chain.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 18,
			slot: "neck",
			name: "iron chain",
			name_cap: "Iron chain",
			variable: "chainiron",
			combat: {
				reference: "clothchoker",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 1000,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 0,
			cost: 300,
			description: "남성용 장신구입니다.",
			shop: ["clothing", "adult"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "iron_chain.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 19,
			slot: "neck",
			name: "holy stole",
			name_cap: "Holy stole",
			variable: "holystole",
			combat: {
				reference: "naked",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 100,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "wine", "forest green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["holy"],
			gender: "n",
			femininity: 0,
			warmth: 2,
			cost: 10000,
			description: "성직자 복장입니다.",
			shop: ["forest"],
			shopGroup: "holystole",
			collared: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "holy_stole.png",
			accIcon: "holy_stole_acc.png",
		}),
		new ClothesItem({
			index: 20,
			slot: "neck",
			name: "free use collar",
			name_cap: "Free use collar",
			variable: "freeuse",
			combat: {
				reference: "clothchoker",
				mainColour: "#b59a51",
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 1000,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "잠금을 해제하려면 특수 도구가 필요합니다.",
			shop: [],
			collared: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "collar.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 21,
			slot: "neck",
			name: "collar with leash",
			name_cap: "Collar with leash",
			variable: "collarleash",
			combat: {
				reference: "clothchoker",
				mainColour: "#000000",
				accessory: false,
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 1000,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "leash"],
			gender: "n",
			warmth: 0,
			cost: 20000,
			description: "잠금을 해제하려면 특수 도구가 필요합니다.",
			shop: [],
			collared: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "collar.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 22,
			slot: "neck",
			name: "free use collar with leash",
			name_cap: "Free use collar with leash",
			variable: "freeuseleash",
			combat: {
				reference: "clothchoker",
				mainColour: "#b59a51",
				accessory: false,
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 1000,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "leash"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "잠금을 해제하려면 특수 도구가 필요합니다.",
			shop: [],
			collared: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "collar.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 23,
			slot: "neck",
			name: "ivory necklace",
			name_cap: "Ivory necklace",
			variable: "ivorynecklace",
			combat: {
				reference: "naked",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 100,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["holy", "dark", "eerie", "esoteric"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 200000,
			description: "고대 교단의 고위 인사가 착용했던 신성한 유물입니다. 보석에 모습이 비칩니다. 창백해 보입니다.",
			shop: [],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "ivory_necklace.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 24,
			slot: "neck",
			name: "leather collar with leash",
			name_cap: "Leather collar with leash",
			variable: "collarleashfetish",
			combat: {
				reference: "clothchoker",
				accessory: false,
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 1000,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "leash"],
			gender: "n",
			warmth: 0,
			cost: 24000,
			description: "잠금을 해제하려면 특수 도구가 필요하지만, 열쇠는 가지고 있습니다.",
			shop: ["adult"],
			collared: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "collar.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 25,
			slot: "neck",
			name: "leather collar",
			name_cap: "Leather collar",
			variable: "collarfetish",
			combat: {
				reference: "clothchoker",
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 1000,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish"],
			gender: "n",
			warmth: 0,
			cost: 20000,
			description: "잠금을 해제하려면 특수 도구가 필요하지만, 열쇠는 가지고 있습니다.",
			shop: ["adult"],
			collared: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "collar_no_leash.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 26,
			slot: "neck",
			name: "spiked collar with leash",
			name_cap: "Spiked collar with leash",
			variable: "spikedleash",
			combat: {
				reference: "clothchoker",
				mainColour: "#000000",
				accessory: false,
			},
			state: 0,
			state_base: 0,
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["fetish", "costume", "eerie", "leash"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 1500,
			description: "강철 스파이크가 위협적입니다.",
			shop: ["clothing"],
			collared: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "spiked_collar.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 27,
			slot: "neck",
			name: "short tie",
			name_cap: "Short tie",
			variable: "shorttie",
			combat: {
				reference: "tie",
				accessory: false,
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "m",
			femininity: -100,
			warmth: 0,
			cost: 3000,
			description: "단정하고 세련되었습니다.",
			shop: ["clothing", "adult"],
			collared: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "necktie.png",
			accIcon: "necktie_acc.png",
		}),
		new ClothesItem({
			index: 28,
			slot: "neck",
			name: "fur boa",
			name_cap: "Fur boa",
			variable: "boa",
			combat: {
				reference: "scarf",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [
				"black",
				"navy blue",
				"wine",
				"blue",
				"brown",
				"green",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 4,
			cost: 3000,
			description: "부드럽고 스타일리시합니다.",
			shop: ["clothing"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "boa.png",
		}),
		new ClothesItem({
			index: 29,
			slot: "neck",
			name: "sailor ribbon",
			name_cap: "Sailor ribbon",
			variable: "serafuku ribbon",
			combat: {
				reference: "tie",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 0,
			cost: 1000,
			description: "선원과 여학생 사이에서 흔히 보이는 스타일입니다.",
			shop: ["forest", "school"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "serafuku_ribbon.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 30,
			slot: "neck",
			name: "love locket",
			name_cap: "Love locket",
			variable: "lovelocket",
			combat: {
				reference: "clothchoker",
			},
			state: 0,
			state_base: 0,
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 300,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["bronze", "gold", "rose gold", "silver"],
			colour_sidebar: 1,
			colour_combat: "gold",
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 3500,
			description: "열면 사진을 넣을 공간이 나옵니다. 거울에서 꾸밀 수 있습니다.",
			shop: ["clothing"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "love_locket.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 31,
			slot: "neck",
			name: "classic lace choker",
			name_cap: "Classic lace choker",
			variable: "lacechokerold",
			combat: {
				reference: "clothchoker",
			},
			state: 0,
			state_base: 0,
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["formal"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 1800,
			description: "매혹적입니다.",
			shop: ["clothing", "adult"],
			shopGroup: "lacechoker",
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "lace_choker.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 32,
			slot: "neck",
			name: "bowtie",
			name_cap: "Bowtie",
			variable: "bowtie",
			combat: {
				reference: "clothchoker",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "navy blue", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "m",
			femininity: -100,
			warmth: 0,
			cost: 3000,
			description: "사무직 직장인을 위한 클래식 액세서리입니다.",
			shop: ["clothing", "adult"],
			collared: 0,
			has_collar: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "bowtie.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 33,
			slot: "neck",
			name: "ribbon tie",
			name_cap: "Ribbon tie",
			variable: "ribbontie",
			combat: {
				reference: "tie",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [
				"black",
				"blue",
				"brown",
				"green",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 3000,
			description: "사무직 직장인을 위한 클래식 액세서리입니다.",
			shop: ["clothing", "adult"],
			collared: 0,
			has_collar: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "ribbon_tie.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 34,
			slot: "neck",
			name: "whistle",
			name_cap: "Whistle",
			variable: "whistle",
			combat: {
				reference: "naked",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 300,
			description: "호신용 호루라기로는 효과가 없습니다.",
			shop: ["clothing", "baitShop"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "whistle.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 35,
			slot: "neck",
			name: "large ribbon tie",
			name_cap: "Large ribbon tie",
			variable: "ribbontielarge",
			combat: {
				reference: "tie",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [
				"black",
				"blue",
				"brown",
				"green",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 3500,
			description: "미리 매듭이 지어져 있습니다.",
			shop: ["clothing"],
			collared: 0,
			has_collar: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "large_ribbon_tie.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 36,
			slot: "neck",
			name: "bolo tie",
			name_cap: "Bolo tie",
			variable: "bolotie",
			combat: {
				reference: "clothchoker",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "white", "brown", "sand", "tan", "olive", "russet", "custom"],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "m",
			femininity: -100,
			warmth: 0,
			cost: 1500,
			description: "별납니다.",
			shop: ["clothing"],
			collared: 0,
			has_collar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["steel", "blue steel", "bronze", "gold", "rose gold", "silver"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "bolo_tie.png",
			accIcon: "bolo_tie_acc.png",
		}),
		new ClothesItem({
			index: 37,
			slot: "neck",
			name: "long holy stole",
			name_cap: "Long holy stole",
			variable: "holystolelong",
			combat: {
				reference: "naked",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 100,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "wine", "forest green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["holy"],
			gender: "n",
			femininity: 0,
			warmth: 2,
			cost: 10000,
			description: "성직자 복장입니다.",
			shop: ["forest"],
			shopGroup: "holystole",
			collared: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "holy_stole.png",
			accIcon: "holy_stole_acc.png",
		}),
		new ClothesItem({
			index: 38,
			slot: "neck",
			name: "feather necklace",
			name_cap: "Feather necklace",
			variable: "feathernecklace",
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 50,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume", "eerie"],
			gender: "n",
			warmth: 0,
			cost: 1500,
			description: "진짜 깃털로 만들었습니다.",
			shop: ["forest"],
			collared: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "feather_necklace.png",
			accIcon: "feather_necklace_acc.png",
		}),
		new ClothesItem({
			index: 39,
			slot: "neck",
			name: "jasper pendant",
			name_cap: "Jasper pendant",
			variable: "jasperpendant",
			combat: {
				reference: "naked",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 50,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "red",
			type: ["eerie"],
			gender: "n",
			warmth: 0,
			cost: 3300,
			description: "현지에서 수작업으로 제작되었습니다. 무엇을 닮았다고도 할 수 있는 모양이지만, 여우 꼬리나 수탉이 떠오릅니다.",
			shop: ["forest"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "jasper_pendant.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 40,
			slot: "neck",
			name: "familiar collar",
			name_cap: "Familiar collar",
			variable: "collarfamiliar",
			combat: {
				reference: "clothchoker",
				mainColour: "#374f2f",
				accessory: false,
			},
			state: 0,
			state_base: 0,
			integrity: 1000,
			integrity_max: 1000,
			fabric_strength: 1000,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "forest-green",
			type: ["eerie", "curious", "enchanting"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 0,
			description: "손으로 짰고, 당신의 이름과 함께 룬 문자가 새겨져 있습니다. 손에 쥐면 찌릿합니다.",
			shop: ["forest"],
			collared: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "familiar_collar.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 41,
			slot: "neck",
			name: "wool scarf",
			name_cap: "Wool scarf",
			variable: "woolscarf",
			combat: {
				reference: "scarf",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 5,
			cost: 12000,
			description: "두껍고 양모로 만들어졌습니다.",
			shop: ["clothing"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "woolscarf.png",
			accIcon: 0,
			zIndex: "head",
		}),
		new ClothesItem({
			index: 42,
			slot: "neck",
			name: "flannel scarf",
			name_cap: "Flannel scarf",
			variable: "flannelscarf",
			combat: {
				reference: "scarf",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "wine", "forest green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 4,
			cost: 4500,
			description: "두껍고 양모로 만들어졌습니다.",
			shop: ["clothing"],
			collared: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "wine", "forest green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "flannelscarf.png",
			accIcon: "flannelscarf_acc.png",
			zIndex: "head",
		}),
		new ClothesItem({
			index: 43,
			slot: "neck",
			name: "fox scarf",
			name_cap: "Fox scarf",
			variable: "foxscarf",
			combat: {
				reference: "scarf",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["tangerine", "forest green", "brown", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 5,
			cost: 4500,
			description: "이 스카프를 만드는 과정에서 다친 여우는 없습니다.",
			shop: ["clothing"],
			collared: 0,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "foxscarf.png",
			accIcon: "foxscarf_acc.png",
			zIndex: "head",
		}),
		new ClothesItem({
			index: 44,
			slot: "neck",
			name: "pompom scarf",
			name_cap: "Pompom scarf",
			variable: "pompomscarf",
			combat: {
				reference: "scarf",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 4,
			cost: 2500,
			description: "정말 푹신합니다.",
			shop: ["clothing"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "pompomscarf.png",
			accIcon: 0,
			zIndex: "head",
		}),
		new ClothesItem({
			index: 45,
			slot: "neck",
			name: "ribbon scarf",
			name_cap: "Ribbon scarf",
			variable: "ribbonscarf",
			combat: {
				reference: "scarf",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [
				"black",
				"navy blue",
				"wine",
				"brown",
				"olive",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 4,
			cost: 5500,
			description: "귀엽고 포근합니다.",
			shop: ["clothing"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "ribbonscarf.png",
			accIcon: 0,
			zIndex: "head",
		}),
		new ClothesItem({
			index: 46,
			slot: "neck",
			name: "cashmere scarf",
			name_cap: "Cashmere scarf",
			variable: "cashmerescarf",
			combat: {
				reference: "scarf",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [
				"black",
				"navy blue",
				"wine",
				"brown",
				"olive",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 5,
			cost: 12000,
			description: "귀엽고 포근합니다.",
			shop: ["clothing"],
			collared: 0,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "cashmerescarf.png",
			accIcon: 0,
			zIndex: "head",
		}),
		new ClothesItem({
			index: 47,
			slot: "neck",
			name: "bow brooch",
			name_cap: "Bow brooch",
			variable: "bow brooch",
			description: "핀으로 고정하는 리본입니다.",
			cost: 10000,
			shop: ["clothing"],
			type: ["normal", "formal"],
			combat: {
				reference: "clothchoker",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [
				"black",
				"navy blue",
				"wine",
				"brown",
				"olive",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [
				"black",
				"navy blue",
				"wine",
				"brown",
				"olive",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			accessory_colour_sidebar: 1,
			gender: "n",
			warmth: 0,
			cursed: 0,
			location: 0,
			iconFile: "bow-brooch.png",
			accIcon: "bow-brooch-acc.png",
		}),
		new ClothesItem({
			index: 48,
			slot: "neck",
			name: "gothic choker",
			name_cap: "Gothic choker",
			variable: "gothic choker",
			description: "프릴이 달린 초커입니다.",
			cost: 4000,
			shop: ["clothing"],
			type: ["normal", "formal", "costume"],
			combat: {
				reference: "clothchoker",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [
				"black",
				"navy blue",
				"wine",
				"brown",
				"olive",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [
				"black",
				"navy blue",
				"wine",
				"brown",
				"olive",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			accessory_colour_sidebar: 1,
			gender: "n",
			warmth: 0,
			cursed: 0,
			location: 0,
			iconFile: "gothic-choker.png",
			accIcon: "gothic-choker-acc.png",
		}),
		new ClothesItem({
			index: 49,
			slot: "neck",
			name: "kitty neck cushion",
			name_cap: "Kitty neck cushion",
			variable: "kitty neck cushion",
			description: "목을 감싸는 고양이 모양 베개입니다.",
			cost: 6500,
			shop: ["clothing"],
			type: ["normal", "sleep"],
			combat: {
				reference: "scarf",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 100,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [
				"black",
				"navy blue",
				"wine",
				"brown",
				"olive",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_sidebar: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			gender: "n",
			warmth: 2,
			shopGroup: "animal neck cushion",
			cursed: 0,
			location: 0,
			iconFile: "kitty-neck-cushion.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 50,
			slot: "neck",
			name: "puppy neck cushion",
			name_cap: "Puppy neck cushion",
			variable: "puppy neck cushion",
			description: "목을 감싸는 강아지 모양 베개입니다.",
			cost: 6500,
			shop: ["clothing"],
			type: ["normal", "sleep"],
			combat: {
				reference: "scarf",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [
				"black",
				"navy blue",
				"wine",
				"brown",
				"olive",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_sidebar: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			gender: "n",
			warmth: 2,
			shopGroup: "animal neck cushion",
			cursed: 0,
			location: 0,
			iconFile: "puppy-neck-cushion.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 51,
			slot: "neck",
			name: "gemstone necklace",
			name_cap: "Gemstone necklace",
			variable: "gemstone necklace",
			description: "섬세한 장신구입니다.",
			cost: 45000,
			shop: ["clothing"],
			type: ["formal"],
			combat: {
				reference: "clothchoker",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["gold", "silver", "rose gold", "bronze"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [
				"black",
				"navy blue",
				"wine",
				"brown",
				"olive",
				"pink",
				"light pink",
				"purple",
				"lilac",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			accessory_colour_sidebar: 1,
			gender: "n",
			warmth: 0,
			cursed: 0,
			location: 0,
			iconFile: "gemstone necklace.png",
			accIcon: "gemstone necklace-acc.png",
		}),
	];
	setup.clothes.neck = clothing;

	/*
		Clothes that modders add go into this array. This should be empty in the base game at all times.
		These items should have a `modder` variable with the modder's name in a short string.
	*/
	setup.moddedClothes.neck = [];

	setup.moddedClothes.neck.forEach((x, i) => (x.index = setup.clothes.neck.length + i));
	setup.clothes.neck.push(...setup.moddedClothes.neck);
}
window.initNeck = initNeck;
