// @ts-check
/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites.

Warmth checklist:
	Base: 0
	Covers mouth: +1
	Covers eyes: +1

	Materials
	Thin: -1
	Normal: 0
	Thick: +1

	Max warmth: 3
*/
function initFace() {
	/** @type {ClothesItem[]} */
	const clothing = [
		new ClothesItem({
			index: 0,
			slot: "face",
			name: "naked",
			name_cap: "Naked",
			variable: "naked",
			state: 0,
			state_base: 0,
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "벗었습니다.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		}),
		new ClothesItem({
			index: 1,
			slot: "face",
			name: "glasses",
			name_cap: "Glasses",
			variable: "glasses",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "light blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "silver", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "공부를 더 쉽게 해주지만, 학교에서 괴롭힘당할 수 있습니다.",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "glasses.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 2,
			slot: "face",
			name: "cool shades",
			name_cap: "Cool shades",
			variable: "coolshades",
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "학교에서 지위가 더 빨리 오르게 합니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "cool_shades.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 3,
			slot: "face",
			name: "surgical mask",
			name_cap: "Surgical mask",
			variable: "surgicalmask",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["mask", "face_covering"],
			gender: "n",
			warmth: 1,
			cost: 2000,
			description: "당신의 신원을 숨겨줍니다.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "surgical_mask.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 4,
			slot: "face",
			name: "gag",
			name_cap: "Gag",
			variable: "gag",
			combat: {
				accessory: true,
				mainColour: "#ff0000",
			},
			integrity: 20,
			state: 0,
			state_base: 0,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "입을 다물게 합니다.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 5,
			slot: "face",
			name: "blindfold",
			name_cap: "Blindfold",
			variable: "blindfold",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "blindfold"],
			gender: "n",
			warmth: 1,
			cost: 2000,
			description: "당신을 어둠 속에 있게 합니다.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 6,
			slot: "face",
			name: "gag and blindfold",
			name_cap: "Gag and blindfold",
			variable: "gagblindfold",
			combat: {
				accessory: true,
				mainColour: "#ff0000",
			},
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1000,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag", "blindfold"],
			gender: "n",
			warmth: 1,
			cost: 3000,
			description: "입을 다물게 하고 눈을 가립니다.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 7,
			slot: "face",
			name: "skulduggery mask",
			name_cap: "Skulduggery mask",
			variable: "skulmask",
			combat: {
				mainColour: "#333333",
			},
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["mask", "stealthy"],
			gender: "n",
			warmth: 1,
			cost: 23000,
			description: "나쁜 짓을 하려는 사람들을 위한 것입니다.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "skulduggery_mask.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 8,
			slot: "face",
			name: "low frame glasses",
			name_cap: "Low frame glasses",
			variable: "lowframe",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "공부를 더 쉽게 해주지만, 학교에서 괴롭힘당할 수 있습니다.",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "low_frame_glasses.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 9,
			slot: "face",
			name: "half moon glasses",
			name_cap: "Half moon glasses",
			variable: "halfmoon",
			combat: {
				accessory: false,
			},
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "공부를 더 쉽게 해주지만, 학교에서 괴롭힘당할 수 있습니다.",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "half_moon_glasses.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 10,
			slot: "face",
			name: "deep frame glasses",
			name_cap: "Deep frame glasses",
			variable: "deepframe",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "공부를 더 쉽게 해주지만, 학교에서 괴롭힘당할 수 있습니다.",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "deep_frame_glasses.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 11,
			slot: "face",
			name: "square shades",
			name_cap: "Square shades",
			variable: "square",
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "학교에서 지위가 더 빨리 오르게 합니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "square_shades.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 12,
			slot: "face",
			name: "round shades",
			name_cap: "Round shades",
			variable: "round",
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "학교에서 지위가 더 빨리 오르게 합니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "round_shades.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 13,
			slot: "face",
			name: "shield shades",
			name_cap: "Shield shades",
			variable: "shield",
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "학교에서 지위가 더 빨리 오르게 합니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "shield_shades.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 14,
			slot: "face",
			name: "cat eye shades",
			name_cap: "Cat eye shades",
			variable: "cateye",
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "학교에서 지위가 더 빨리 오르게 합니다.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "cat_eye_shades.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 15,
			slot: "face",
			name: "aviators",
			name_cap: "Aviators",
			variable: "aviator",
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["grey", "steel", "blue steel", "bronze", "gold", "silver", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "학교에서 지위가 더 빨리 오르게 합니다.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "aviators.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 16,
			slot: "face",
			name: "punk shades",
			name_cap: "Punk shades",
			variable: "punk",
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 3500,
			description: "학교에서 지위가 더 빨리 오르게 합니다.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "punk_shades.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 17,
			slot: "face",
			name: "muzzle",
			name_cap: "Muzzle",
			variable: "muzzle",
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["gag"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "입을 다물게 해 보호합니다.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 18,
			slot: "face",
			name: "mummy facewrap",
			name_cap: "Mummy facewrap",
			variable: "mummy",
			state: 0,
			state_base: 0,
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 1,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "white",
			type: ["costume", "mask", "face_covering"],
			gender: "n",
			warmth: 1,
			cost: 500,
			description: "화장지로 만든 것 같습니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "mummy_facewrap.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 19,
			slot: "face",
			name: "swimming goggles",
			name_cap: "Swimming goggles",
			variable: "swimgoggles",
			state: 0,
			state_base: 0,
			integrity: 70,
			integrity_max: 70,
			fabric_strength: 25,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["swim", "diving"],
			gender: "n",
			warmth: 1,
			cost: 1500,
			description: "물속에서 시야를 확보하기 위한 것입니다.",
			shop: ["clothing", "baitShop"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "swimming_goggles.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 20,
			slot: "face",
			name: "belly dancer's veil",
			name_cap: "Belly dancer's veil",
			variable: "belly",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["dance"],
			gender: "n",
			warmth: 0,
			cost: 8000,
			description: "이국적이고 매혹적입니다.",
			shop: ["forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "belly_dancers_veil.png",
			accIcon: "belly_dancers_veil_acc.png",
		}),
		new ClothesItem({
			index: 21,
			slot: "face",
			name: "muzzle",
			name_cap: "Muzzle",
			variable: "muzzlefetish",
			combat: {
				reference: "muzzle",
			},
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["grey", "black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["gag", "fetish", "face_covering"],
			gender: "n",
			warmth: 0,
			cost: 12000,
			description: "입을 다물게 해 보호합니다.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "muzzle.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 22,
			slot: "face",
			name: "gag",
			name_cap: "Gag",
			variable: "gagfetish",
			combat: {
				reference: "gag",
			},
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 8000,
			description: "입을 다물게 합니다.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "gag.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 23,
			slot: "face",
			name: "bit gag",
			name_cap: "Bit gag",
			variable: "bitgag",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "입을 다물게 합니다.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "bit_gag.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 24,
			slot: "face",
			name: "wolf muzzle",
			name_cap: "Wolf muzzle",
			variable: "wolfmuzzle",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 1,
			cost: 8000,
			description: "입을 다물게 합니다.",
			shop: [],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "wolf_muzzle.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 25,
			slot: "face",
			name: "kitty muzzle",
			name_cap: "Kitty muzzle",
			variable: "kittymuzzle",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 1,
			cost: 8000,
			description: "입을 다물게 합니다.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "kitty_muzzle.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 26,
			slot: "face",
			name: "cloth gag",
			name_cap: "Cloth gag",
			variable: "clothgag",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 1,
			cost: 500,
			description: "입을 다물게 합니다.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "cloth_gag.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 27,
			slot: "face",
			name: "panty gag",
			name_cap: "Panty gag",
			variable: "pantygag",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 500,
			description: "입을 다물게 합니다.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "panty_gag.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 28,
			slot: "face",
			name: "tape gag",
			name_cap: "Tape gag",
			variable: "tapegag",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 500,
			description: "입을 다물게 합니다.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "tape_gag.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 29,
			slot: "face",
			name: "penis gag",
			name_cap: "Penis gag",
			variable: "penisgag",
			combat: {
				mainColour: "#ff0000",
			},
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 4500,
			description: "입을 채워둡니다.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "penis_gag.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 30,
			slot: "face",
			name: "skeleton mask",
			name_cap: "Skeleton mask",
			variable: "skele",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "mask"],
			gender: "n",
			warmth: 1,
			cost: 2500,
			description: "따질 게 있을 때를 위한 것입니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "skeleton_mask.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 31,
			slot: "face",
			name: "esoteric spectacles",
			name_cap: "Esoteric spectacles",
			variable: "esoteric",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["glasses", "esoteric"],
			gender: "n",
			warmth: 0,
			cost: 50000,
			description: "물담배 장인의 안경입니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "esoteric_spectacles.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 32,
			slot: "face",
			name: "gas mask",
			name_cap: "Gas mask",
			variable: "gasmask",
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 25,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "brown", "tan", "olive", "sand", "grey", "white", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["mask", "face_covering", "costume"],
			gender: "n",
			warmth: 3,
			cost: 20000,
			description: "신원을 숨겨주지만, 이상한 시선을 받을 수 있습니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "gas_mask.png",
			accIcon: "gas_mask_acc.png",
		}),
		new ClothesItem({
			index: 33,
			slot: "face",
			name: "eyepatch",
			name_cap: "Eyepatch",
			variable: "eyepatch",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 0,
			cost: 1000,
			description: "망망대해를 항해하기 위한 것입니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "eyepatch.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 34,
			slot: "face",
			name: "medical eyepatch",
			name_cap: "Medical eyepatch",
			variable: "medical eyepatch",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "white", "grey", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 0,
			cost: 1000,
			description: "비상시를 대비한 물건입니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "medical_eyepatch.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 35,
			slot: "face",
			name: "doggy muzzle",
			name_cap: "Doggy muzzle",
			variable: "doggymuzzle",
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["gag", "fetish", "face_covering"],
			gender: "n",
			warmth: 1,
			cost: 16000,
			description: "당신의 입을 다물게 해 보호합니다.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "doggy-muzzle.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 36,
			slot: "face",
			name: "wood muzzle",
			name_cap: "Wood muzzle",
			variable: "wood muzzle",
			combat: {
				reference: "bitgag",
			},
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["gag", "fetish", "face_covering"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "당신의 입을 다물게 해 보호합니다.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "wood-muzzle.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 37,
			slot: "face",
			name: "monocle",
			name_cap: "Monocle",
			variable: "monocle",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "grey", "steel", "blue steel", "bronze", "gold", "silver"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["glasses", "formal"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "공부를 더 쉽게 만들어주지만, 학교에서 놀림받을 수도 있습니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "monocle.png",
			accIcon: "monocle_acc.png",
		}),
		new ClothesItem({
			index: 38,
			slot: "face",
			name: "islander mask",
			name_cap: "Islander mask",
			variable: "islandermask",
			state: 0,
			state_base: 0,
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["mask", "face_covering", "costume"],
			colour_combat: 0,
			gender: "n",
			warmth: 2,
			cost: 5000,
			description: "섬 주민들이 쓰는 가면입니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "islander-mask.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 39,
			slot: "face",
			name: "reading glasses",
			name_cap: "Reading glasses",
			variable: "reading",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "light blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "silver", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "공부를 더 쉽게 만들어주지만, 학교에서 놀림받을 수도 있습니다.",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "reading_glasses.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 40,
			slot: "face",
			name: "bandanna",
			name_cap: "Bandanna",
			variable: "bandanna",
			state: 0,
			state_base: 0,
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "light blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "silver", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["mask", "face_covering"],
			gender: "n",
			warmth: 1,
			cost: 500,
			description: "당신의 정체를 숨겨줍니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "bandanna.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 41,
			slot: "face",
			name: "heart sunglasses",
			name_cap: "Heart sunglasses",
			variable: "heartsunglasses",
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "neon blue", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "학교에서 지위가 더 빨리 오르게 합니다.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [
				"light pink",
				"lilac",
				"olive",
				"gold",
				"black",
				"blue",
				"brown",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"neon blue",
				"custom",
			],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "heart_sunglasses.png",
			accIcon: "heart_sunglasses_acc.png",
		}),
		new ClothesItem({
			index: 42,
			slot: "face",
			name: "fox mask",
			name_cap: "Fox mask",
			variable: "foxmask",
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["mask", "stealthy", "costume"],
			gender: "n",
			warmth: 1,
			cost: 23000,
			description: "엘크의 곡조에 맞춰 춤을 춥니다.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "fox-mask.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 43,
			slot: "face",
			name: "futuristic shades",
			name_cap: "Futuristic shades",
			variable: "futureshades",
			combat: {
				reference: "coolshades",
			},
			state: 0,
			state_base: 0,
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool", "costume"],
			gender: "n",
			warmth: 0,
			cost: 4000,
			description: "매끈하고 로봇 같습니다.",
			shop: ["forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "futureshades.png",
			accIcon: "futureshades_acc.png",
		}),
		new ClothesItem({
			index: 44,
			slot: "face",
			name: "plaster",
			name_cap: "Plaster",
			variable: "plaster",
			state: 0,
			state_base: 0,
			integrity: 5,
			integrity_max: 5,
			fabric_strength: 1,
			reveal: 1,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 0,
			cost: 500,
			description: "긁힌 상처에 아주 좋습니다.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "plaster.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 45,
			slot: "face",
			name: "butterfly eyepatch",
			name_cap: "Butterfly eyepatch",
			variable: "butterfly eyepatch",
			combat: {
				reference: "eyepatch",
			},
			description: "섬세한 손길.",
			cost: 7000,
			shop: ["forest"],
			type: ["formal", "serving", "costume"],
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			gender: "n",
			warmth: 0,
			cursed: 0,
			location: 0,
			iconFile: "butterfly-eyepatch.png",
			accIcon: "butterfly-eyepatch-acc.png",
			altposition: "none",
			altdisabled: [],
		}),
		new ClothesItem({
			index: 46,
			slot: "face",
			name: "rose eyepatch",
			name_cap: "Rose eyepatch",
			variable: "rose eyepatch",
			combat: {
				reference: "eyepatch",
			},
			description: "모든 장미에는 가시가 숨어 있다.",
			cost: 9500,
			shop: ["forest"],
			type: ["formal", "costume"],
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			gender: "n",
			warmth: 0,
			cursed: 0,
			location: 0,
			iconFile: "rose-eyepatch.png",
			accIcon: "rose-eyepatch-acc.png",
			altposition: "none",
			altdisabled: [],
		}),
		new ClothesItem({
			index: 47,
			slot: "face",
			name: "sleeping mask",
			name_cap: "Sleeping mask",
			variable: "sleeping mask",
			combat: {
				reference: "blindfold",
			},
			description: "언제 어디서나 끊김 없는 휴식을 보장합니다.",
			cost: 3500,
			shop: ["clothing"],
			type: ["sleep"],
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 25,
			reveal: 200,
			word: "",
			plural: 0,
			colour: 0,
			colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			pattern: 0,
			pattern_options: ["blank", "aloof", "anime", "cat", "disapproving", "frilled", "quilted", "sleeping"],
			pattern_layer: "primary",
			gender: "n",
			warmth: 1,
			set: "face",
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "sleeping-mask.png",
			accIcon: 0,
		}),
		new ClothesItem({
			index: 48,
			slot: "face",
			name: "swirly glasses",
			name_cap: "Swirly glasses",
			variable: "swirly glasses",
			combat: {
				reference: "glasses",
			},
			description: "전혀 수상하지 않다.",
			cost: 5000,
			shop: ["clothing"],
			type: ["glasses", "mask"],
			integrity: 20,
			integrity_max: 20,
			reveal: 1,
			word: "",
			plural: 0,
			gender: "n",
			warmth: 0,
			iconFile: "swirly-glasses.png",
		}),
		new ClothesItem({
			index: 49,
			slot: "face",
			name: "teardrop glasses",
			name_cap: "Teardrop glasses",
			variable: "teardrop glasses",
			combat: {
				reference: "glasses",
			},
			description: "트렌디한 물방울 모양 안경테다.",
			cost: 5000,
			shop: ["clothing"],
			type: ["glasses"],
			integrity: 20,
			integrity_max: 20,
			reveal: 100,
			word: "",
			plural: 0,
			colour_options: ["black", "white", "navy blue", "wine", "brown", "light pink", "lilac", "red", "tangerine", "teal", "yellow", "custom"],
			gender: "n",
			warmth: 0,
			iconFile: "teardrop-glasses.png",
		}),
	];
	setup.clothes.face = clothing;

	/*
		Clothes that modders add go into this array. This should be empty in the base game at all times.
		These items should have a `modder` variable with the modder's name in a short string.
	*/
	setup.moddedClothes.face = [];

	setup.moddedClothes.face.forEach((x, i) => (x.index = setup.clothes.face.length + i));
	setup.clothes.face.push(...setup.moddedClothes.face);
}
window.initFace = initFace;
