/* globals Dict */
// @ts-check

function finalizefoodstuff() {
	/** @type {Dict<FoodstuffItem>} */
	const sortedCatalog = {};
	Object.keys(setup.foodstuff)
		.sort()
		.forEach(key => {
			sortedCatalog[key] = setup.foodstuff[key];
		});

	setup.foodstuff = sortedCatalog;
}

function initFoodstuff() {
	/** @type {Dict<FoodstuffItem>} */
	setup.foodstuff = {
		red_rose: {
			index: 0,
			name: "붉은 장미",
			singular: "붉은 장미",
			plural: "붉은 장미",
			icon: "red-rose.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 14,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 350,
			},
		},
		white_rose: {
			index: 1,
			name: "하얀 장미",
			singular: "하얀 장미",
			plural: "하얀 장미",
			icon: "white-rose.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 14,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 350,
			},
		},
		orchid: {
			index: 2,
			name: "난초",
			singular: "난초",
			plural: "난초",
			icon: "orchid.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 28,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["summer"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 500,
			},
		},
		daisy: {
			index: 3,
			name: "데이지",
			singular: "데이지",
			plural: "데이지",
			icon: "daisy.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 7,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn"],
				tags: [],
				featCost: 1,
			},
			shop: {
				sell_price: 150,
			},
		},
		tulip: {
			index: 4,
			name: "튤립",
			singular: "튤립",
			plural: "튤립",
			icon: "tulip.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 12,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 200,
			},
		},
		lotus: {
			index: 5,
			name: "연꽃",
			singular: "연꽃",
			plural: "연꽃",
			icon: "lotus.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "water",
				growth_days: 5,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn", "winter"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 300,
			},
		},
		lily: {
			index: 6,
			name: "백합",
			singular: "백합",
			plural: "백합",
			icon: "lily.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 10,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 200,
			},
		},
		poppy: {
			index: 7,
			name: "양귀비",
			singular: "양귀비",
			plural: "양귀비",
			icon: "poppy.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 8,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 200,
			},
		},
		apple: {
			index: 8,
			name: "사과",
			singular: "사과",
			plural: "사과",
			icon: "apple.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 50,
			},
			is_fishing_bait: true,
		},
		orange: {
			index: 9,
			name: "오렌지",
			singular: "오렌지",
			plural: "오렌지",
			icon: "orange.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 300,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		banana: {
			index: 10,
			name: "바나나",
			singular: "바나나",
			plural: "바나나",
			icon: "banana.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 100,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		lemon: {
			index: 11,
			name: "레몬",
			singular: "레몬",
			plural: "레몬",
			icon: "lemon.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 120,
			},
			is_fishing_bait: true,
		},
		blood_lemon: {
			index: 12,
			name: "핏빛 레몬",
			singular: "핏빛 레몬",
			plural: "핏빛 레몬",
			icon: "blood-lemon.gif",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 400,
			},
			food: {
				tags: ["aphrodisiac"],
			},
			is_fishing_bait: true,
		},
		pear: {
			index: 13,
			name: "배",
			singular: "배",
			plural: "배",
			icon: "pear.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 80,
			},
			is_fishing_bait: true,
		},
		strawberry: {
			index: 14,
			name: "딸기",
			singular: "딸기",
			plural: "딸기",
			icon: "strawberry.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 180,
			},
			is_fishing_bait: true,
		},
		peach: {
			index: 15,
			name: "복숭아",
			singular: "복숭아",
			plural: "복숭아",
			icon: "peach.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 65,
			},
			is_fishing_bait: true,
		},
		plum: {
			index: 16,
			name: "자두",
			singular: "자두",
			plural: "자두",
			icon: "plum.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 80,
			},
			is_fishing_bait: true,
		},
		mushroom: {
			index: 17,
			name: "버섯",
			singular: "버섯",
			plural: "버섯",
			icon: "mushroom.png",
			category: "mushroom",
			kitchen_item_type_icon: "recipe-shroom.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 100,
			},
		},
		wolfshroom: {
			index: 18,
			name: "늑대버섯",
			singular: "늑대버섯",
			plural: "늑대버섯",
			icon: "wolfshroom.png",
			category: "mushroom",
			kitchen_item_type_icon: "recipe-shroom.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 300,
			},
			food: {
				tags: ["aphrodisiac"],
			},
		},
		wild_honeycomb: {
			index: 19,
			name: "야생 벌집",
			singular: "야생 벌집",
			plural: "야생 벌집",
			icon: "wild-honeycomb.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			shop: {
				sell_price: 12000,
				stall_size: "large",
			},
		},
		wild_carrot: {
			index: 20,
			name: "야생 당근",
			singular: "야생 당근",
			plural: "야생 당근",
			icon: "carrot.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 10,
				yield_multiplier: 3,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 80,
			},
			is_fishing_bait: true,
		},
		onion: {
			index: 21,
			name: "양파",
			singular: "양파",
			plural: "양파",
			icon: "onion.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 12,
				yield_multiplier: 3,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 120,
			},
			is_fishing_bait: true,
		},
		garlic_bulb: {
			index: 22,
			name: "마늘",
			singular: "마늘",
			plural: "마늘",
			icon: "garlic.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 8,
				yield_multiplier: 3,
				has_seeds: true,
				seasons: ["autumn"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 100,
			},
			is_fishing_bait: true,
		},
		potato: {
			index: 23,
			name: "감자",
			singular: "감자",
			plural: "감자",
			icon: "potato.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 7,
				yield_multiplier: 5,
				has_seeds: true,
				seasons: ["spring", "autumn", "winter"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 50,
			},
			is_fishing_bait: true,
		},
		strange_flower: {
			index: 24,
			name: "이상한 꽃",
			singular: "이상한 꽃",
			plural: "이상한 꽃",
			icon: "strange-flower.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			ingredient_alternatives: {
				normal: ["blood_lemon"],
				lewd: [],
			},
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 28,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn", "winter"],
				tags: [],
			},
			shop: {
				sell_price: 400,
			},
			food: {
				tags: ["aphrodisiac"],
			},
		},
		truffle: {
			index: 25,
			name: "송로버섯",
			singular: "송로버섯",
			plural: "송로버섯",
			icon: "truffle.png",
			category: "mushroom",
			kitchen_item_type_icon: "recipe-shroom.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 800,
			},
		},
		bottle_of_milk: {
			index: 26,
			name: "우유가 든 병",
			singular: "우유가 든 병",
			plural: "우유가 든 병",
			icon: "milk.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			ingredient_alternatives: {
				normal: [],
				lewd: ["baby_bottle_of_breast_milk"],
			},
			tending: {
				affected_by_tending_skill: false,
				tags: [],
			},
			shop: {
				sell_price: 100,
			},
		},
		chicken_egg: {
			index: 27,
			name: "달걀",
			singular: "달걀",
			plural: "달걀",
			icon: "egg.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			ingredient_alternatives: {
				normal: ["bird_egg"],
				lewd: [],
			},
			tending: {
				affected_by_tending_skill: false,
				tags: [],
			},
			shop: {
				sell_price: 40,
			},
		},
		bottle_of_breast_milk: {
			index: 28,
			name: "모유가 든 병",
			singular: "모유가 든 병",
			plural: "모유가 든 병",
			icon: "breastmilk.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			shop: {
				sell_price: 3000,
				stall_size: "large",
			},
		},
		bottle_of_semen: {
			index: 29,
			name: "정액이 든 병",
			singular: "정액이 든 병",
			plural: "정액이 든 병",
			icon: "semenbottle.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: false,
				tags: [],
			},
			shop: {
				sell_price: 3000,
				stall_size: "large",
			},
		},
		cabbage: {
			index: 30,
			name: "양배추",
			singular: "양배추",
			plural: "양배추",
			icon: "cabbage.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 8,
				yield_multiplier: 3,
				has_seeds: true,
				seasons: ["spring", "winter"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 90,
			},
		},
		turnip: {
			index: 31,
			name: "순무",
			singular: "순무",
			plural: "순무",
			icon: "turnip.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 12,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn", "winter"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 130,
			},
		},
		broccoli: {
			index: 32,
			name: "브로콜리",
			singular: "브로콜리",
			plural: "브로콜리",
			icon: "broccoli.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 10,
				yield_multiplier: 3,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 100,
			},
		},
		ghostshroom: {
			index: 33,
			name: "유령버섯",
			singular: "유령버섯",
			plural: "유령버섯",
			icon: "ghostshroom.png",
			category: "mushroom",
			kitchen_item_type_icon: "recipe-shroom.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 200,
			},
		},
		blackberry: {
			index: 34,
			name: "블랙베리",
			singular: "블랙베리",
			plural: "블랙베리",
			icon: "blackberry.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 7,
				stall_size: "small",
			},
			is_fishing_bait: true,
		},
		carnation: {
			index: 35,
			name: "카네이션",
			singular: "카네이션",
			plural: "카네이션",
			icon: "carnation.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 3,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["autumn"],
				tags: [],
				featCost: 20,
			},
			shop: {
				sell_price: 200,
			},
		},
		bird_egg: {
			index: 36,
			name: "새 알",
			singular: "새 알",
			plural: "새 알",
			icon: "bird-egg.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			shop: {
				sell_price: 200,
			},
		},
		baby_bottle_of_breast_milk: {
			index: 37,
			name: "모유가 든 젖병",
			singular: "모유가 든 젖병",
			plural: "모유가 든 젖병",
			icon: "babybottle.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: false,
				tags: [],
			},
			shop: {
				sell_price: 200,
			},
		},
		plumeria: {
			index: 38,
			name: "플루메리아",
			singular: "플루메리아",
			plural: "플루메리아",
			icon: "plumeria.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 12,
				yield_multiplier: 2,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 250,
			},
		},
		oyster_pearl: {
			index: 39,
			name: "굴 진주",
			singular: "굴 진주",
			plural: "굴 진주",
			icon: "oyster-pearl.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			shop: {
				sell_price: 50000,
				stall_size: "large",
			},
		},
		bread: {
			index: 40,
			name: "빵",
			singular: "빵",
			plural: "빵",
			icon: "bread.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			is_fishing_bait: true,
			recipe: {
				recipe_name: "bread",
				difficulty: 1,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["flour", "salt", "vegetable_oil"],
				tags: [],
			},
			food: {
				tags: ["vegan"],
			},
		},
		flour: {
			index: 41,
			name: "밀가루",
			singular: "밀가루",
			plural: "밀가루",
			icon: "flour.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 10,
			},
			recipe: {
				recipe_name: "flour",
				difficulty: 1,
				cook_minutes: 20,
				servings: 10,
				ingredients: ["wheat"],
				tags: [],
			},
		},
		salt: {
			index: 42,
			name: "소금",
			singular: "소금",
			plural: "소금",
			icon: "salt.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 5,
				available_in: ["supermarket"],
				bought_in_bulk: 25,
			},
		},
		vegetable_oil: {
			index: 43,
			name: "식용유",
			singular: "식용유",
			plural: "식용유",
			icon: "vegetable-oil.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 10,
				available_in: ["supermarket"],
				bought_in_bulk: 25,
			},
		},
		pizza: {
			index: 44,
			name: "피자",
			singular: "피자",
			plural: "피자",
			icon: "pizza.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "피자",
				difficulty: 2,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["bread", "tomato", "garlic_bulb", "cheese"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian"],
			},
		},
		tomato: {
			index: 45,
			name: "토마토",
			singular: "토마토",
			plural: "토마토",
			icon: "tomato.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 10,
				yield_multiplier: 4,
				has_seeds: true,
				seasons: ["summer", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 70,
			},
		},
		cheese: {
			index: 46,
			name: "치즈",
			singular: "치즈",
			plural: "치즈",
			icon: "cheese.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 500,
			},
			recipe: {
				recipe_name: "치즈",
				difficulty: 1,
				cook_minutes: 60,
				servings: 1,
				ingredients: ["bottle_of_milk"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian"],
			},
		},
		macaroni_cheese: {
			index: 47,
			name: "마카로니 치즈",
			singular: "마카로니 치즈",
			plural: "마카로니 치즈",
			icon: "macaroni-cheese.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 800,
			},
			recipe: {
				recipe_name: "마카로니 치즈",
				difficulty: 2,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["bottle_of_milk", "cheese", "flour", "pasta", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		pasta: {
			index: 48,
			name: "파스타",
			singular: "파스타",
			plural: "파스타",
			icon: "pasta.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 200,
			},
			recipe: {
				recipe_name: "파스타",
				difficulty: 1,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["flour", "chicken_egg", "vegetable_oil", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		cauliflower_cheese: {
			index: 49,
			name: "콜리플라워 치즈",
			singular: "콜리플라워 치즈",
			plural: "콜리플라워 치즈",
			icon: "cauliflower-cheese.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "콜리플라워 치즈",
				difficulty: 2,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["cauliflower", "cheese", "garlic_bulb", "bottle_of_milk"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		wheat: {
			index: 50,
			name: "밀",
			singular: "밀",
			plural: "밀",
			icon: "wheat.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 9,
				yield_multiplier: 12,
				has_seeds: true,
				seed_name: "밀",
				seasons: ["spring", "summer", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 40,
			},
		},
		prawn_bisque: {
			index: 51,
			name: "새우 비스크",
			singular: "새우 비스크",
			plural: "새우 비스크",
			icon: "prawn-bisque.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1500,
			},
			recipe: {
				recipe_name: "새우 비스크",
				difficulty: 3,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["prawn", "onion", "garlic_bulb", "vegetable_oil", "cream", "lemon"],
				tags: [],
			},
			food: {
				tags: ["seafood"],
			},
		},
		cream: {
			index: 52,
			name: "크림",
			singular: "크림",
			plural: "크림",
			icon: "cream.png",
			category: "produce",
			kitchen_item_type_icon: "recipe-produce.png",
			prop_folder: "tending",
			ingredient_alternatives: {
				normal: [],
				lewd: ["bottle_of_semen"],
			},
			shop: {
				sell_price: 100,
			},
		},
		chelsea_bun: {
			index: 53,
			name: "첼시 번",
			singular: "첼시 번",
			plural: "첼시 번",
			icon: "chelsea-bun.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 200,
			},
			recipe: {
				recipe_name: "첼시 번",
				difficulty: 2,
				cook_minutes: 60,
				servings: 4,
				ingredients: ["flour", "salt", "butter", "sugar", "bottle_of_milk", "honey"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		honey: {
			index: 54,
			name: "꿀",
			singular: "꿀",
			plural: "꿀",
			icon: "honey.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 10,
			},
			recipe: {
				recipe_name: "꿀",
				difficulty: 1,
				cook_minutes: 60,
				servings: 1200,
				ingredients: ["wild_honeycomb"],
				tags: [],
			},
		},
		butter: {
			index: 55,
			name: "버터",
			singular: "버터",
			plural: "버터",
			icon: "butter.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 10,
			},
			recipe: {
				recipe_name: "버터",
				difficulty: 1,
				cook_minutes: 20,
				servings: 10,
				ingredients: ["bottle_of_milk"],
				tags: [],
			},
		},
		naan_bread: {
			index: 56,
			name: "난",
			singular: "난",
			plural: "난",
			icon: "naan-bread.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 200,
			},
			recipe: {
				recipe_name: "난",
				difficulty: 2,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["bottle_of_milk", "flour", "vegetable_oil", "chicken_egg", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		pastry: {
			index: 57,
			name: "페이스트리",
			singular: "페이스트리",
			plural: "페이스트리",
			icon: "pastry.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 150,
			},
			recipe: {
				recipe_name: "페이스트리",
				difficulty: 1,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["butter", "flour", "salt"],
				tags: [],
			},
		},
		quiche: {
			index: 58,
			name: "키시",
			singular: "키시",
			plural: "키시",
			icon: "quiche.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 200,
			},
			recipe: {
				recipe_name: "키시",
				difficulty: 3,
				cook_minutes: 20,
				servings: 6,
				ingredients: ["pastry", "bottle_of_milk", "chicken_egg", "bacon", "cheese", "tomato"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		bacon: {
			index: 59,
			name: "베이컨",
			singular: "베이컨",
			plural: "베이컨",
			icon: "bacon.png",
			category: "meat",
			kitchen_item_type_icon: "recipe-meat.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 200,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		mince_pie: {
			index: 60,
			name: "민스 파이",
			singular: "민스 파이",
			plural: "민스 파이",
			icon: "mince-pie.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 400,
			},
			recipe: {
				recipe_name: "민스 파이",
				difficulty: 2,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["pastry", "blackberry", "sugar"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		sugar: {
			index: 61,
			name: "설탕",
			singular: "설탕",
			plural: "설탕",
			icon: "sugar.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 5,
				available_in: ["supermarket"],
				bought_in_bulk: 25,
			},
		},
		sausage_roll: {
			index: 62,
			name: "소시지 롤",
			singular: "소시지 롤",
			plural: "소시지 롤",
			icon: "sausage-roll.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 150,
			},
			recipe: {
				recipe_name: "소시지 롤",
				difficulty: 2,
				cook_minutes: 40,
				servings: 6,
				ingredients: ["pastry", "salt", "sausage", "chicken_egg", "lemon"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		sausage: {
			index: 63,
			name: "소시지",
			singular: "소시지",
			plural: "소시지",
			icon: "sausage.png",
			category: "meat",
			kitchen_item_type_icon: "recipe-meat.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 200,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		potato_pancake: {
			index: 64,
			name: "감자 팬케이크",
			singular: "감자 팬케이크",
			plural: "감자 팬케이크",
			icon: "potato-pancake.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "감자 팬케이크",
				difficulty: 2,
				cook_minutes: 10,
				servings: 4,
				ingredients: ["potato", "onion", "chicken_egg", "vegetable_oil"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		onion_bhaji: {
			index: 65,
			name: "양파 바지",
			singular: "양파 바지",
			plural: "양파 바지",
			icon: "onion-bhaji.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "양파 바지",
				difficulty: 2,
				cook_minutes: 10,
				servings: 4,
				ingredients: ["flour", "onion", "chilli_pepper"],
				tags: [],
			},
			food: {
				tags: ["vegan", "spicy"],
			},
		},
		chilli_pepper: {
			index: 66,
			name: "고추",
			singular: "고추",
			plural: "고추",
			icon: "chilli-pepper.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				planting_bed: "earth",
				growth_days: 22,
				yield_multiplier: 6,
				has_seeds: true,
				seasons: ["summer", "autumn"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 80,
			},
			is_fishing_bait: true,
		},
		samosa: {
			index: 67,
			name: "사모사",
			singular: "사모사",
			plural: "사모사",
			icon: "samosa.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 60,
			},
			recipe: {
				recipe_name: "사모사",
				difficulty: 3,
				cook_minutes: 15,
				servings: 5,
				ingredients: ["pastry", "potato", "chilli_pepper", "lemon"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "spicy"],
			},
		},
		sweet_and_sour_chicken: {
			index: 68,
			name: "스위트 앤 사워 치킨",
			singular: "스위트 앤 사워 치킨",
			plural: "스위트 앤 사워 치킨",
			icon: "sweet-and-sour-chicken.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 800,
			},
			recipe: {
				recipe_name: "스위트 앤 사워 치킨",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["chicken", "vegetable_oil", "pepper", "sugar", "onion"],
				tags: [],
			},
			food: {
				tags: ["spicy"],
			},
		},
		chicken: {
			index: 69,
			name: "닭고기",
			singular: "닭고기",
			plural: "닭고기",
			icon: "chicken.png",
			category: "meat",
			kitchen_item_type_icon: "recipe-meat.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 300,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		pepper: {
			index: 70,
			name: "피망",
			singular: "피망",
			plural: "피망",
			icon: "pepper.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 15,
				yield_multiplier: 4,
				has_seeds: true,
				seasons: ["spring", "summer", "winter"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 100,
			},
			is_fishing_bait: true,
		},
		kedgeree: {
			index: 71,
			name: "케저리",
			singular: "케저리",
			plural: "케저리",
			icon: "kedgeree.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1600,
			},
			recipe: {
				recipe_name: "케저리",
				difficulty: 3,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["haddock", "rice", "chicken_egg", "butter", "vegetable_oil", "lemon", "cream"],
				ingredient_alternatives: {
					normal: {
						haddock: ["cod", "herring", "mackerel", "salmon", "trout", "whiting", "eel"],
					},
					lewd: {},
				},
				tags: [],
			},
			food: {
				tags: ["seafood"],
			},
		},
		rice: {
			index: 72,
			name: "쌀",
			singular: "쌀",
			plural: "쌀",
			icon: "rice.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "water",
				growth_days: 26,
				yield_multiplier: 20,
				has_seeds: true,
				seed_name: "쌀",
				seasons: ["spring", "summer", "autumn"],
				tags: [],
				featCost: 20,
			},
			shop: {
				sell_price: 50,
			},
		},
		haddock: {
			index: 73,
			name: "해덕대구",
			singular: "해덕대구",
			plural: "해덕대구",
			icon: "haddock.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 600,
				available_in: ["supermarket"],
			},
		},
		honeyed_pork: {
			index: 74,
			name: "꿀 바른 돼지고기",
			singular: "꿀 바른 돼지고기",
			plural: "꿀 바른 돼지고기",
			icon: "honeyed-pork.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1100,
			},
			recipe: {
				recipe_name: "꿀 바른 돼지고기",
				difficulty: 2,
				cook_minutes: 45,
				servings: 1,
				ingredients: ["pork", "salt", "honey", "chicken_egg"],
				tags: [],
			},
			food: {
				tags: ["carnivore"],
			},
		},
		beef_wellington: {
			index: 75,
			name: "비프 웰링턴",
			singular: "비프 웰링턴",
			plural: "비프 웰링턴",
			icon: "beef-wellington.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1800,
			},
			recipe: {
				recipe_name: "비프 웰링턴",
				difficulty: 4,
				cook_minutes: 60,
				servings: 1,
				ingredients: ["beef", "onion", "pastry", "chicken_egg", "salt", "mushroom"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		salmon_wellington: {
			index: 76,
			name: "연어 웰링턴",
			singular: "연어 웰링턴",
			plural: "연어 웰링턴",
			icon: "salmon-wellington.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1800,
			},
			recipe: {
				recipe_name: "연어 웰링턴",
				difficulty: 3,
				cook_minutes: 60,
				servings: 1,
				ingredients: ["salmon", "broccoli", "pastry", "chicken_egg", "salt"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		hamburger: {
			index: 77,
			name: "햄버거",
			singular: "햄버거",
			plural: "햄버거",
			icon: "burger.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 600,
			},
			recipe: {
				recipe_name: "햄버거",
				difficulty: 1,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["beef", "bread", "onion", "tomato"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		cheeseburger: {
			index: 78,
			name: "치즈버거",
			singular: "치즈버거",
			plural: "치즈버거",
			icon: "cheeseburger.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 800,
			},
			recipe: {
				recipe_name: "치즈버거",
				difficulty: 2,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["beef", "bread", "onion", "tomato", "cheese"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		chips: {
			index: 79,
			name: "감자튀김",
			singular: "감자튀김",
			plural: "감자튀김",
			icon: "chips.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 400,
			},
			recipe: {
				recipe_name: "감자튀김",
				difficulty: 2,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["potato", "vegetable_oil", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegan"],
			},
		},
		cheese_topped_trout: {
			index: 80,
			name: "치즈 얹은 송어",
			singular: "치즈 얹은 송어",
			plural: "치즈 얹은 송어",
			icon: "cheese-topped-trout.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1600,
			},
			recipe: {
				recipe_name: "치즈 얹은 송어",
				difficulty: 3,
				cook_minutes: 20,
				servings: 1,
				ingredients: ["trout", "bread", "cheese", "vegetable_oil", "butter", "lemon"],
				tags: [],
			},
			food: {
				tags: ["seafood"],
			},
		},
		salmon: {
			index: 81,
			name: "연어",
			singular: "연어",
			plural: "연어",
			icon: "salmon.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 600,
				available_in: ["supermarket"],
			},
		},
		trout: {
			index: 82,
			name: "송어",
			singular: "송어",
			plural: "송어",
			icon: "trout.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 800,
				available_in: ["supermarket"],
			},
		},
		spaghetti_bolognese: {
			index: 83,
			name: "스파게티 볼로네제",
			singular: "스파게티 볼로네제",
			plural: "스파게티 볼로네제",
			icon: "spaghetti-bolognese.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1100,
			},
			recipe: {
				recipe_name: "스파게티 볼로네제",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["pasta", "beef", "vegetable_oil", "garlic_bulb", "tomato"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		lasagne: {
			index: 84,
			name: "라자냐",
			singular: "라자냐",
			plural: "라자냐",
			icon: "lasagne.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1400,
			},
			recipe: {
				recipe_name: "라자냐",
				difficulty: 3,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["pasta", "beef", "cheese", "flour", "garlic_bulb", "tomato"],
				ingredient_alternatives: {
					normal: {
						beef: ["chicken"],
					},
					lewd: {},
				},
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		carbonara: {
			index: 85,
			name: "까르보나라",
			singular: "까르보나라",
			plural: "까르보나라",
			icon: "carbonara.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "까르보나라",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["pasta", "cheese", "flour", "bottle_of_milk", "pork"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		chicken_tikka_masala: {
			index: 86,
			name: "치킨 티카 마살라",
			singular: "치킨 티카 마살라",
			plural: "치킨 티카 마살라",
			icon: "chicken-tikka-masala.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1700,
			},
			recipe: {
				recipe_name: "치킨 티카 마살라",
				difficulty: 3,
				cook_minutes: 45,
				servings: 1,
				ingredients: ["chicken", "vegetable_oil", "onion", "garlic_bulb", "tomato", "butter", "lemon", "naan_bread", "rice"],
				tags: [],
			},
			food: {
				tags: ["spicy"],
			},
		},
		chilli_con_carne: {
			index: 87,
			name: "칠리 콘 카르네",
			singular: "칠리 콘 카르네",
			plural: "칠리 콘 카르네",
			icon: "chilli-con-carne.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1300,
			},
			recipe: {
				recipe_name: "칠리 콘 카르네",
				difficulty: 3,
				cook_minutes: 45,
				servings: 1,
				ingredients: ["beef", "vegetable_oil", "onion", "garlic_bulb", "tomato", "chilli_pepper"],
				tags: [],
			},
			food: {
				tags: ["spicy"],
			},
		},
		rich_biscuit: {
			index: 88,
			name: "리치 비스킷",
			singular: "리치 비스킷",
			plural: "리치 비스킷",
			icon: "rich-biscuit.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 50,
			},
			recipe: {
				recipe_name: "리치 비스킷",
				difficulty: 1,
				cook_minutes: 20,
				servings: 10,
				ingredients: ["chicken_egg", "flour", "sugar", "lemon"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		shortbread: {
			index: 89,
			name: "쇼트브레드",
			singular: "쇼트브레드",
			plural: "쇼트브레드",
			icon: "shortbread.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 150,
			},
			recipe: {
				recipe_name: "쇼트브레드",
				difficulty: 2,
				cook_minutes: 35,
				servings: 5,
				ingredients: ["butter", "flour", "sugar"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		melting_moment: {
			index: 90,
			name: "멜팅 모먼트",
			singular: "멜팅 모먼트",
			plural: "멜팅 모먼트",
			icon: "melting-moment.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 80,
			},
			recipe: {
				recipe_name: "멜팅 모먼트",
				difficulty: 1,
				cook_minutes: 20,
				servings: 5,
				ingredients: ["butter", "flour", "sugar", "jam"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		choc_chip_cookie: {
			index: 91,
			name: "초코칩 쿠키",
			singular: "초코칩 쿠키",
			plural: "초코칩 쿠키",
			icon: "choc-chip-cookie.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "초코칩 쿠키",
				difficulty: 1,
				cook_minutes: 15,
				servings: 10,
				ingredients: ["butter", "flour", "sugar", "chicken_egg", "chocolate"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		cocoa_powder: {
			index: 92,
			name: "코코아 가루",
			singular: "코코아 가루",
			plural: "코코아 가루",
			icon: "cocoa-powder.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 200,
				available_in: ["supermarket"],
				bought_in_bulk: 5,
			},
		},
		chocolate: {
			index: 93,
			name: "초콜릿",
			singular: "초콜릿",
			plural: "초콜릿",
			icon: "chocolate.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 700,
			},
			recipe: {
				recipe_name: "초콜릿",
				difficulty: 1,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["butter", "bottle_of_milk", "cocoa_powder"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		apple_strudel: {
			index: 94,
			name: "애플 스트루델",
			singular: "애플 스트루델",
			plural: "애플 스트루델",
			icon: "apple-strudel.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "애플 스트루델",
				difficulty: 2,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["pastry", "apple", "sugar", "honey", "butter"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		souffle: {
			index: 95,
			name: "수플레",
			singular: "수플레",
			plural: "수플레",
			icon: "souffle.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 3000,
			},
			recipe: {
				recipe_name: "수플레",
				difficulty: 4,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["chicken_egg", "cream", "sugar", "butter", "flour", "lemon"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		tart: {
			index: 96,
			name: "타르트",
			singular: "타르트",
			plural: "타르트",
			icon: "tart.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "타르트",
				difficulty: 2,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["pastry", "chocolate"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		lemon_meringue_pie: {
			index: 97,
			name: "레몬 머랭 파이",
			singular: "레몬 머랭 파이",
			plural: "레몬 머랭 파이",
			icon: "lemon-meringue-pie.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1600,
			},
			recipe: {
				recipe_name: "레몬 머랭 파이",
				difficulty: 3,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["pastry", "lemon", "sugar", "butter", "chicken_egg"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		sponge_cake: {
			index: 98,
			name: "스펀지 케이크",
			singular: "스펀지 케이크",
			plural: "스펀지 케이크",
			icon: "sponge-cake.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "스펀지 케이크",
				difficulty: 2,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["flour", "butter", "sugar", "cream", "chicken_egg", "jam"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		swiss_roll: {
			index: 99,
			name: "스위스 롤",
			singular: "스위스 롤",
			plural: "스위스 롤",
			icon: "swiss-roll.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1500,
			},
			recipe: {
				recipe_name: "스위스 롤",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["flour", "butter", "cream", "chicken_egg", "jam", "orange", "sugar"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		scone: {
			index: 100,
			name: "스콘",
			singular: "스콘",
			plural: "스콘",
			icon: "scone.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 150,
			},
			recipe: {
				recipe_name: "스콘",
				difficulty: 2,
				cook_minutes: 20,
				servings: 4,
				ingredients: ["flour", "butter", "sugar", "salt", "bottle_of_milk"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		brownie: {
			index: 101,
			name: "브라우니",
			singular: "브라우니",
			plural: "브라우니",
			icon: "brownie.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 300,
			},
			recipe: {
				recipe_name: "브라우니",
				difficulty: 2,
				cook_minutes: 50,
				servings: 4,
				ingredients: ["butter", "flour", "chocolate", "chicken_egg", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		carrot_cake: {
			index: 102,
			name: "당근 케이크",
			singular: "당근 케이크",
			plural: "당근 케이크",
			icon: "carrot-cake.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1400,
			},
			recipe: {
				recipe_name: "당근 케이크",
				difficulty: 2,
				cook_minutes: 50,
				servings: 1,
				ingredients: ["wild_carrot", "sugar", "chicken_egg", "vegetable_oil", "flour", "lemon", "cream", "butter"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		creme_brulee: {
			index: 103,
			name: "크렘 브륄레",
			singular: "크렘 브륄레",
			plural: "크렘 브륄레",
			icon: "creme-brulee.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 600,
			},
			recipe: {
				recipe_name: "크렘 브륄레",
				difficulty: 2,
				cook_minutes: 50,
				servings: 1,
				ingredients: ["bottle_of_milk", "cream", "sugar", "chicken_egg"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		date: {
			index: 104,
			name: "대추야자",
			singular: "대추야자",
			plural: "대추야자",
			icon: "date.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 50,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		sticky_toffee_pudding: {
			index: 105,
			name: "스티키 토피 푸딩",
			singular: "스티키 토피 푸딩",
			plural: "스티키 토피 푸딩",
			icon: "sticky-toffee-pudding.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "스티키 토피 푸딩",
				difficulty: 2,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["date", "flour", "chicken_egg", "butter", "sugar", "bottle_of_milk", "cream"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		chicken_vindaloo: {
			index: 106,
			name: "치킨 빈달루",
			singular: "치킨 빈달루",
			plural: "치킨 빈달루",
			icon: "chicken-vindaloo.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1800,
			},
			recipe: {
				recipe_name: "치킨 빈달루",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["chicken", "vegetable_oil", "chilli_pepper", "onion", "tomato", "lemon", "garlic_bulb", "naan_bread", "rice"],
				tags: [],
			},
			food: {
				tags: ["spicy"],
			},
		},
		flapjack: {
			index: 107,
			name: "플랩잭",
			singular: "플랩잭",
			plural: "플랩잭",
			icon: "flapjack.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "플랩잭",
				difficulty: 2,
				cook_minutes: 25,
				servings: 6,
				ingredients: ["butter", "sugar", "oats", "lemon"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		cherry: {
			index: 108,
			name: "체리",
			singular: "체리",
			plural: "체리",
			icon: "cherry.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 20,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		belgian_bun: {
			index: 109,
			name: "벨지안 번",
			singular: "벨지안 번",
			plural: "벨지안 번",
			icon: "belgian-bun.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "벨지안 번",
				difficulty: 2,
				cook_minutes: 40,
				servings: 10,
				ingredients: ["flour", "sugar", "bottle_of_milk", "chicken_egg", "lemon", "cherry"],
				tags: [],
			},
			food: {
				tags: ["sweet"],
			},
		},
		lime: {
			index: 110,
			name: "라임",
			singular: "라임",
			plural: "라임",
			icon: "lime.png",
			category: "fruit",
			kitchen_item_type_icon: "recipe-fruit.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 250,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		linguine: {
			index: 111,
			name: "링귀네",
			singular: "링귀네",
			plural: "링귀네",
			icon: "linguine.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 700,
			},
			recipe: {
				recipe_name: "링귀네",
				difficulty: 3,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["vegetable_oil", "lemon", "pasta", "cream"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		steak: {
			index: 112,
			name: "스테이크",
			singular: "스테이크",
			plural: "스테이크",
			icon: "steak.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "스테이크",
				difficulty: 3,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["vegetable_oil", "beef"],
				tags: [],
			},
			food: {
				tags: ["carnivore"],
			},
		},
		full_english_breakfast: {
			index: 113,
			name: "잉글리시 브렉퍼스트",
			singular: "잉글리시 브렉퍼스트",
			plural: "잉글리시 브렉퍼스트",
			icon: "full-english-breakfast.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 900,
			},
			recipe: {
				recipe_name: "잉글리시 브렉퍼스트",
				difficulty: 2,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["vegetable_oil", "bacon", "sausage", "mushroom", "tomato", "chicken_egg"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		apple_crumble: {
			index: 114,
			name: "애플 크럼블",
			singular: "애플 크럼블",
			plural: "애플 크럼블",
			icon: "apple-crumble.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 700,
			},
			recipe: {
				recipe_name: "애플 크럼블",
				difficulty: 2,
				cook_minutes: 35,
				servings: 1,
				ingredients: ["apple", "sugar", "flour", "butter", "oats", "cream"],
				tags: [],
			},
			food: {
				tags: ["sweet"],
			},
		},
		bakewell_tart: {
			index: 115,
			name: "베이크웰 타르트",
			singular: "베이크웰 타르트",
			plural: "베이크웰 타르트",
			icon: "bakewell-tart.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "베이크웰 타르트",
				difficulty: 3,
				cook_minutes: 35,
				servings: 1,
				ingredients: ["shortbread", "cream", "cherry"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["sweet"],
			},
		},
		cod: {
			index: 116,
			name: "대구",
			singular: "대구",
			plural: "대구",
			icon: "cod.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 700,
				available_in: [],
			},
		},
		fish_and_chips: {
			index: 117,
			name: "피시 앤 칩스",
			singular: "피시 앤 칩스",
			plural: "피시 앤 칩스",
			icon: "fish-and-chips.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1400,
			},
			recipe: {
				recipe_name: "피시 앤 칩스",
				difficulty: 2,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["cod", "chips", "vegetable_oil", "flour"],
				ingredient_alternatives: {
					normal: {
						cod: ["haddock", "whiting", "flounder", "bass", "perch", "pike"],
					},
					lewd: {},
				},
				tags: [],
			},
			food: {
				tags: ["seafood"],
			},
		},
		clam: {
			index: 118,
			name: "조개",
			singular: "조개",
			plural: "조개",
			icon: "clam.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 400,
				available_in: ["supermarket"],
			},
		},
		clam_chowder: {
			index: 119,
			name: "클램 차우더",
			singular: "클램 차우더",
			plural: "클램 차우더",
			icon: "clam-chowder.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1300,
			},
			recipe: {
				recipe_name: "클램 차우더",
				difficulty: 3,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["clam", "butter", "bacon", "onion", "flour", "bottle_of_milk", "cream", "potato"],
				tags: [],
			},
			food: {
				tags: ["seafood"],
			},
		},
		cheese_and_crackers: {
			index: 120,
			name: "치즈와 크래커",
			singular: "치즈와 크래커",
			plural: "치즈와 크래커",
			icon: "cheese-and-crackers.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 800,
			},
			recipe: {
				recipe_name: "치즈와 크래커",
				difficulty: 1,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["flour", "salt", "sugar", "vegetable_oil", "cheese"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		bangers_and_mash: {
			index: 121,
			name: "뱅어스 앤 매시",
			singular: "뱅어스 앤 매시",
			plural: "뱅어스 앤 매시",
			icon: "bangers-and-mash.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "뱅어스 앤 매시",
				difficulty: 2,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["vegetable_oil", "sausage", "butter", "bottle_of_milk", "potato"],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		yorkshire_pudding: {
			index: 122,
			name: "요크셔 푸딩",
			singular: "요크셔 푸딩",
			plural: "요크셔 푸딩",
			icon: "yorkshire-pudding.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1200,
			},
			recipe: {
				recipe_name: "요크셔 푸딩",
				difficulty: 2,
				cook_minutes: 40,
				servings: 1,
				ingredients: ["flour", "chicken_egg", "bottle_of_milk", "vegetable_oil"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		stuffing: {
			index: 123,
			name: "스터핑",
			singular: "스터핑",
			plural: "스터핑",
			icon: "stuffing.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "스터핑",
				difficulty: 2,
				cook_minutes: 40,
				servings: 6,
				ingredients: ["butter", "vegetable_oil", "onion", "garlic_bulb", "bread", "chicken_egg"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		roast_dinner: {
			index: 124,
			name: "로스트 디너",
			singular: "로스트 디너",
			plural: "로스트 디너",
			icon: "roast-dinner.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 2400,
			},
			recipe: {
				recipe_name: "로스트 디너",
				difficulty: 3,
				cook_minutes: 60,
				servings: 1,
				ingredients: [
					"yorkshire_pudding",
					"stuffing",
					"chicken",
					"beef",
					"pork",
					"potato",
					"wild_carrot",
					"cabbage",
					"onion",
					"turnip",
					"vegetable_oil",
					"salt",
				],
				tags: [],
			},
			food: {
				tags: [],
			},
		},
		crumpet: {
			index: 125,
			name: "크럼펫",
			singular: "크럼펫",
			plural: "크럼펫",
			icon: "crumpet.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "크럼펫",
				difficulty: 2,
				cook_minutes: 20,
				servings: 5,
				ingredients: ["flour", "butter", "salt", "sugar"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		orange_juice: {
			index: 126,
			name: "오렌지 주스",
			singular: "오렌지 주스",
			plural: "오렌지 주스",
			icon: "orange-juice.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "drink",
			shop: {
				sell_price: 55,
			},
			recipe: {
				recipe_name: "오렌지 주스",
				difficulty: 1,
				cook_minutes: 5,
				servings: 2,
				ingredients: ["orange", "sugar"],
				tags: [],
			},
			food: {
				tags: ["vegan", "drink"],
			},
		},
		lemonade: {
			index: 127,
			name: "레모네이드",
			singular: "레모네이드",
			plural: "레모네이드",
			icon: "lemonade.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "drink",
			shop: {
				sell_price: 100,
			},
			recipe: {
				recipe_name: "레모네이드",
				difficulty: 1,
				cook_minutes: 5,
				servings: 2,
				ingredients: ["lemon", "sugar"],
				tags: [],
			},
			food: {
				tags: ["vegan", "drink"],
			},
		},
		banana_bread: {
			index: 128,
			name: "바나나 빵",
			singular: "바나나 빵",
			plural: "바나나 빵",
			icon: "banana-bread.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 500,
			},
			recipe: {
				recipe_name: "바나나 빵",
				difficulty: 2,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["butter", "sugar", "chicken_egg", "flour", "banana"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
			is_fishing_bait: true,
		},
		red_wine: {
			index: 129,
			name: "레드 와인",
			singular: "레드 와인",
			plural: "레드 와인",
			icon: "red-wine.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "drink",
			shop: {
				sell_price: 600,
				available_in: ["supermarket"],
			},
		},
		white_wine: {
			index: 130,
			name: "화이트 와인",
			singular: "화이트 와인",
			plural: "화이트 와인",
			icon: "white-wine.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "drink",
			shop: {
				sell_price: 600,
				available_in: ["supermarket"],
			},
		},
		poached_pear: {
			index: 131,
			name: "와인에 졸인 배",
			singular: "와인에 졸인 배",
			plural: "와인에 졸인 배",
			icon: "poached-pear.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1000,
			},
			recipe: {
				recipe_name: "와인에 졸인 배",
				difficulty: 3,
				cook_minutes: 21,
				servings: 1,
				ingredients: ["pear", "sugar", "red_wine"],
				tags: [],
			},
			food: {
				tags: ["vegan", "alcohol", "sweet"],
			},
		},
		peach_panzanella: {
			index: 132,
			name: "복숭아 판자넬라",
			singular: "복숭아 판자넬라",
			plural: "복숭아 판자넬라",
			icon: "peach-panzanella.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 600,
			},
			recipe: {
				recipe_name: "복숭아 판자넬라",
				difficulty: 2,
				cook_minutes: 30,
				servings: 1,
				ingredients: ["peach", "bread", "cheese", "vegetable_oil", "lemon"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		plum_pudding: {
			index: 133,
			name: "플럼 푸딩",
			singular: "플럼 푸딩",
			plural: "플럼 푸딩",
			icon: "plum-pudding.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1400,
			},
			recipe: {
				recipe_name: "플럼 푸딩",
				difficulty: 3,
				cook_minutes: 25,
				servings: 1,
				ingredients: ["plum", "flour", "bread", "sugar", "orange", "lemon", "cherry", "wild_carrot"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		spinach: {
			index: 134,
			name: "시금치",
			singular: "시금치",
			plural: "시금치",
			icon: "spinach.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 10,
				yield_multiplier: 6,
				has_seeds: true,
				seed_name: "시금치",
				seasons: ["spring", "autumn"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 60,
			},
		},
		salad: {
			index: 135,
			name: "샐러드",
			singular: "샐러드",
			plural: "샐러드",
			icon: "salad.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 1100,
			},
			recipe: {
				recipe_name: "샐러드",
				difficulty: 2,
				cook_minutes: 10,
				servings: 1,
				ingredients: ["spinach", "tomato", "onion", "garlic_bulb", "chilli_pepper", "pepper", "lime"],
				tags: [],
			},
			food: {
				tags: ["vegan"],
			},
		},
		arancini: {
			index: 136,
			name: "아란치니",
			singular: "아란치니",
			plural: "아란치니",
			icon: "arancini.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 700,
			},
			recipe: {
				recipe_name: "아란치니",
				difficulty: 3,
				cook_minutes: 40,
				servings: 4,
				ingredients: ["vegetable_oil", "butter", "onion", "rice", "garlic_bulb", "white_wine", "cheese", "lemon", "flour", "chicken_egg", "truffle"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		wolfbrew: {
			index: 137,
			name: "늑대맥주",
			singular: "늑대맥주",
			plural: "늑대맥주",
			icon: "wolfbrew.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "drink",
			shop: {
				sell_price: 3000,
			},
			recipe: {
				recipe_name: "늑대맥주",
				difficulty: 5,
				cook_minutes: 60,
				servings: 1,
				ingredients: ["wolfshroom", "red_wine", "strange_flower"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "drink", "alcohol", "tainted"],
			},
		},
		ghostbrew: {
			index: 138,
			name: "유령맥주",
			singular: "유령맥주",
			plural: "유령맥주",
			icon: "ghostbrew.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "drink",
			shop: {
				sell_price: 3000,
			},
			recipe: {
				recipe_name: "유령맥주",
				difficulty: 5,
				cook_minutes: 60,
				servings: 1,
				ingredients: ["ghostshroom", "white_wine", "strange_flower"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "drink", "alcohol", "tainted"],
			},
		},
		beef: {
			index: 139,
			name: "소고기",
			singular: "소고기",
			plural: "소고기",
			icon: "beef.png",
			category: "meat",
			kitchen_item_type_icon: "recipe-meat.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 1000,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		pork: {
			index: 140,
			name: "돼지고기",
			singular: "돼지고기",
			plural: "돼지고기",
			icon: "pork.png",
			category: "meat",
			kitchen_item_type_icon: "recipe-meat.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 700,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		cauliflower: {
			index: 141,
			name: "콜리플라워",
			singular: "콜리플라워",
			plural: "콜리플라워",
			icon: "cauliflower.png",
			category: "vegetable",
			kitchen_item_type_icon: "recipe-vegetable.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 30,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "summer", "autumn", "winter"],
				tags: [],
				featCost: 10,
			},
			shop: {
				sell_price: 400,
			},
		},
		oats: {
			index: 142,
			name: "귀리",
			singular: "귀리",
			plural: "귀리",
			icon: "oats.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 100,
				available_in: ["supermarket"],
				bought_in_bulk: 5,
			},
		},
		prawn: {
			index: 143,
			name: "새우",
			singular: "새우",
			plural: "새우",
			icon: "prawn.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			tending: {
				affected_by_tending_skill: true,
				tags: [],
			},
			shop: {
				sell_price: 300,
				available_in: ["supermarket"],
			},
			is_fishing_bait: true,
		},
		omelette: {
			index: 144,
			name: "오믈렛",
			singular: "오믈렛",
			plural: "오믈렛",
			icon: "omelette.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 300,
			},
			recipe: {
				recipe_name: "오믈렛",
				difficulty: 1,
				cook_minutes: 5,
				servings: 1,
				ingredients: ["chicken_egg", "vegetable_oil", "butter"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		porridge: {
			index: 145,
			name: "포리지",
			singular: "포리지",
			plural: "포리지",
			icon: "porridge.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 250,
			},
			recipe: {
				recipe_name: "포리지",
				difficulty: 1,
				cook_minutes: 5,
				servings: 1,
				ingredients: ["oats", "bottle_of_milk"],
				tags: [],
			},
			food: {
				tags: ["vegetarian"],
			},
		},
		turnip_soup: {
			index: 146,
			name: "순무 수프",
			singular: "순무 수프",
			plural: "순무 수프",
			icon: "turnip-soup.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 250,
			},
			recipe: {
				recipe_name: "순무 수프",
				difficulty: 1,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["turnip", "potato", "onion", "vegetable_oil", "salt"],
				tags: [],
			},
			food: {
				tags: ["vegan"],
			},
		},
		pink_rose: {
			index: 147,
			name: "분홍 장미",
			singular: "분홍 장미",
			plural: "분홍 장미",
			icon: "pink-rose.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				affected_by_tending_skill: true,
				planting_bed: "earth",
				growth_days: 14,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["spring", "autumn"],
				tags: [],
			},
			shop: {
				sell_price: 400,
			},
		},
		valentines_chocolate: {
			index: 148,
			name: "발렌타인 초콜릿",
			singular: "발렌타인 초콜릿",
			plural: "발렌타인 초콜릿",
			icon: "valentines-chocolate.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 900,
			},
			recipe: {
				recipe_name: "발렌타인 초콜릿",
				difficulty: 1,
				cook_minutes: 15,
				servings: 1,
				ingredients: ["butter", "bottle_of_milk", "cocoa_powder", "pear"],
				tags: [],
			},
			food: {
				tags: ["vegetarian", "sweet"],
			},
		},
		sunflower: {
			index: 149,
			name: "해바라기",
			singular: "해바라기",
			plural: "해바라기",
			icon: "sunflower.png",
			category: "flower",
			kitchen_item_type_icon: "recipe-flower.png",
			prop_folder: "tending",
			tending: {
				planting_bed: "earth",
				growth_days: 7,
				yield_multiplier: 1,
				has_seeds: true,
				seasons: ["summer"],
				tags: [],
				featCost: 5,
			},
			shop: {
				sell_price: 300,
			},
		},
				jammie_dodger: {
			index: 94,
			name: "잼 도저",
			singular: "잼 도저",
			plural: "잼 도저",
			icon: "jammie-dodger.png",
			category: "dish",
			kitchen_item_type_icon: "recipe-food.png",
			prop_folder: "food",
			shop: {
				sell_price: 80,
			},
			recipe: {
				recipe_name: "잼 도저",
				difficulty: 1,
				cook_minutes: 10,
				servings: 5,
				ingredients: ["flour", "sugar", "butter", "chicken_egg", "jam"],
				tags: [],
			},
			food: {
				handheld_gift: true,
				tags: ["vegetarian", "sweet"],
			},
		},
		jam: {
			index: 95,
			name: "잼",
			singular: "잼",
			plural: "잼",
			icon: "jam.png",
			category: "ingredient",
			kitchen_item_type_icon: "recipe-ingredient.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 200,
			},
			recipe: {
				recipe_name: "잼",
				difficulty: 1,
				cook_minutes: 5,
				servings: 1,
				ingredients: ["strawberry", "sugar"],
				tags: [],
			},
		},
		herring: {
			index: 152,
			name: "청어",
			singular: "청어",
			plural: "청어",
			icon: "herring.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 150,
			},
		},
		whiting: {
			index: 153,
			name: "민대구",
			singular: "민대구",
			plural: "민대구",
			icon: "whiting.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 300,
			},
		},
		mackerel: {
			index: 154,
			name: "고등어",
			singular: "고등어",
			plural: "고등어",
			icon: "mackerel.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 200,
			},
		},
		flounder: {
			index: 155,
			name: "가자미",
			singular: "가자미",
			plural: "가자미",
			icon: "flounder.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 400,
			},
		},
		bass: {
			index: 156,
			name: "베스",
			singular: "베스",
			plural: "베스",
			icon: "bass.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 800,
			},
		},
		roach: {
			index: 157,
			name: "로치",
			singular: "로치",
			plural: "로치",
			icon: "roach.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 80,
			},
		},
		perch: {
			index: 158,
			name: "퍼치",
			singular: "퍼치",
			plural: "퍼치",
			icon: "perch.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 250,
			},
		},
		chub: {
			index: 159,
			name: "처브",
			singular: "처브",
			plural: "처브",
			icon: "chub.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 150,
			},
		},
		pike: {
			index: 160,
			name: "꼬치고기",
			singular: "꼬치고기",
			plural: "꼬치고기",
			icon: "pike.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 800,
			},
		},
		eel: {
			index: 162,
			name: "뱀장어",
			singular: "뱀장어",
			plural: "뱀장어",
			icon: "eel.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 700,
			},
		},
		grayling: {
			index: 163,
			name: "사루기",
			singular: "사루기",
			plural: "사루기",
			icon: "grayling.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			shop: {
				sell_price: 900,
			},
		},
		baitfish: {
			index: 164,
			name: "미끼고기",
			singular: "미끼고기",
			plural: "미끼고기",
			icon: "baitfish.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			is_fishing_bait: true,
			shop: {
				sell_price: 0,
			},
		},
		bait_worm: {
			index: 165,
			name: "미끼용 지렁이",
			singular: "미끼용 지렁이",
			plural: "미끼용 지렁이",
			icon: "bait-worm.png",
			category: "seafood",
			kitchen_item_type_icon: "recipe-seafood.png",
			prop_folder: "ingredient",
			is_fishing_bait: true,
			shop: {
				sell_price: 0,
			},
		},
	};
	finalizefoodstuff();
}
window.initFoodstuff = initFoodstuff;
